### ISSUE TITLE
Several Subscriber's events are never fired

### ISSUE THREAD

**Issue by coldcat-tw** [opentok/opentok-react-native#109]
I notice that several events of [`OTSubscriber`](https://github.com/opentok/opentok-react-native/blob/master/docs/OTSubscriber.md) are never fired, such as `videoDisabled` and `disconnected`.

It would be great to have these events fire correctly.

**Comment by msach22** [comment]
@coldcat-tw Thanks for sharing this, I'll investigate further and update you with my findings!

**Comment by coldcat-tw** [comment]
Yeah it's happening for both iOS and Android.

 Looking forward to hearing from you. :)

**Comment by MaFranceschi** [comment]
I made a PR for this issue based on your comment @msach22 :) the `videoDisabled` and the `disconnect` events work for me.

**Comment by msach22** [comment]
Thanks for the PR @MaFranceschi ! This should be going out with `0.8.0`
