### ISSUE TITLE
iOS Swift Compilation Issue

### ISSUE THREAD

**Issue by steverob** [opentok/opentok-react-native#113]
Hi @msach22 :) I'm wondering if you can help me out with this

![screen shot 2018-06-15 at 1 23 00 pm](https://user-images.githubusercontent.com/1220480/41456836-502f8e34-709f-11e8-8237-265c58b68154.png)

During upgrade to latest version, I did `react-native link` for the package and removed all the previously manually added files.

Then I read in [this comment](https://github.com/opentok/opentok-react-native/issues/108#issuecomment-396358639) that adding the project under `Target Dependencies` is also needed (which was not done automatically by RN Link).

Still I get these issues. Would love some help. 

RN - 55.4
OT-RN - 0.71
OT (Pod) - 2.14.0

**Comment by msach22** [comment]
Hi @steverob, did you add an empty swift file to your project?

**Comment by steverob** [comment]
Yes yes I have that 

--
Regards
Steve Robinson

**Comment by msach22** [comment]
Thanks for letting me know! Could you please share a screenshot of your project structure?

**Comment by matthewmazzuca** [comment]
temporary fix in Pods/gRPC-Core/Interface/gpr_types.h change the anonymous typedef to...

typedef enum gpr_clock_type{
  /** Monotonic clock. Epoch undefined. Always moves forwards. */
  GPR_CLOCK_MONOTONIC = 0,
  /** Realtime clock. May jump forwards or backwards. Settable by
     the system administrator. Has its epoch at 0:00:00 UTC 1 Jan 1970. */
  GPR_CLOCK_REALTIME,
  /** CPU cycle time obtained by rdtsc instruction on x86 platforms. Epoch
     undefined. Degrades to GPR_CLOCK_REALTIME on other platforms. */
  GPR_CLOCK_PRECISE,
  /** Unmeasurable clock type: no base, created by taking the difference
     between two times */
  GPR_TIMESPAN
} gpr_clock_type;

**Comment by steverob** [comment]
No. But not sure what fixed it

--
Regards
Steve Robinson

**Comment by msach22** [comment]
Hmm, that's interesting. I'm going to go ahead and close this issue, but please feel free to re-open if this happens again or you discover any relevant info!
