### ISSUE TITLE
Publisher Stream Destroyed is sometime not called

### ISSUE THREAD

**Issue by dtaborda** [opentok/opentok-react-native#115]
I have an other observation about the functionality of finishing the videocall, if you can see the following screenshot:
when the videocall is finished, the function publisher stream destroyed is called but some time not and publisher stream created is called without destroyed

<img width="839" alt="screen shot 2018-06-13 at 00 44 24" src="https://user-images.githubusercontent.com/882516/41379912-b2b2dd98-6f39-11e8-851d-fee9f9697f74.png">

**Comment by msach22** [comment]
@dtaborda Could you please check if this is still happening if you are using OpenTok iOS SDK 2.15.0?

You can use the 2.15.0 version by updating your Pod file

**Comment by msach22** [comment]
The fix for this has been released with v0.9.4
