### ISSUE TITLE
Android Target API Level 26 required in August 2018

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#120]
The Play store has new requirements for August 2018: Android target API level 26 will be required.

Source:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

React Native is already putting plans in place to move to Android API 26:
facebook/react-native#18095

And some of us have already proactively moved to Android API 26 (myself included).
Will opentok-react-native have problems with this requirement?

**Comment by sunweiyang** [comment]
I've updated my React Native app to Android API level 26 -- this library seems to be working fine. I'll close this for now -- if we see problems, they should probably have their own dedicated issues.

**Comment by msach22** [comment]
@sunweiyang The library should not have any issues with moving to API Level 26. The OpenTok Android SDK supports API Level 16 and above.
