### ISSUE TITLE
Stream audio and video status consistency

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-react-native#126]
# Feature Request

**Description**
> The stream object is not consistent between android and IOS : IOS (as opentok js) uses a hasVideo and a hasAudio boolean while android uses a video or audio boolean

**Proposal**
Add hasVideo and a hasAudio to the android prepareStreamMap function

**Links / references**

**Comment by msach22** [comment]
@mbouxin Thanks for reporting this. I've added some comments on your PR 😄

**Comment by msach22** [comment]
The fix for this will be going out with `v0.8.2`.
