### ISSUE TITLE
Subscriber do not render when using streamProperties without style

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-react-native#128]
# Bug Report

**Current behavior**
> when using OTSubscriber streamProperties without style, the subscriber is not render. This is due to an incorrect use of isNull in this class

**Steps to reproduce**
> just use streamProperties without style

**What is the current *bug* behavior?**
> No rendition of the subscriber

**What is the expected *correct* behavior?**
> The subscriber should render with the style props

For this the line of OTSubscriber

>      const style = isEmpty(streamProperties) ? this.props.style : isNull(streamProperties.style) ? this.props.style : streamProperties.style;

should be replaced by

>      const style = isEmpty(streamProperties) ? this.props.style : isUndefined(streamProperties.style) ? this.props.style : streamProperties.style;

**Comment by msach22** [comment]
Thanks for the PR @mbouxin! This has been released with `v0.8.4`
