### ISSUE TITLE
Sending signals is unintuitive

### ISSUE THREAD

**Issue by jeanregisser** [opentok/opentok-react-native#132]
Hi,

I see the official way to send signals using the lib is rather unintuitive.
It requires you to update the `signal` prop on the `OTSession` component.
Hence you have to `setState` and re-render every time you want to send a new signal.
Also the error result is not exposed and simply logged.

For now I'm bypassing this using the following code:

```jsx
// @flow

import { OT } from 'opentok-react-native/src/OT';

export default {
  sendSignal(type: string, data: Object): Promise<any> {
    return new Promise((resolve, reject) => {
      const signal = { type, data: JSON.stringify(data) };
      if (__DEV__) {
        console.log('[OpenTok] sendSignal', signal);
      }
      OT.sendSignal(signal, (error, result) => {
        if (error) {
          reject(error);
        } else {
          resolve(result);
        }
      });
    });
  },
};
```

It would be nice to officially expose this.

**Comment by msach22** [comment]
@jeanregisser Do you prefer exposing the signal method through the session ref? As for the error issue, we can fix that 😄

**Comment by msach22** [comment]
@jeanregisser Any thoughts on exposing via session ref?

**Comment by msach22** [comment]
@jeanregisser I'm going to close this issue due to inactivity, please re-open if you would like to continue this 😄

**Comment by msach22** [comment]
We've released an update with `v0.10.0` that allows you to send a signal via the `signal` method of the `OTSession` component or via the `signal` prop. Please see the doc changes for more info: 
https://github.com/opentok/opentok-react-native/blob/master/docs/OTSession.md

**Comment by minhnhatspk** [comment]
@msach22 we can not send the signal to the other client without a connected session.
I got this error message `OTRN JS: There was an error sending the signal [object Object]`.
My main purpose is to close the call UI of the user A if the user B declines the call immediately.
Are there other ways to communicate among these OT clients that don't need a connected session?

**Comment by enricop89** [comment]
Hi @minhnhatspk, the signal method requires a connected session as you need WebSocket connection. If you need to send real-time events without a connected session, you can set up a WebSocket connection on your app server or use a 3rd party API

**Comment by enricop89** [comment]
Hi @minhnhatspk, the signal method requires a connected session as you need WebSocket connection. If you need to send real-time events without a connected session, you can set up a WebSocket connection on your app server or use a 3rd party API

**Comment by minhnhatspk** [comment]
Thank you for the answer @enricop89, I ended up this problem by making an API request to my server then use the `signal` method to delete all participants in the current session.
