### ISSUE TITLE
OpenTok can't recover from wifi <=> cellular switching

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#133]
# Bug Report

**Current behavior**
OpenTok connection does not recover when switching between wifi <=> cellular. During a session between 2 users (both with a publisher and subscriber), when one user switches from wifi to cellular network (or vice versa), both users experience pure black subscriber views.

**Steps to reproduce**
1. Start a normal 2-way OpenTok session between 2 users (each user has a publisher and subscriber).
2. Have one of the users switch from wifi to cellular (or vice versa).

**What is the current *bug* behavior?**
The switching user is effectively disconnected from the session.

**What is the expected *correct* behavior?**
OpenTok should be able to recover from network switching within a reasonable time frame (seconds).

If this is expected to be handled client-side, then `opentok-react-native-samples` should include an example of how to handle network switching, since it occurs too frequently to be considered an edge case.

**Comment by msach22** [comment]
@sunweiyang The OpenTok SDKs do have a reconnecting mechanism where they will fire the respective reconnecting events. You should be able to listen to the `sessionReconnecting` and `sessionReconnected` events to see when reconnecting began and completed.

**Comment by msach22** [comment]
@sunweiyang You can use the `sessionReconnecting` and `sessionReconnected` events to display information to the end user about the connection changes.

I'm going to go ahead and close this issue, please re-open if these events are not working for you.
