### ISSUE TITLE
Structure of the error object

### ISSUE THREAD

**Issue by steverob** [opentok/opentok-react-native#135]
Is there any documentation around the structure of the error object being passed into the `error` event handler? @msach22

**Comment by msach22** [comment]
@steverob The error object should have an error code and a message. I just did a quick glance and it looks like this is not consistent throughout the different errors. 

If you're interested, please send a PR, if not I can I try to release this with the next path.

**Comment by steverob** [comment]
@msach22 Ahhhhh!! That's a bummer. I'll see if we can contribute to this. Thanks man.

**Comment by msach22** [comment]
@steverob Let me know if you'll have time to get around to this, if not, I can try to get it out sometime this week 😄

**Comment by msach22** [comment]
@steverob Let me know if you have some time to get around to this, our team will be happy to send over a TokBox t-shirt as a small token of gratitude 😄

**Comment by msach22** [comment]
@steverob I am working on a patch for this, but you should be seeing an object like this:

```
error = {
  code: '',
  message: ''
}
```

The discrepancy I mentioned is internal so it's not something that you should be seeing - I will also update the docs to clarify the error object.

**Comment by msach22** [comment]
This has been fixed and released of `v0.9.9`
