### ISSUE TITLE
Attempt to invoke virtual method 'Session.getSessionId()' on a null object reference

### ISSUE THREAD

**Issue by steverob** [opentok/opentok-react-native#137]
Getting this error on some of our Android devices - 

```
NullPointerException: Attempt to invoke virtual method 'java.lang.String com.opentok.android.Session.getSessionId()' on a null object reference
    at com.opentokreactnative.OTSessionManager.getSessionInfo(OTSessionManager.java:307)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
...
(6 additional frame(s) were not displayed)
```

@msach22  Hey any idea why this error happens? Thanks! :)

**Comment by msach22** [comment]
@steverob Do you have any steps on how I can reproduce this? The only time this should happen is if you call the `getSessionId()` method when the `Session` Object has not been created or has been destroyed.

**Comment by msach22** [comment]
@steverob Any updates on this?

**Comment by steverob** [comment]
@msach22 Sorry man. Thanks for your reply. Its very intermittent and I'm unable to find out solidly when this happens. I'll close this for now. Thanks for your help! :)

**Comment by duenwaldd1** [comment]
I'm getting the same error, not sure how to get around it. It says the error happens at OTSessionManager.java:307, going to find it now

**Comment by duenwaldd1** [comment]
Turned out to be a simple mistake, didn't put in the right apiKey

**Comment by ajatib** [comment]
I have the same problem. I'm using <OTSession> with correct apikey, seesionId & token. When I'm in development mode with my device connected to my computer this works well, but when I make an apk and run it in the same device I get this error in the first attempt, but in the second I can run normally. Any help with this?

**Comment by msach22** [comment]
@ajatib Thanks for sharing - can you please confirm that this is happening with the latest release and which line is causing the crash? Please share the stack trace.
