### ISSUE TITLE
"SyntaxError: Unexpected end of input" when Pause on Exceptions is enabled in React Native Debugger

### ISSUE THREAD

**Issue by snobear** [opentok/opentok-react-native#138]
# Bug Report

**Current behavior**
When using the React Native Debugger (http://localhost:8081/debugger-ui/ in Chrome) with `Pause on Exceptions` enabled, the debugger will pause due to an exception being thrown from Opentok RN.

**Steps to reproduce**

1. Install and run the [BasicVideoChat sample project](https://github.com/opentok/opentok-react-native-samples/tree/master/BasicVideoChat). I specifically ran mine with `yarn run ios`.
2. Open the dev tools menu from the simulator or device and select `Debug JS Remotely` to open the RN debugger in Chrome.
3. Open the Chrome developer console, select the `Sources` tab, and enable `Pause on Caught Exceptions` (checkbox on the far right)
4. Reload the app in the simulator/device and the debugger should pause due to an exception being thrown

Disabling `Pause on Caught Exceptions` allows the app to run OK, but then you can't use the available debugging tools effectively. 

**Example Project**
[BasicVideoChat sample project](https://github.com/opentok/opentok-react-native-samples/tree/master/BasicVideoChat).

This also occurs on the app we're building now, but you can easily reproduce it using the Opentok sample project mentioned.

**What is the current *bug* behavior?**
Pauses on exception.

**What is the expected *correct* behavior?**
There should be no exception to pause on.

**Relevant logs and/or screenshots**

Screenshot:
![image](https://user-images.githubusercontent.com/696230/42853416-42a51cd8-8a04-11e8-9764-0e55c99adadf.png)

Text: 
```
  transformResponse: [function transformResponse(data) {
    /*eslint no-param-reassign:0*/
    if (typeof data === 'string') {
      try {
        data = JSON.parse(data);   # the exception pause happens here!  see screenshot above
      } catch (e) { /* Ignore */ }
    }
    return data;
  }],
```

From what I've read this could be due to a json response not being formatted correctly, or perhaps an empty string being returned.  Thanks for looking into it and let me know if you need more info!

**Comment by ggoldens** [comment]
Hi @snobear this issue seems to be a bit old. Could you please report if you sill have this issue with the latest version? thanks!

**Comment by snobear** [comment]
I don't think its still an issue. Closing.
