### ISSUE TITLE
Changes to `subscribeToAudio` property is not applied dynamically

### ISSUE THREAD

**Issue by steverob** [opentok/opentok-react-native#139]
Here's what I'm doing - I'm taking in a prop called `subscribeToAudio` and I'm using it to build a property object and I feed it into the `OTSubscriber` component. Something like this - 

```
class VideoSubscriber extends Component {
render() {
  return (
    <OTSession apiKey="your-api-key" sessionId="your-session-id" token="your-session-token" eventHandlers={this.sessionEventHandlers}>
      <OTSubscriber
        properties={this.subscriberProperties}
        eventHandlers={this.subscriberEventHandlers}
        style={{ height: 100, width: 100 }}
        streamProperties={{subscribeToAudio: this.props.subscribeToAudio}}
      />
    </OTSession>
  );
}
}
```

Now when this prop changes in the parent component, the changes propagate down but it does not seem to take any effect on the subscriber.

Do I need to do anything differently or is this not supported? Thanks! @msach22

**Comment by steverob** [comment]
@msach22 quick glance [here ](https://github.com/opentok/opentok-react-native/blob/master/src/OTSubscriber.js#L31) tells me we're only checking for updates in the `streamProperties` prop. Am I correct?

**Comment by msach22** [comment]
@steverob The `streamProperties` prop needs the `streamId` to know which stream to update. If you want to update all of the streams with the same properties, you can use the `properties` prop.

Here's some sample code on how to implement `streamProperties`: https://github.com/opentok/opentok-react-native/issues/124#issuecomment-403996366

I'm going to close this issue, but please re-open if the issue still persists.

**Comment by steverob** [comment]
@msach22 Got it. The code I pasted was a bit incorrect. I'm not using `streamProperties`. I just want to apply mute to the entire session on the subscriber end.

Changing properities only on the `properties` prop does not seem to work . Can you confirm please?

**Comment by msach22** [comment]
@steverob Thanks for updating! Apologies for the confusion, but the `properties` prop is for used when we subscribe to streams. To update them, you would have to use the `streamProperties` props as I linked above.
