### ISSUE TITLE
Portrait streaming and video resolution

### ISSUE THREAD

**Issue by steverob** [opentok/opentok-react-native#140]
Hi @msach22, just need a clarification on portrait orientation streaming. I've set our resolution to be `1280x720`, but our app is set to stream video in Portrait orientation.

How does OpenTok handle this? Does it detect the orientation and rotate video or does it do a a center crop of the 720p frame?

Thanks!

**Comment by JayTokBox** [comment]
Hi @steverob , sorry for the late response.

The phone detects the orientations and we set the orientation mode within the frame. No cropping is done. (https://github.com/opentok/opentok-ios-sdk-samples/blob/master/Custom-Video-Driver/Lets-Build-OTPublisher/TBExampleVideoCapture.m#L768)

**Comment by ggoldens** [comment]
Hi @steverob I hope the answer from @JayTokBox was helpful. I'll close this issue, but let us know if you have any other question.
Thanks!

**Comment by jameschou-bk** [comment]
Hi @IGitGotIt !

Having an issue related device orientation where the initial orientation mode is set to landscape even if the tablet is in portrait mode and the stream displayed is rotated 90 degrees. Is there a way to customize the initial orientation of the session?
