### ISSUE TITLE
Multiple Xcode projects found, please specify one

### ISSUE THREAD

**Issue by wzup** [opentok/opentok-react-native#152]
I follow your [iOS installation guide](https://github.com/opentok/opentok-react-native#ios-installation) and get:

> [!] Multiple Xcode projects found, please specify one

Explain how to solve it.

I understand it is not your issue per se, but at lease you can explain how to solve it

**Comment by msach22** [comment]
Hmm, could you please outline the steps and where you're getting this message?

**Comment by wzup** [comment]
I had two projects in my `ios` folder. I deleted one I do not use anymore. And it works ok now.
