### ISSUE TITLE
<YourProjectName>.xcworkspace IS NOT a file

### ISSUE THREAD

**Issue by wzup** [opentok/opentok-react-native#154]
You write 

> _Open <YourProjectName>.xcworkspace file in XCode. This file can be found in the ios folder of your React Native project._

But it IS NOT a file. It is a directory. 

![screen shot 2018-08-15 at 4 17 14 pm](https://user-images.githubusercontent.com/3880497/44150148-1df924d8-a0a7-11e8-9936-6c5ce1a160bd.png)

What file should I open then?

**Comment by msach22** [comment]
Thanks for reporting! This is a README typo that we can fix with the next release.

Please open the `.xcworkspace` contents with XCode to get started

**Comment by sunweiyang** [comment]
If you open .xcworkspace's parent directory in Finder, you can then double click the .xcworkspace's icon to open it in Xcode.
