### ISSUE TITLE
Request for unified 'react-native link` package setup for both iOS and Android

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#16]
This `opentok-react-native` package has rather manual setup steps for iOS, and only uses `react-native link` for Android.

The common practice now is to use `react-native link` for efficient package setup, with optional manual steps to replace `react-native link` when problems arise.

**Comment by msach22** [comment]
@sunweiyang Agreed! It's on our ToDo list to get it working for iOS as well!

**Comment by msach22** [comment]
@ASerga Thanks for reporting this! I'll investigate into this and see what we can do!

**Comment by msach22** [comment]
@sunweiyang @ASerga Just wanted to update you folks that this is a WIP and should go out with `0.7.0`

**Comment by emin93** [comment]
Usually I'm not fanboying things, but this time: A BIG thank you! I was so close to giving up on integrating audio / video chat in my app before I stumbled upon OpenTok. Everything just worked flawlessly! Great documentation and clean integration.

As soon as the iOS setup works with `react-native link` as well, it will be the perfect module! 😃

P.S. GitHub needs an appreciation page for repositories 😄

**Comment by msach22** [comment]
Thanks for the kind words @emin93! 

I've opened a PR for the `react-native link` installation, but it still requires you to create an empty swift file in your iOS project to avoid a compiling error. If anyone else has a solution, please feel free to share!

**Comment by sunweiyang** [comment]
@msach22 Thanks again! And perhaps this might give some insight:
https://github.com/rhdeck/react-native-swift

**Comment by msach22** [comment]
@sunweiyang Looks like this package is also creating an empty swift file: https://github.com/rhdeck/react-native-swift/blob/master/bin/postlink.js#L35

When you create a Swift file, XCode creates a `Objective-C Generated Interface Header Name` which is needed to import Swift into Objective-C.

**Comment by msach22** [comment]
Also mentions the need to add an empty file: 
https://github.com/rhdeck/react-native-swift/blob/master/README.md#how-it-works

**Comment by msach22** [comment]
@sunweiyang In any case, I think I'm going to proceed with the empty swift file solution for now and improve as we can. I know it's not a optimal solution, but it is still a step forward because it allows you to use the library without having to use `use_frameworks`.

**Comment by MaFranceschi** [comment]
Thanks for this improvement @msach22 ! I've taken the desition to migrate to this library from `react-native-opentok` and this changes will be very useful to me because I'm having some problems with others libraries with the `use_framework` flag.

**Comment by msach22** [comment]
Released with `0.7.0`
