### ISSUE TITLE
Errors in OTSessionManager on IOS

### ISSUE THREAD

**Issue by YYH123123** [opentok/opentok-react-native#166]
I am developing an app using opentok sdk and it is quite working well.
But sometimes(not that much frequently tho) I got several error reports when users tried to enter the screen which uses opentok library.

These are reports on errors from firebase and they are callstack given by firebase when errors occur:
///
1
OTSessionManager.swift - 221st line
specialized OTSessionManager.prepareJSEventData(OTStream) -> [String : Any]

2
OTSessionManager.swift - 366th line
specialized OTSessionManager.publisher(OTPublisherKit, streamDestroyed : OTStream) -> ()

3
@objc OTSessionManager.session(OTSession, connectionCreated : OTConnection) -> () + 4332367704

4
__56-[OTKitPublisherDelegate otkitPublisherStreamDestroyed:]_block_invoke + 1333676

5
libdispatch.dylib
_dispatch_call_block_and_release + 24

12
UIKit
UIApplicationMain + 236

13
main.m - 14th line
main
///

Additionally, crash happens even before the connection is made from time to time.

Why do these errors occur? Is there anything I can do fix the problems? Or can you edit the library for these problems not to happen?

For you information, I am using the latest version of library.

**Comment by msach22** [comment]
@YYH123123 Apologies for the delay here, can you share the device and iOS version? Please also provide any steps that will allow me to reproduce this issue on my end so I can investigate further.

**Comment by msach22** [comment]
@YYH123123 Did you get a chance to see my previous message? Could you please provide any relevant information about the reproduction steps?

**Comment by msach22** [comment]
@YYH123123 I'm going to go ahead and close this issue, but please feel free to re-open if it still persists.
