### ISSUE TITLE
New streams loading in incorrect order

### ISSUE THREAD

**Issue by profburial** [opentok/opentok-react-native#167]
# Bug Report

**Current behavior**
When a new stream is loaded, the subscriber component shows the video stream from the first stream loaded instead of the newest stream. For example, if a subscriber is first streaming their camera, and then streams shares their screen, the user's camera stream is still being displayed instead of their screen. 

**Steps to reproduce**

- Publish stream with user's camera
- Publish stream of a user's screen (screensharing)
- View subscriber component video output

**What is the current *bug* behavior?**
> See "Current Behavior"

**What is the expected *correct* behavior?**
> When a user publishes an additional stream, subscribers should be able to see that stream

**Comment by msach22** [comment]
@profburial Apologies for getting to this late. Going to go ahead and close the issue because we're not seeing this happen with the latest release. Please feel free to re-open if this persists.

**Comment by rajat-np** [comment]
I face the similar issue @msach22. What can we do to subscribe to the latest stream ? I have the similar use case, when the screenshare stream is created, the previous stream should not be displayed.

**Comment by msach22** [comment]
@rajat-np Hmm, I'm not sure if this is the same issue. Could you please file a new issue where you only want to subscribe to a specific stream? It's harder to track closed issues and these are not the same 😄

**Comment by rajat-np** [comment]
@msach22 It's same. I want that as soon screensharing stream is created, it should be visible to the person instead of the camera. The use case of both is same.

**Comment by msach22** [comment]
This current issue is asking about loading streams in incorrect order whereas you are requesting the ability to subscribe to a specific stream, not load it in order.  I've filed for a feature request here:  https://github.com/opentok/opentok-react-native/issues/268

**Comment by rajat-np** [comment]
Is there a workaround to cater this requirement ?
