### ISSUE TITLE
[Feature request] styling subscribers container View

### ISSUE THREAD

**Issue by riourbana** [opentok/opentok-react-native#170]
# Feature Request

**Description**
Styling the subscribers container View in the OTSubscriber component would be useful (e.g. adding padding, flex-direction, spacing in case of multiple subscribers).

**Proposal**
I would add an additional prop (something like _containerStyle_) to OTSubscriber.

**Comment by msach22** [comment]
This is a duplicate of: https://github.com/opentok/opentok-react-native/issues/170

This issue will be addressed with the v0.9.8 release
