### ISSUE TITLE
Support to audio output route ear/speaker

### ISSUE THREAD

**Issue by renanpupin** [opentok/opentok-react-native#173]
It will be nice if we have audioOutputRoute property explicit at OTSubscriber object.

`
<OTSubscriber audioOutputRoute={"ear"} />
`

or 

`
<OTSubscriber audioOutputRoute={"speaker"} />
`

**Comment by Carlosp16** [comment]
For now you can use IncallManager library for that.

**Comment by daft300punk** [comment]
Using InCallManager( https://www.npmjs.com/package/react-native-incall-manager) doesn't work for me. Anyone had any success with it? Is there any other way to route audio through the earpiece rather than the default speaker?

**Comment by renanpupin** [comment]
Yeah, it does not work with OT.

**Comment by flogy** [comment]
Would required this feature as well. Is there any update on this?

**Comment by enricop89** [comment]
Duplicate of #159
