### ISSUE TITLE
Share screen of all device

### ISSUE THREAD

**Issue by eashevchenko** [opentok/opentok-react-native#177]
Could i share screen of all device instead of share application screen ? Thanks !

**Comment by msach22** [comment]
@eashevchenko Unfortunately, this is not support by the OpenTok iOS or Android SDK so as of now, it's not possible to do this.

**Comment by msach22** [comment]
@eashevchenko I'm going to go ahead and close this issue because it's not a native feature that we support. Please let me know if you have any questions.
