### ISSUE TITLE
OTSubscriber audio/videoNetworkStats values

### ISSUE THREAD

**Issue by evillemez** [opentok/opentok-react-native#179]
Registering handlers for `OTSubscriber.audioNetworkStats` and `OTSubscriber.videoNetworkStats` received unexpected values in the event received.

When `OTPublisher.publishAudio`, or `OTPublisher.publishVideo` are `true`, the `OTSubscriber.audioNetworkStats` and `OTSubscriber.videoNetworkStats` methods receive events with varying values for the a/v bytes/packets received, and a/v packet loss, as expected.

However, when `OTPublisher.publishAudio`, or `OTPublisher.publishVideo` are `false`, or the publishing side has lost their connection, then events continue to fire with the values from the most recently received value.  We would expect all the values to be `0`, because no a/v is being received.

The docs don't mention the format of the information received for these events, or what the expected values should be in certain cases.  This feels like a bug, but we don't technically know what the expected behavior is.

**Comment by msach22** [comment]
@evillemez The subscriber network stats(`audioNetworkStats` and `videoNetworkStats`) are cumulative. This means that you can check the values of the data and compare them to the values of the event that was triggered before. If the delta is 0, you would see that no data was received.
