### ISSUE TITLE
Detecting failure to publish stream

### ISSUE THREAD

**Issue by evillemez** [opentok/opentok-react-native#180]
Over the past week we've detected a large increase in one side of conversations failing to publish their stream.  The result is that both sides enter a session, but can't see/hear each other due to a failure to publish the stream.  Part of this could be connectivity problems we have no control over, but we're having a difficult time getting our app to detect and respond properly.

How do we detect when this happens using this library?  Being able to detect a case like this, both from the publishing and subscribing side is really important and we have not been able come up with a reasonable solution.  We're concerned that we have failure cases we cannot detect and respond to for the users.

**Comment by msach22** [comment]
@evillemez Thanks for opening an issue. I'm sorry to hear that you're seeing publish failures. You can set an `error` event listener for the `OTSession` component which should allow you to see the error code and message. You can then use the error code and messages to cross check it with the [iOS](https://tokbox.com/developer/sdks/ios/reference/) or [Android](https://tokbox.com/developer/sdks/android/reference/) SDKs API reference.

**Comment by evillemez** [comment]
@msach22 Thanks - is there any documentation about the error object received there?  It could be that a lot of what we're expecting to see triggered in other methods are actually triggered by the error message instead.  Is it just `{"code": ...., "message": ....}`.

Are the error codes consistent across Android/iOS, or do we need to take into account platform differences here?

**Comment by msach22** [comment]
Good point, there is no documentation on the `error` object so we should probably add that.

Yes, that's how the error object should be. The codes will vary because these are two different platforms.

You can find the full list of when the errors are triggered: 
https://tokbox.com/developer/sdks/ios/reference/Classes/OTError.html
https://tokbox.com/developer/sdks/android/reference/com/opentok/android/OpentokError.ErrorCode.html

Lastly, please keep in mind that the error object can be dispatched from `OTPublisher`, `OTSession`, and `OTSubscriber`.

**Comment by msach22** [comment]
Each component has their own `error` event and details about when they are dispatched can be found here in the docs: https://github.com/opentok/opentok-react-native/tree/master/docs

When simulating a network failure, the `connectionDestroyed` event will be dispatched (this is tied to `OTSession`). This event would also contain a reason of why the connection was destroyed i.e `clientDisconnected`, `forceDisconnected`, or `networkDisconnected`.

The `disconnect` event for the subscriber is dispatched when the `stream` is interrupted meaning that the audio-video stream is temporarily disconnected.

Hope this helps clarify some things!

**Comment by evillemez** [comment]
Hi @msach22 Thanks for that clarification.

I think our problem is that we're just not seeing the behavior we expect.  We've tried various approaches - logging both `connectionDestroyed` on the session, `disconnect` on the subscriber, and also the `error` events on all the components.

Our scenario is this: a publisher and a subscriber have successfully subscribed to each other's streams, so are in the session.  On the publishing side, we'll put that device into airplane mode.  Usually the `OTSession.disconnected` event will fire for the publishing side soon after.  On the subscribing side, however, nothing fires.  Several minutes go by before any of the relevant events are triggered.

Based on the documentation for the library, I feel like we've tried everything that's reasonable to try.  So I'm wondering now if something is going on in the native libraries.  Are we just simulating connection failures incorrectly or something?

**Comment by msach22** [comment]
@evillemez You should also be able to listen to `streamCreated`, `streamDestroyed`, and `error` for `OTPublisher` to see know when the stream started to publish, stopped publishing, or had an error.

Please let me know if that works for you.

**Comment by msach22** [comment]
@evillemez Were you able to check the `streamCreated,`streamDestroyed`, and `error` events for the publisher to when the publisher started streaming, stopped, or had an error?

**Comment by evillemez** [comment]
@msach22 Sorry for the delay. We're working on including more internal forensics in our app to get a better read on this, but it's not live yet.  We have it working in testing, but we can't consistently reproduce the failures we want to reproduce there, so it's hard to say.

We did add logic to remount the session/publisher/subscriber in cases where errors are triggered, but we can't actually tell if that's helping yet.

**Comment by evillemez** [comment]
@msach22 Working on something related to this, a question came up.  I know the publisher/subscribers make multiple attempts internally to do their thing.  How much time goes by before the publisher or subscriber would call the error handler?  Is there a max time limit, like 30 seconds?

I'm reworking how connections get set up initially, and at the moment I'm giving both sides 30s to let the connection get established before considering the call "failed" and ending it.  But, if the publisher/subscriber only trigger their error handler after 30s or so, that just may not be enough time.

Do you have any thoughts on it?

**Comment by msach22** [comment]
@evillemez Apologies for missing this. There are two error handlers - one is an event that's dispatched (asynchronous) and another is a synchronous error callback that's triggered if there is any error when publishing. 

I've added an event(`otrnError`) with the `v0.10.0` which gets dispatched if there are issues with the synchronization between the native layer and the JS layer. For example, if the JS layer tries to publish and the native publisher instance can not be found for any reason, we dispatch that event. Could you please use the `otrnError` event to see if that helps with this situation?

**Comment by evillemez** [comment]
As far as I can tell, the error callbacks work as expected for detecting the publisher/subscriber errors.  Our issue now is dealing with unexpected signals after a reconnection event, but it's a separate issue at this point, so I'll close this.

**Comment by msach22** [comment]
Thanks for confirming, @evillemez. Please file an issue with the unexpected signals.

On another note, we fixed a signaling issue with `v0.10.1` where empty signals were being sent even when you didn't specify it.
