### ISSUE TITLE
OTSession fails to complete OT.connect

### ISSUE THREAD

**Issue by AbsohAbsoh** [opentok/opentok-react-native#182]
# Bug Report

**Current behavior**
Using the simple tutorials to get a session running, the OTSession manager appears blank. 
```
<OTSession apiKey={this.props.api_key} sessionId={this.props.session_id} token={this.props.token}>
    <OTPublisher style={{ width: 100, height: 100 }} />
    <OTSubscriber style={{ width: 100, height: 100 }} />
</OTSession>
```
I've ensured the props are all there, and upon investigating the OTSession component the console log stops returning anything around the OT.connect helper function.

**Steps to reproduce**
Below is the createSession method with logging:
```
  createSession(credentials) {
    OT.initSession(credentials.apiKey, credentials.sessionId);    
    console.log("Initialization log"); // Logs to the debugger
    OT.connect(credentials.token, (error) => {
      if (error) {
        console.log("Error log"); // Doesn't reach this log 
        handleError(error);
      } else {
        console.log("Smooth running"); // Doesn't reach this log
        OT.getSessionInfo((session) => {
          if (!isNull(session)) {
            const sessionInfo = { ...session, connectionStatus: getConnectionStatus(session.connectionStatus)};
            this.setState({
              sessionInfo,
            });
            logOT(credentials.apiKey, credentials.sessionId, 'rn_on_connect', session.connection.connectionId);
            const signalData = sanitizeSignalData(this.props.signal);
            OT.sendSignal(signalData, signalData.errorHandler);
          }
        });
      }
    });
  }
```

**What is the current *bug* behavior?**
The OT.connect method isn't being reached for either if/else.

**Comment by msach22** [comment]
@AbsohAbsoh Thanks for filing an issue. Can you please share if this is happening for iOS or Android? Which version of this library are you using?

**Comment by msach22** [comment]
@AbsohAbsoh Could you please check if your credentials are valid? I'm unable to reproduce the issue, the callback on the native layer always works for me regardless of being an error or no error

**Comment by msach22** [comment]
@AbsohAbsoh Can you please confirm if you're seeing this with v0.9.0?

**Comment by hardikjs** [comment]
As per native code the connect has 3 arguments need to be passed

```
OT.connect(this.sessionId, this.token, (error) => {
	if (error) {
		console.log('Error log', error); // Doesn't reach this log
	} else {
		console.log('Smooth running'); // Doesn't reach this log
	}
});
```

Also initSession session has 3 arguments need to be passed 

Check here https://github.com/opentok/opentok-react-native/blob/f943e1c147b8bcc104fdbfa289e49edf9162f141/android/src/main/java/com/opentokreactnative/OTSessionManager.java#L128
