### ISSUE TITLE
no such file or directory:  /Library/Developer/Xcode/DerivedData/[project_name]-gqnxcdepkzfjroeibqodgvdtvvne/Build/Products/Debug-iphoneos/libOpenTokReactNative.a in react native opentok

### ISSUE THREAD

**Issue by nimeshbhalani7** [opentok/opentok-react-native#184]
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by msach22** [comment]
@nimeshbhalani7 Thanks for reporting this. Can you confirm if you've tried the following:

```
   Go to Target -> Build Phases and add OpenTokReactNative under Target Dependencies. After that go to the Link Binary With Libraries section and remove the libOpenTokReactNative.a and add it again.

```

**Comment by nimeshbhalani7** [comment]
@msach22 It is working fine

**Comment by msach22** [comment]
Happy to help! I'm going to go ahead and close the issue.
