### ISSUE TITLE
EventUtils Error

### ISSUE THREAD

**Issue by hero70312** [opentok/opentok-react-native#190]
I have upgrade to version 0.9.0
There was another issue occurred  when I am was testing the BasicVideoChat example.
I tried to open and close the camera. 
set publish property:
```
 publishVideo: true or false,
```

I closed the camera of USER1 cause screen of USER2 got stuck.

I opened the camera of USER2 cause screen of USER2 got stuck

Then Xcode Indicate that there is a err in **EventUtils.swift -> prepareJSStreamEventData**

![2018-11-05 4 50 01](https://user-images.githubusercontent.com/14068699/47987884-a4cc0200-e11b-11e8-93f3-f9ade8bf027a.png)

![2018-11-05 4 48 27](https://user-images.githubusercontent.com/14068699/47987872-9d0c5d80-e11b-11e8-9509-e9f4a31b8b36.png)

**Comment by msach22** [comment]
Thanks @hero70312! I will see if I can create an environment where I can reproduce this reliably - thanks for your patience.

**Comment by msach22** [comment]
@hero70312 @mbouxin This is an issue with the iOS SDK - I have filed it internally and will update this issue once we have a patch available.

**Comment by Artemnsk** [comment]
Hello gentlemen,
I have very similar issue: _randomly_ app crashes in prepareJSStreamEventData() function body. It happens for **subscriber** when **publisher** closes and reopens app.

![ot-error](https://user-images.githubusercontent.com/2211933/49777785-87024600-fd34-11e8-8bf5-2a2ae81d0b34.png)
- iOS OpenTok 2.15.0
- opentok-react-native 0.9.0

It is not related to explicit switching publishVideo publishing property but IMO similar kind of switching happens behind the scenes when publisher closes and then resumes app.
Hopefully that will be helpful, thanks!

**Comment by msach22** [comment]
This issue will be fixed with v0.9.2 - we are planning to release a patch with the native SDKs (2.15.2) in the very near future.

**Comment by msach22** [comment]
This has been fixed and released with v0.9.2 - note that you have to upgrade to `2.15.2` SDK for this to work.
