### ISSUE TITLE
Initial signal on session creation (v0.9)

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-react-native#192]
# Bug Report

**Current behavior**
On IOS I always get a message "OTRN JS: There was an error sending the signal ${error}" when creating a session. This is due to the fact that when I create my OTSession object I do not use the "signal" props. In this configuration, an empty signal {type: "", message: ""} is sent to the swift which do not send it and resolve with this error.

This does not happen on android as, if I understand well the opentok documentation, no error is provided when the sendSignal did not work on android (therefore, the error callback is invoked with no error provided). 

**Steps to reproduce**
Create an OTSession on ios without signal prop

**What is the expected *correct* behavior?**
IMO, if signal prop is not provided, no signal should be sent. 

I can make the fix if you agree on the expected behavior I propose

**Comment by msach22** [comment]
@mbouxin Thanks for reporting the issue! Please do propose a PR 😄

**Comment by msach22** [comment]
@mbouxin I believe this is a bug with the iOS 2.15.0 SDK. I will update you as soon as I have more info!

**Comment by msach22** [comment]
@mbouxin For now, please use the 2.14 SDK on iOS. You can do this by changing the version number in the Podfile.

**Comment by mbouxin** [comment]
@msach22 Thanks for the analysis !

**Comment by msach22** [comment]
@mbouxin We have released the patch for this issue in the native iOS SDK - please update your pod file to use `2.15.1`. I'm also going to release v0.9.1 which will have the updated readme along with the updated android sdk

**Comment by mbouxin** [comment]
@msach22 Tested it: it works. Thanks !
