### ISSUE TITLE
Cannot find symbol MATRIX_SAVE_FLAG

### ISSUE THREAD

**Issue by TeruyaHaroldo** [opentok/opentok-react-native#197]
Hi. I having this issue when I am trying to run `react-native run-android`. I updated Android Gradle to `classpath 'com.android.tools.build:gradle:3.2.1'` and Android compileSdkVersion and buildToolsVersion 28.

```
> Task :opentok-react-native:compileDebugJavaWithJavac FAILED
../node_modules/opentok-react-native/android/src/main/java/com/opentokreactnative/OTScreenCapturer.java:50: error: cannot find symbol
                canvas.save(Canvas.MATRIX_SAVE_FLAG);
                                  ^
  symbol:   variable MATRIX_SAVE_FLAG
  location: class Canvas
1 error
```

**Comment by fatiago** [comment]
Hi @TeruyaHaroldo did you reach any solution?
Thanks

**Comment by podvipodvert** [comment]
any updates?

**Comment by tarunmehta-quovantis** [comment]
@podvipodvert @fatiago  any solution ?

**Comment by fatiago** [comment]
@tarunmehta-quovantis I simple delete the 2 lines code where that flag appear.

**Comment by tarunmehta-quovantis** [comment]
@fatiago , Will have to delete flag inside node_modules - > OtScreenCapture ?

**Comment by jyotigupta007** [comment]
Hello, Anyone has found solution for this. As I am also facing the same issue.

**Comment by tarunmehta-quovantis** [comment]
@jyoti you will have to comment that line and replace with canvas.save()

**Comment by jyotigupta007** [comment]
@tarunmehta-quovantis thanks for the help. it worked

**Comment by msach22** [comment]
@TeruyaHaroldo Thanks for the fix - could you please make a PR with this change?

**Comment by msach22** [comment]
This has been released with v0.9.6

**Comment by smakosh** [comment]
It's really frustrating the amount of issues I've ran into using your library.

**Comment by steebchen** [comment]
@smakosh feel free to contribute to make it more robust

**Comment by msach22** [comment]
@smakosh Apologies if this library does not meet your standards, but I think it's important to note that this is an open source labs project that's not officially support by TokBox. It was developed to help React Native developers get started with real time video and we've seen many developers use it successfully. We welcome any and all contributions so if you think there are areas we can improve, please file an issue or submit a PR so the community members and I can review it 😄

**Comment by smakosh** [comment]
Sure, opening my first issue! (managed to solve others so far)
