### ISSUE TITLE
OpenTok seems to crash when videoSource is set to "screen"

### ISSUE THREAD

**Issue by zaidSimajji** [opentok/opentok-react-native#198]
**Current behavior**
OpenTok OTPublisher seems to crash/ freeze after interacting with the screen and "videoSource" is set to "screen". This seems to affect the app itself as well to a certain extent as my Back button no longer works as well (however some element on the screen seems to still be working).

**Steps to reproduce**
1. Set the OTPublisher's videoSource to 'screen'
2. Have a webview image that covers the screen so that OTPublisher will show something as well
3. Run the project on Android device
4. Interact with  the webview like scrolling up and down
5. The image in OTPublisher will stop moving after a few movements

**Other Info**
I've tried digging around a bit (by using Log) and from what I can tell the crash might be happening in OTScreenCapturer.java in the line

`contentView.draw(canvas);`

as the line before it was shown in Log but the line after isn't.

Device tested:
1. Lenovo (Tab) YT3-850M; Android 5.1.1, API 22
2. Xiaomi Redmi Note 4; Android 6.0, API 23

**Comment by msach22** [comment]
@zaidSimajji Thanks for reporting this, can you please share which package version this is happening with?

**Comment by zaidSimajji** [comment]
@msach22 From my package.json:
"opentok-react-native": "^0.9.0",
 "react-native": "0.57.3",

**Comment by msach22** [comment]
@zaidSimajji Apologies for the delay on this, could you please confirm that you're seeing it with the latest release (v0.9.6)?

**Comment by zaidSimajji** [comment]
@msach22 Hi, I've tried updating to 0.9.6 but it seems to still be happening.

**Comment by ggoldens** [comment]
Confirmed, it's still happening Using the latest version of opentok-react-native and opentok SDK.

**Comment by ggoldens** [comment]
Hi @zaidSimajji could you please confirm if it still happening with v0.12.0?

**Comment by ggoldens** [comment]
This should be fixed in opentok-react-native >= 0.120.
