### ISSUE TITLE
Random crash on switch on and off video

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-react-native#199]
# Bug Report

Version : 
 - opentok-react-native 0.9.0
 - opentok ios 2.15.0 and 2.15.1

**Current behavior**
> Random crashes on iOS when remote user switch on and off his video stream

**Steps to reproduce**
> Connect two instance of opentok-react-native on ios and switch camera on and off for one repeatedly. The other should crash pretty fast (sometimes even on the first switch)

**Relevant logs and/or screenshots**
The code crashes randomly in prepareJSStreamEventData. The error indicates that the C memory associated to the OTStream can not be read.

The problem seems to be correlated to opentok-ios rather than opentok-react-native as replacing 2.15.X with 2.14.0 fixes this issue.

**Comment by msach22** [comment]
@mbouxin Thanks for reporting this. Are you seeing this with iOS to iOS applications or iOS to any other OpenTok platform?

**Comment by mbouxin** [comment]
@msach22 The app that crashes is always the iOS app but it crashes whatever the other opentok platform is (at least I just reproducted the bug with an android client and a web client)

The crashes are in prepareJSStreamEventData called by subscriberVideoEnabled and subscriberVideoDisabled delegates.

**Comment by msach22** [comment]
This is a duplicate issue: https://github.com/opentok/opentok-react-native/issues/190

It looks like it's an issue with the native SDKs and it has been filed internally. I will update the original issue as I have more details.
