### ISSUE TITLE
unable to wrap own views 

### ISSUE THREAD

**Issue by Necromant1k** [opentok/opentok-react-native#2]
Stuck with one problem.
So basically we want to wrap our components with `<OTSession>` like we do with `<View>`.
But, when we will do that - our components just disappear.

**Comment by msach22** [comment]
@Necromant1k can you show me a sample of the style you're applying so I can check this out on my end. Will test out your PR as well :)

**Comment by Necromant1k** [comment]
@msach22 probably i want just pass `flex: 1` to OTSession view.

`<OTSession>
   <View>
      <Text>Hello</Text>
   </View>
</OTSession>
`

So in this case ^ you unable to see `Hello` text. But when u will pass `flex` to your `OTSession` View u will be able. 

And also nice to have style property on container. My case very common, but sometimes we want to pass some styles to this container view

**Comment by msach22** [comment]
fixed with: https://github.com/opentok/opentok-react-native/pull/10
