### ISSUE TITLE
Random Session Stream Destroyed when call reconnect

### ISSUE THREAD

**Issue by pedro-cerdera** [opentok/opentok-react-native#201]
# Bug Report

Version: 
opentok-react-native 0.9.0

**Current behavior**
> Random Session Stream Destroyed when call reconnect.

**Steps to reproduce**
> During a call, disconnect and reconnect the Internet sometimes. 

**What is the current *bug* behavior?**
> During a call, if one device disconnect and reconnect quickly, the other device receive a Session Stream Destroyed and end the call.

**What is the expected *correct* behavior?**
> If the one device disconnect and reconnect, the call don't end.

**Comment by renanpupin** [comment]
@msach22 this issue is happening in android and iOS.

**Comment by renanpupin** [comment]
I am not sure if it is related to the issue, but both Session and Subscriber is mapping the same disconnect event in android.

<img width="1035" alt="captura de tela 2018-11-27 as 16 17 43" src="https://user-images.githubusercontent.com/8743530/49102493-1f41fa80-f260-11e8-9b1b-f705a35ea6ab.png">

**Comment by msach22** [comment]
@pedro-cerdera @renanpupin We have a reconnection bug that's been filed with the native team which is currently being tracked internally. I will update you as soon as we have more input.

**Comment by renanpupin** [comment]
@msach22 thanks for the reply.
Please let me not ASAP when this fix is going to be released.
We have this bug in production that are causing some troubles to our clients.
Feel free to ask if you need some other informations.

**Comment by renanpupin** [comment]
Any updates on this bug?

**Comment by msach22** [comment]
@renanpupin based on our conversation, this has been resolved with the latest patch of the OpenTok SDKs.
