### ISSUE TITLE
NullPointerException crash on Android

### ISSUE THREAD

**Issue by pedro-cerdera** [opentok/opentok-react-native#202]
# Bug Report

Version:
opentok-react-native 0.9.0

**Current behavior**
> Attempt to invoke virtual method 'void com.opentok.android.Publisher.destroy()' on a null object reference

**Steps to reproduce**
> During a call connection end the call.  

**Relevant logs and/or screenshots**
```
com.opentokreactnative.OTSessionManager$2 in run at line 326
android.os.Handler in handleCallback at line 836
android.os.Handler in dispatchMessage at line 103
android.os.Looper in loop at line 203
android.app.ActivityThread in main at line 6251
java.lang.reflect.Method in invoke
com.android.internal.os.ZygoteInit$MethodAndArgsCaller in run at line 1075
com.android.internal.os.ZygoteInit in main at line 936

```

**Comment by msach22** [comment]
The fix for this has been released with v0.9.4
