### ISSUE TITLE
Android crash - Error while updating property 'streamId' of a view managed by OTSubscriberViewManager

### ISSUE THREAD

**Issue by cmedinadeveloper** [opentok/opentok-react-native#203]
![crash1](https://user-images.githubusercontent.com/33674559/49664817-5c10ad00-fa29-11e8-938b-4a4a4efb25bf.jpeg)
Got this crash on Android devices after remounting the session component if the user lost his internet connection, this happens 85% of our calls, any way to prevent or fix this since the default reconnecting method is not working properly?

**Comment by msach22** [comment]
@cmedinadeveloper Could you replace
```
       mSubscribers.get(streamId).setStyle(BaseVideoRenderer.STYLE_VIDEO_SCALE,
                BaseVideoRenderer.STYLE_VIDEO_FILL);
```
 in `OTSubscriberLayout.java` with the following to see if prevents the crash?
```
        Subscriber mSubscriber = mSubscribers.get(streamId);
        if (mSubscriber != null) {
            mSubscriber.setStyle(BaseVideoRenderer.STYLE_VIDEO_SCALE,
                    BaseVideoRenderer.STYLE_VIDEO_FILL);
        }
```

**Comment by msach22** [comment]
@cmedinadeveloper Could you please let me know if the fix worked for you?

**Comment by msach22** [comment]
@cmedinadeveloper Did you get a chance to check this out?

**Comment by julien-meichelbeck** [comment]
@msach22 Yes, adding this condition fixes the issue. Is it possible to release the fix ? Thank you.

**Comment by msach22** [comment]
I believe that latest release (v0.9.7) has resolved this issue. I'm going to close this out, but please re-open if it still persists.
