### ISSUE TITLE
OT Undefined Error

### ISSUE THREAD

**Issue by ZakeryFyke** [opentok/opentok-react-native#204]
I have a very simple implementation as follows: 

        export default class VideoChatScreen extends React.Component{

        constructor(props){
            super(props);
            // I have real values here
            this.apiKey = '';
            this.sessionId = '';
            this.token = '';

        }

        render(){

            return(
                <View style={{ flex: 1, flexDirection: 'row' }}>
                    <OTSession apiKey={this.apiKey} sessionId={this.sessionId} token={this.token}>
                        <OTPublisher style={{ width: 100, height: 100 }}/>
                        <OTSubscriber style={{ width: 100, height: 100 }} />
                    </OTSession>
                    <Text>Please?</Text>
                </View>
            )
        };
    }

I load this screen on a button push. However, upon the screen loading, I'm given the error: TypeError: undefined is not an object (evaluating OT.setNativeEvents).

Digging around a bit, I believe this is caused by OT being undefined for some reason, but I can't figure out why?

**Comment by msach22** [comment]
@ZakeryFyke Have you linked the native modules? (`react-native link opentok-react-native`) Could you please share which platform (iOS/Android) this is happening for?

**Comment by ZakeryFyke** [comment]
@msach22 I have indeed run `react-native link opentok-react-native` at the top level of the project. 

This is currently happening for Android using expo to build to my device, I do not have the ability to run on iOS at this time.

**Comment by msach22** [comment]
@ZakeryFyke Ah, unfortunately, this library does not support Expo because it uses custom native modules.

**Comment by ZakeryFyke** [comment]
I rebuilt the project without using Expo, and that fixed the issue. 😄

**Comment by msach22** [comment]
Happy to hear 😄
