### ISSUE TITLE
How to get token data on streamCreated event? the event object doesn't include connection object (which holds the data), only connection id

### ISSUE THREAD

**Issue by malkaShtibel** [opentok/opentok-react-native#208]
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by msach22** [comment]
@malkaShtibel Thanks for pointing this out. I'm going to go ahead and create a feature request and close this issue because it's not using any of the issue templates.

#209
