### ISSUE TITLE
How to place a view on top of OTPublisher component?

### ISSUE THREAD

**Issue by codvlpr** [opentok/opentok-react-native#212]
I'm having a little difficulty while placing a view as on overlay on OTPublisher component. I have 4 control buttons in a view and I'm trying to place that view on top of OTPublisher.

This is the JSX:
`
<OTPublisher
          publishAudio={this.state.publisherIsAudible}
          publishVideo={this.state.publisherIsVisible}
          cameraPosition={this.state.publisherCameraPosition}
          style={styles.publisherWindow}/>
          <View style={styles.controlsContainer}>
            <TouchableOpacity style={styles.controls}>
              <Icon size={40} color="#eee"
              name={Platform.OS === "android" ? "md-mic" : "ios-mic"} />
            </TouchableOpacity>

            <TouchableOpacity style={styles.controls}>
              <Icon size={40} color="#eee"
              name={Platform.OS === "android" ? "md-eye-off" : "ios-eye-off"} />
            </TouchableOpacity>
            
            <TouchableOpacity style={styles.controls}>
              <Icon size={40} color="#eee"
              name={Platform.OS === "android" ? "md-reverse-camera" : "ios-reverse-camera"} />
            </TouchableOpacity>

            <TouchableOpacity style={styles.controls}>
              <Icon size={40} color="#D32F2F"
              name={Platform.OS === "android" ? "md-call" : "ios-call"} />
            </TouchableOpacity>
          </View>
`

and this is the styles i'm applying
`const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Config.PRIMARY_COLOR
  },
  publisherWindow: { 
    height: '80%', 
    width: '100%'
  },
  controlsContainer: {
    flexDirection: "row",
    alignItems: "center",
    position: 'absolute',
    bottom: 0, 
    left: 0, 
    right: 50, 
    zIndex: 1000, 
    alignItems: 'center', 
    justifyContent: 'center'
  },
  controls: {
    marginLeft: 60
  }
});`
![screenshot from 2018-12-18 00-10-46](https://user-images.githubusercontent.com/7852344/50109433-9e23c500-0259-11e9-82ca-2e70bbf06c43.jpg)

`

**Comment by msach22** [comment]
@codvlpr We've removed the code from Android where the publisher was always on top. We plan on adding releasing an update where you can specify if you'd like the publisher or subscriber on top. For now, you can use `v0.9.8` and you should be able to add views on top of `OTPublisher`.
