### ISSUE TITLE
Android SDK 2.15.2 Build Issue

### ISSUE THREAD

**Issue by hero70312** [opentok/opentok-react-native#213]
I had upgraded to v0.9.2.
There is no problem in building iOS app.
But when I tried to build android app. There was a problem show in my Android Studio.

Shown as follows
> Error:(23, 0) Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.  

React Native Version: "0.53.0"

**Comment by msach22** [comment]
@hero70312 I just created a fresh project with React Native v0.53.0 and OpenTok React Native v0.9.2 and I was able to build without any issues.

Is that error that your sharing related to this library or just your Android project in general?

**Comment by msach22** [comment]
@hero70312 Any update on this?

**Comment by hero70312** [comment]
@msach22 After I updated my build.gradle version, I solve this problem. 
Thank you!

**Comment by msach22** [comment]
Thanks for updating us! I'm going to go ahead and close this issue.
