### ISSUE TITLE
Control each subscriber separately and not only the list of subscribers

### ISSUE THREAD

**Issue by malkaShtibel** [opentok/opentok-react-native#215]
# Feature Request

**Description**
 I need to get control on each subscriber component separately (subscriberView), so I can decide when to add each subscriber component to the screen, what style each subscriber will get etc.

**Proposal**

**Links / references**

**Comment by msach22** [comment]
This seems to be a duplicate of: https://github.com/opentok/opentok-react-native/issues/193
