### ISSUE TITLE
Multiple sessions in parallel don't work

### ISSUE THREAD

**Issue by ArtemSerga** [opentok/opentok-react-native#218]
# Bug Report

**Current behavior**
When you have connection to multiple sessions:
1. Signal will be sent to all sessions
2. Unmounting one of the `<OTSession />` disconnects all sessions

**Steps to reproduce**
> Mount the first `<OTSession sessionId="xxx" ... />` session
> Mount the second `<OTSession sessionId="yyy" ... />` session (and don't unmount previous)
> Send a signal to the second session (you will get it in both)
> Unmount the second one (you will be disconnected from both)

**What is the expected *correct* behavior?**
> Multiple sessions support with isolation from each other

**Relevant logs and/or screenshots**
Extra example with similar issue
http://blogs.quovantis.com/session-handling-with-opentok/
http://prntscr.com/lyb9ty

**Comment by msach22** [comment]
@ArtemSerga Yes, this is a known limitation of this library. As of now, this library does not support multiple sessions, but we can go ahead and add it.

**Comment by ArtemSerga** [comment]
Thanks @msach22 for an answer.
Currently it's a huge limitation for a successful usage of Opentok at the company I'm working.

There are two cases:
1. I need one common session for receiving a new message from any chatroom and one session per chatroom. The difficulties is that I need a common permanent session since app launch and I don't unmount it. I will try to switch between the sessions, but a current component-based (`<OTSession>`) architecture makes it unconfortable.
2. I need a videochat with one person and messaging with others at the same time. Currently it's not posible without multiple sessions support.

I will hope it's possible to implement multiple sessions.
Thanks you one more time.

**Comment by msach22** [comment]
@ArtemSerga Apologies for the delay on this - I don't have a timeline on this update yet, but I'd love to chat with you to see if I can help you out while we work on this. Could you please reach out at manik@tokbox.com

**Comment by msach22** [comment]
@ArtemSerga I just wanted to update you that I've started to work on this, but this is going to be part of a big refactor on the native code so I can't promise a release date. I will update you as I progress.

**Comment by ASerga** [comment]
It's great. Thanks a lot, @msach22
We almost release iOS and Android app with Opentok inside and I will be the first to try multiple sessions support.

**Comment by ASerga** [comment]
@msach22, is there any updates?

**Comment by ggoldens** [comment]
hello @ASerga, we're working on it. I'll post an update soon.

**Comment by ggoldens** [comment]
@ASerga FYI We're still working on this. We have a good progress, but still trying to resolve an issue related to having more than one publisher.

**Comment by ggoldens** [comment]
@ASerga would you like to test the PR and provide some feedback? I'll add you as a reviewer.

**Comment by ggoldens** [comment]
Closing this one since, it's solved in the PR #311
