### ISSUE TITLE
[BUG] com.opentokreactnative.utils.EventUtils.prepareJSSessionMap

### ISSUE THREAD

**Issue by renanpupin** [opentok/opentok-react-native#219]
# Bug Report

**Current behavior**
> EventUtils.java line 52 
> com.opentokreactnative.utils.EventUtils.prepareJSSessionMap

**Steps to reproduce**
> I do not know how to reproduce, because it was catch at our bug tracker.

**Relevant logs and/or screenshots**
<img width="1236" alt="captura de tela 2018-12-22 as 18 45 18" src="https://user-images.githubusercontent.com/8743530/50378457-c759a200-0619-11e9-9a45-cfd62461aec8.png">

**Comment by msach22** [comment]
@renanpupin Could you please share the following information?

- Native SDK version
- OTRN version

**Comment by renanpupin** [comment]
- Native SDK version 2.15.2
- OTRN version 0.9.4

**Comment by msach22** [comment]
Thanks @renanpupin. Do you know how often this is happening? It would be really helpful if you can provide info on when this is happening (i.e when the session is created, or the specific event that's being triggered that causes this).

**Comment by renanpupin** [comment]
@msach22 looking at the logs, it seems that the exception is happening while/after the session is destroyed.

**Comment by msach22** [comment]
@renanpupin I'm currently working on a refactor for both iOS and Android which will tackle this issue and support multiple sessions. Please let me know if you have any questions.

**Comment by msach22** [comment]
@renanpupin I believe that latest release (v0.9.7) has resolved this issue. I'm going to close this out, but please re-open if it still persists.
