### ISSUE TITLE
App crash after receiving the signal from API

### ISSUE THREAD

**Issue by ArtemSerga** [opentok/opentok-react-native#220]
# Bug Report

If a signal has been sent via API, but not a client, app will get a fatal error (both iOS, Android) while trying to get information about empty connection.

**Comment by ArtemSerga** [comment]
Great answer at `1 Jan 00:26`! 
Happy New Year, colleague! 
Thanks you for working hard to make Opentok better.

**Comment by msach22** [comment]
@ArtemSerga The fix has been released with v0.9.5. Thanks for all your help!

**Comment by ASerga** [comment]
It works! Thanks a lot @msach22 and Opentok iOS SDK team.

One moment - doesn't forget to update Pods
```
 platform :ios, '9.0'

    target '<YourProjectName>' do

      # Pods for <YourProject>
        pod 'OpenTok', '2.15.3'
    end

**Comment by msach22** [comment]
@ArtemSerga Thanks! I also updated the readme so it reflects the change in using the iOS SDK 😄
