### ISSUE TITLE
[iOS] Can't build iOS app after upgrading from opentok-react-native 0.8.4 to 0.9.4 (unresolved identifier "EventUtils" and "Utils")

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#223]
# Bug Report

**Current behavior**
After upgrading opentok-react-native from 0.8.4 to 0.9.4 (and making sure that OpenTok SDK is updated to 2.15.2), I am unable to build the app in Xcode 10. Have also investigated #190 as reference, but still was unable to successfully build iOS app. (Android builds properly and works fine.) 

Screenshot:

![screen shot 2019-01-14 at 5 19 22 pm](https://user-images.githubusercontent.com/12490625/51151874-4e68f700-1821-11e9-99a9-9613aa7aa483.png)

**Steps to reproduce**
- Start with working React Native 0.56.0 app with opentok-react-native 0.8.4
- Update the node_package of opentok-react-native to 0.9.4
- Update the OpenTok pod to 2.15.2
- Re-run `react-native link`, reinstall node packages, clear Xcode build caches, and restart Xcode to be safe
- Attempt to build the app (using legacy build system in Xcode 10
- Observe build failure

**Comment by msach22** [comment]
@sunweiyang Hmm, I'm not sure why this is happening for you. I just followed your steps and was able to upgrade without any issues. Could you please verify that the `OpenTokReactNative.xcodeproj` files has a `Utils` folder after you upgrade? Something like this:
![](https://duaw26jehqd4r.cloudfront.net/items/0e2r462x053h0n3z1v2f/Image%202019-01-24%20at%2010.51.21%20AM.png)

**Comment by msach22** [comment]
@sunweiyang Did you have a chance to look at my previous comment?

**Comment by msach22** [comment]
@sunweiyang I'm going to go ahead and close this issue, please feel free to re-open if you're still seeing this.

**Comment by sunweiyang** [comment]
I finally figured it out; posting what I did here so that others in the future who encounter this same issue can have an easier time.

For some reason, `opentok-react-native`'s npm module that I downloaded using `yarn install` had a different `ios/OpenTokReactNative.xcodeproj/project.pbxproj` file from that of this official repo. Yes @msach22, it unfortunately excluded the Utils directory.

What I had to do was manually replace that `project.pbxproj` file with the one from this repo. Furthermore, I had to do these additional steps:
1. Perform `react-native unlink opentok-react-native` and re-link again with `react-native link opentok-react-native`
2. Go to my Xcode project's `Build Phases >> Link Binary With Libraries`, remove `libOpenTokReactNative.a`, and then re-add it again

I was then finally able to build my app.

**Comment by sunweiyang** [comment]
In the end, it was the result of a peculiarity in my specific RN app. The vast majority of developers upgrading this module world never encounter this issue.

**Comment by msach22** [comment]
Thanks for sharing your update @sunweiyang. Is it possible that `yarn add` was checking a local cached package and pulling from there?

**Comment by sunweiyang** [comment]
@msach22 For reasons specific to my app, I had to create a custom yarn cache, which is highly unusual for most developers. In general, clearing the cache would completely resolve this issue (and most developers will never encounter this).
