### ISSUE TITLE
Changes to `publishAudio` & `publishVideo` property is not working

### ISSUE THREAD

**Issue by karthinalliyappan** [opentok/opentok-react-native#224]
Here's what I'm doing - I'm taking in a prop called **publishAudio** and **publishVideo**,  I'm using it to build a property object and I feed it into the OTPublisher component. Something like this -

```
 <OTPublisher 
            properties={{
              publishAudio: this.state.audio,  // set the state of the audio of the stream
              publishVideo: this.state.video,  // set the state of the video of the stream
              showControls: true,                 // Hide provided controls to make custom control bar
              videoTrack: this.state.videoTrack,
            }}
            eventHandlers={this.publisherEventHandlers}
            style={{ width: deviceHeight/6.67, height: deviceHeight/5.13}} 
  />
```

When this prop changes in the parent component, the changes propagate down but it does not seem to take any effect on the publisher.

Version:
` "react-native": "0.51.1"`
`"opentok-react-native": "0.6.3",`

**Comment by msach22** [comment]
@karthinalliyappan I'm going to go ahead and close this issue, please feel free to reopen if the issue still persist with the latest release.
