### ISSUE TITLE
How to get events call back like client connected , disconnected and so on?

### ISSUE THREAD

**Issue by tarunmehta-quovantis** [opentok/opentok-react-native#228]
I found a doc of OTSession for having various callback . I applied all these callback but receiving all the callback at once.

Is there any example with the callbacks ? Would help me see how I can apply in my code

**Comment by msach22** [comment]
Answered here: https://stackoverflow.com/questions/54455675/in-opentok-react-native-how-to-get-various-events-information-like-client-connec/54521392#54521392
