### ISSUE TITLE
Screen Sharing for both iOS and Android

### ISSUE THREAD

**Issue by msach22** [opentok/opentok-react-native#23]

**Comment by msach22** [comment]
Currently in Progress

**Comment by msach22** [comment]
added in `0.6.0`

**Comment by Igorpollo** [comment]
Hi...Where can I find some docs or example of screen sharing?
Thanks

**Comment by EfteazTE** [comment]
its not working properly. after few seconds screen sharing stops and publisher app not responding.

**Comment by msach22** [comment]
@EfteazTE The team is working on an improved screensharing capturer for iOS so we'll add it to this React Native library once it's complete. cc: @bsrao

**Comment by EfteazTE** [comment]
@msach22 i am getting this issue in android. when sharing screen after few seconds when i scroll screen publisher app not publishing and app not responding at all. please reply me as soon as possible.

**Comment by EfteazTE** [comment]
@msach22 can you please help me out as i am stuck on this problem and i can't move forward with screen sharing on android.

**Comment by smkamranqadri** [comment]
can we share screen from other app in iOS?
