### ISSUE TITLE
Controlling audio volume

### ISSUE THREAD

**Issue by evillemez** [opentok/opentok-react-native#231]
# Feature Request

Add more ability to directly control parameters related to volume.

**Description**

We have many reports from users of our app that volume is too low in calls.  We can anecdotally tell the difference in testing just by comparing our app to other apps like Facetime or Hangouts, where the received audio is noticeably louder.

We don't know what the underlying issue is, but think that the library might need to expose more underlying functionality of the native SDKs around volume controls.

**Proposal**

The JS docs describe `subscriber.setAudioVolume` - but there doesn't seem to be a way to set this on `OTSubscriber`.  It's also not clear this is actually a solution to the problem, though it could be a factor.

**Links / references**

https://tokbox.com/developer/guides/audio-video/js/

**Comment by msach22** [comment]
@evillemez Thanks for filing this issue. We don't have any API for mobile that allows you to set the volume for the subscriber. You would simply have to use the built in iOS controls (i.e the physical buttons).

**Comment by evillemez** [comment]
Closing in favor of #249, which better describes the actual issue we're experiencing.

**Comment by znelson32** [comment]
@msach22 Is there a technical reason that subscriber volume level isn't supported on mobile but it's supported in JS? We're working on a high profile app and wish we had the ability to set individual volume levels for the participants. As it stands, all we can do is mute them via an audio unsubscribe but it's not sufficient really.
