### ISSUE TITLE
iOS build failure with cocoapods 1.6.0

### ISSUE THREAD

**Issue by sanddy-man** [opentok/opentok-react-native#235]
# Bug Report

**Current behavior**
> iOS build failed

**Steps to reproduce**
> following all install guide with cocoapods 1.6.0

**What is the current *bug* behavior?**
>  'OpenTok/OpenTok.h' file not found 

**What is the expected *correct* behavior?**
> build success

When I downgrade cocoapods to 1.5.3 build was successful.
Any ideas? How to use this library with 1.6.0
Xcode: 10.1
React Native: 0.57.8

**Comment by michaeldouglas** [comment]
+1

**Comment by msach22** [comment]
Thanks for filing this issue - I'm also able to reproduce this using Cocoapods 1.6.0. I'll investigate further and update you folks on my findings.

**Comment by smakosh** [comment]
@sanddy-man you will have to use a previous cocapods version to generate the pre-compiled opentok headers, save it somewhere then you can use your new cocapods version and simply drag & drop the opentok folder in `pods/headers/public` & `pods/headers/private`

**Comment by EscoCreeks** [comment]
@smakosh I tried your solution, it worked! But the build failed later with a fancy 
`ld: symbol(s) not found for architecture ...` (I tried with a simulator and with a real device).
Do you have any suggestion on this one?

**Comment by smakosh** [comment]
Alright you should edit your podfile, can you first share it here?

**Comment by EscoCreeks** [comment]
```
# frozen_string_literal: true

platform :ios, '9.0'

target 'MyProject' do
  pod 'Crashlytics'
  pod 'Fabric'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
```

**Comment by EscoCreeks** [comment]
So I [added an empty swift file ](https://stackoverflow.com/a/50495316/10780147) and it worked like a charm.

**Comment by smakosh** [comment]
Nice!

**Comment by MoxeyGroup** [comment]
I am also getting same issue and this is a blocker for me. As per my knowledge, I will not be able to release on app on App Store if it is not built using latest XCode. I am new to OpenTok and I have got this code from previous developer, so please help if you have a solution.

**Comment by msach22** [comment]
@MoxeyGroup Is it possible for you to use a different version of Cocoapods to compile the headers and then copy them over like so? https://github.com/opentok/opentok-react-native/issues/235#issuecomment-469845027

I know it's not an optimal solution, but unfortunately, I don't have the bandwidth the explore the fix right now. I am open to PRs and suggestions 😄

**Comment by MoxeyGroup** [comment]
@msach22 - I would have loved to provide a PR but I am new to OpenTok so do not know much. 

I am able to run my app using (Old Cocoapods+Xcode 9+iOS 11) but old cocoapods version does not work with Xcode 10 and iOS 12, so I cannot build it using iOS 12 SDK. This is concerning as:

"**Starting March 2019, all new apps and app updates for iPhone, including universal apps, will need to be built with the iOS 12 SDK and support iPhone XS Max.**"

I will try by compiling headers and will keep you posted of result.

**Comment by msach22** [comment]
Thanks for the feedback - the fix has been deployed with `opentok-react-native v0.10.2`
