### ISSUE TITLE
I need how to change voice audio 

### ISSUE THREAD

**Issue by win05178** [opentok/opentok-react-native#238]
Hello,I have problem about audio.
I need change audio output form speaker to earpiece but i don't know how to do.please help me.

Thank you.

Ps.
Sorry if my english language not good.

**Comment by askhat** [comment]
Was not able to find according methods in neither of `.m` files. I assume it's supposed to regulate volume with physical buttons on device.

**Comment by msach22** [comment]
This seems to be a repeat of: https://github.com/opentok/opentok-react-native/issues/173

Please let me know if it's not the same.
