### ISSUE TITLE
 Attempt to invoke virtual method 'void com.opentok.android.v3.Session.resume()' on a null object reference

### ISSUE THREAD

**Issue by urvashikharecha** [opentok/opentok-react-native#248]
I am getting this error!!!

 Attempt to invoke virtual method 'void com.opentok.android.v3.Session.resume()' on a null object reference

**Comment by palmas** [comment]
I'm also getting this error. In both 2.15.3 and  in the latest 2.16.5 version.
OpenTok team, why do you close this issue when it is not fixed? 

It is a very critical issue and we are thinking to stop useing openTok and choose some other framewiork because of this...
