### ISSUE TITLE
In-app OpenTok subscribed audio becomes too quiet after an incoming phone call

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#249]
# Bug Report

**Current behavior**
OpenTok behavior is normal until an incoming phone call. After answering the phone call during an OpenTok session, OpenTok subscribed audio volume is drastically reduced (almost inaudible). OpenTok audio volume will continue to be extremely quiet until the app is closed and relaunched. This issue is seen on both iOS and Android.

**Steps to reproduce**
1. Start an OpenTok session in an app on the phone (either iOS or Android), subscribing to audio and video (or just audio). Observe audio behaving normally.
2. During the OpenTok session, have someone call the phone from step 1 using another phone (normal phone call).
3. The user of the phone from step 1 should answer the call, and then hang up. (After the call, that phone should then be back in the original OpenTok app.)
4. Observe that audio volume has reduced drastically.
5. Optional final step: without restarting the app, start another OpenTok session. Observe that subscribed audio volume is still reduced.

**What is the current *bug* behavior?**
OpenTok subscriber audio volume drops during a phone call and doesn't recover until app relaunch. 

**What is the expected *correct* behavior?**
OpenTok subscriber audio recovers back up to pre-call volume after each phone call.

**Comment by evillemez** [comment]
@sunweiyang @msach22 We have this issue, or a similar one, as well.  The trigger for the behavior on our side might be different though, we haven't been able to determine consistent reproduction steps.

I know we've had the same symptom in cases that don't involve receiving an incoming call while using our app.  If your method reproduces the symptom consistently though, solving this case might address the issue we're seeing as well.

@sunweiyang When you have the reduced volume situation, if you use the volume buttons to try and increase the volume during the OpenTok session, does it visually look like the device is at full volume but it's still very quiet?

**Comment by sunweiyang** [comment]
@evillemez Yes, confirming that after cranking the system volume up to its highest setting after a phone call, the audio still remains quiet.

**Comment by evillemez** [comment]
@sunweiyang Interesting... it sounds like we have the same symptoms exactly.  We'll keep investigating on our end and see if we can come up with reproduction steps that are different... maybe that will help uncover the root cause.

@msach22 Do you have any ideas on what we should be looking into, or do you think this might be an issue at the native level?

**Comment by evillemez** [comment]
@sunweiyang Another question - are you using any other sound-related libraries?  We're trying to investigate if there may be some conflict with other sound libraries we're using.  At the moment we're using these two for certain things:

* https://github.com/zmxv/react-native-sound
* https://github.com/react-native-webrtc/react-native-incall-manager

I know that's not directly related to the issue of receiving an incoming phone call during the OT session, but I'm trying to get a sense of what all the factors could come in to play affecting the audio, and if we share any other similarities in our setup.

**Comment by sunweiyang** [comment]
We are only using react-native-audio-toolkit to briefly play a chime elsewhere in the app (definitely not using it during the OpenTok session), and react-native-system-setting to directly change the phone's system volume:
* https://github.com/react-native-community/react-native-audio-toolkit
* https://github.com/c19354837/react-native-system-setting

**Comment by msach22** [comment]
@sunweiyang @evillemez Thanks for filing this issue. I'm doing some internal digging for this and will update you soon on the findings :)

**Comment by evillemez** [comment]
@msach22 Did you discover anything related to this?

We still have low audio volume issues in our app (in-call volume is always much lower than in other apps, and user cannot increase it), and haven't been able to determine the root cause.

**Comment by hugoh59** [comment]
Any update on this issue? Thank you.

**Comment by scitbiz** [comment]
My workaround is using [AppState](https://facebook.github.io/react-native/docs/appstate) to unmount the session if the state is **_inactive_** or **_background_** and remount when the state is **_active_**

**Comment by sunweiyang** [comment]
@scitbiz Thanks for the suggestion. Unfortunately, our app needs to still persist the session when normally backgrounded by the user (audio is still subscribed and published).

**Comment by znelson32** [comment]
I have a similar problem when playing background audio during an OpenTok session using the iOS API. The first time it plays the audio level is good. But on a second play the audio level drops very low. I think it has something to do with the behavior of the AVAudioSession and source ducking but I can't narrow it down.

**Comment by PitGuy** [comment]
I have the same problem. It was because OpenTok speak by phoneSpeaker, but incomming call swith it to earpice. I fixed it by manual swithing after call finished: audioManager.SpeakerphoneOn = true;
