### ISSUE TITLE
Class RTCCVPixelBuffer is implemented in both... error in iOS 12.2

### ISSUE THREAD

**Issue by cagataydagnik** [opentok/opentok-react-native#260]
I have an issue with dependencies included in Class RTCCVPixelBuffer.

I am using OpenTok SDK in my iOS App. My iOS version is 12.2 . When I try to run the app, I get a console full of error like :

Class RTCCVPixelBuffer is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x1d9f0bf98) and /var/containers/Bundle/Application/2152DE07-01CA-4739-9F7C-80DF4E9378A8/parrotize.app/parrotize (0x10128c248). One of the two will be used. Which one is undefined.

Swift class extensions and categories on Swift classes are not allowed to have +load methods

**Comment by akandaurov** [comment]
Looks like it is needed to update to the latest react-native version
https://github.com/facebook/react-native/pull/24155

**Comment by msach22** [comment]
@cagataydagnik Could you please share which version of the OpenTok iOS SDK you're using? Is this something that you're seeing when using this library?

**Comment by mbouxin** [comment]
@msach22 I face the same issue when I try to migrate from xcode 10.1 to xcode 10.2 (it works in xcode 10.1 but fail in 10.2).

My setting is:
RN 0.59.2
Opentok 2.15.3
opentok-react-native 0.9.7

I will try to upgrade and tell here if it solves the issue

**Comment by mbouxin** [comment]
I tested with upgraded version (RN 0.59.5 and opentok-react-native 0.10.1) and it works

**Comment by msach22** [comment]
Thanks @mbouxin - It seems like an issue with React Native that's resolved by upgrading to v0.59.3. Is that safe to assume?

**Comment by msach22** [comment]
Closing this issue because it looks like it was resolved with the updated RN version. Please re-open if this still persists.
