### ISSUE TITLE
Subscribe to a specific stream

### ISSUE THREAD

**Issue by msach22** [opentok/opentok-react-native#268]
# Feature Request

**Description**
> (Include problem, use cases, benefits, and/or goals)
As of now, all streams are automatically subscribed to when they are created. We want to be able to subscribe to specific streams, not all of them.
**Proposal**

**Links / references**

**Comment by enricop89** [comment]
Should be possible with https://github.com/opentok/opentok-react-native/blob/main/docs/OTSubscriber.md#custom-rendering-of-streams
