### ISSUE TITLE
couldn't find key to in dynamic object 

### ISSUE THREAD

**Issue by pompy** [opentok/opentok-react-native#272]
Error (RED SCREEN):
couldn't find key to in dynamic object  

How:
When I run the default BasicVideoChat 
ref url
https://github.com/opentok/opentok-react-native-samples/tree/master/BasicVideoChat
Passing parameters to  OTSession

Note:
I noticed the session does start and is also recorded in the inspector. 
If i ignore the red screen(error) the video does shows up. 
Its just that on app load it shows the red screen.

Environment:

  compileSdkVersion 28
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "com.basicvideochat"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

react-native-cli: 2.0.1
Gradle:  classpath 'com.android.tools.build:gradle:3.2.1' 

![S90420-204749](https://user-images.githubusercontent.com/1394843/56459756-2f609080-634d-11e9-9a66-f05d98a0e88d.jpg)

**Comment by msach22** [comment]
@pompy This looks like a problem with the samples - could you please file the issue on the samples repo. 

Since this is the library repo, we only track the issues for the library here.
