### ISSUE TITLE
OTSessionManager.initSession got 2 arguments, expected 3 after upgrade to 0.10.x

### ISSUE THREAD

**Issue by fpenovi** [opentok/opentok-react-native#273]
# Bug Report

**Current behavior**
After the upgrade from v0.9.8 to v0.10.1 library crashes on both Android and iOS.

**Steps to reproduce**
+ Install library, link, etc.
+ Declare this snippet of code inside a render function:
```
  render() {
    return (
      <View>
        <OTSession
          sessionId={sessionId}
          apiKey={apiKey}
          token={token}>
          <OTSubscriber style={{ width: 100, height: 100 }} />
          <OTPublisher style={{ width: 200, height: 200 }} />
        </OTSession>
      </View>
    );
  }
```

**What is the current *bug* behavior?**
App crashes

**What is the expected *correct* behavior?**
Render OTSession without crashing

**Relevant logs and/or screenshots**
![image](https://user-images.githubusercontent.com/19509087/56519795-5370cd00-6519-11e9-802c-22c381233b6f.png)

**Comment by msach22** [comment]
@fpenovi Thanks for filing the issue - I'm not sure why this is happening because the JS layer is sending three arguments https://github.com/opentok/opentok-react-native/blob/master/src/OTSession.js#L52

Can you please confirm that the OTRN JS node module has been updated?

**Comment by fpenovi** [comment]
@msach22 Thanks for your quick response and for this great library!
I can confirm that OTRN node modules files are actually up to date with the latest version. I also tried deleting `./node_modules` folder and reinstalling but to no avail.

**Comment by msach22** [comment]
@fpenovi Of course. Thanks for verifying. Could you please close your metro bundler and start it again? I'm thinking it could be some sort of cache. Please also clean your native build and build again and let me know what you see.

**Comment by fpenovi** [comment]
@msach22 Okay this took me longer than I expected, nothing would work until I finally deleted every trace of RN cache. 

For anyone having RN cache issues, running the following in your root project folder should clear everything
```
$ watchman watch-del-all && rm package-lock.json && rm -rf node_modules && rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/haste-map-* && npm install
```
**Check the contents of $TMPDIR before running it though**

**Comment by msach22** [comment]
Thanks for sharing @fpenovi. I've come across this before and I've noticed it was the cache. I'm glad to hear that your issue has been resolved.
