### ISSUE TITLE
disconnected event not firing

### ISSUE THREAD

**Issue by pompy** [opentok/opentok-react-native#275]
disconnected event not firing when subscriber force disconnect (in subscriberEventHandler ). While connected and videonetworkstats event are firing.  I am disconnecting by using back button of android button or developer/took/playground creating a video stream and then disconnecting by clicking unpublish stream

As below
 subscriberEventHandler = {
  StreamDisconnected: (event) => {
      },
  videoDisabled: (event) => {
      },
  videoEnabled: (event) => {
      },
  videoDataReceived: (event) => {
      },
  videoNetworkStats: (event) => {
    //THIS IS FIRING
      },
  connected: (event) => {
    //THIS IS FIRING
      },  
      disconnected: (event) => {
    //THIS IS NOT FIRING
      },
  error: (error) => {
    //console.log(`There was an error with the subscriber: ${error}`);
  },
};

Ref:
 <OTSubscriber style={{width:300, height:300}}   properties={this.subscriberProperties}
              eventHandlers={this.subscriberEventHandler} />

Tested in android 6 & 8

Library
    "opentok-react-native": "^0.9.7",
    "react": "16.8.3",
    "react-native": "0.59.3",

   ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }

    dependencies :
        classpath 'com.android.tools.build:gradle:3.3.1'

**Comment by pompy** [comment]
Please close it -- I removed other events but strangely this issue got solved..?

  Is there any way to get count of subscribers from tokbox api directly ?
Also anyway to know if subscriber object is empty or not  ?

**Comment by msach22** [comment]
@pompy I'm glad to hear that it's working. Did you update the library version?

We don't have a list of # of subscribers, but you can keep a count of streams using the `streamCreated` and `streamDestroyed` events. Could you please explain what you mean by subscriber object is empty or not?
