### ISSUE TITLE
How to enable auto focus for publisher video ?

### ISSUE THREAD

**Issue by Nitheeshsalian** [opentok/opentok-react-native#277]
Camera does not auto focus or manual focus FRONT / BACK

**Comment by msach22** [comment]
@Nitheeshsalian Thanks for filing an issue - we would need some more information for this issue.

Could you please share which version of the library you're using? Which platform is this effecting? Is this happening on a specific device?

**Comment by nitheeshskiploop** [comment]
@msach22 Here is the detailed information [https://stackoverflow.com/questions/56035926/tokbox-video-video-is-pixelated-with-no-clarity](url)

**Comment by nitheeshskiploop** [comment]
I am evaluating tokbox for react-native for a support application which has video streaming.

The basic video streaming is working fine, however the clarity on the video is very unclear. It appears that autofocus is not working.

 I am able to reproduce the same issue on the example application provided 
@ [https://github.com/opentok/opentok-react-native-samples/tree/master/BasicVideoChat](url)

The only change I have done is to add the app settings and back the back camera as default. The same code is available [ https://github.com/nitheeshskiploop/opentokBasicVideo](url)

I have tested taking the video using WhatsApp and Agora and the video quality is good.

Below is my package.json configuration
`
{
  "name": "BasicVideoChat",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "opentok-react-native": "^0.10.1",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-device-info": "^1.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
The device information is
`
{
    "app_name": "BasicVideoChat",
    "build_number": 1,
    "bundle_id": "com.basicvideochat",
    "carrier": "AIRTEL",
    "device_country": "US",
    "device_id": "sdm660",
    "device_locale": "en-US",
    "font_scale": 0.8500000238418579,
    "freedisk_storage": 9232261120,
    "manufacturer": "Xiaomi",
    "max_memory": 268435456,
    "model": "Mi A2",
    "readable_version": "1.0.1",
    "serial_number": "unknown",
    "system_name": "Android",
    "system_version": "9",
    "timezone": "Asia/Kolkata",
    "storage_size": 3121049600,
    "total_memory": 3921362944,
    "user_agent": "Mozilla/5.0 (Linux; Android 9; Mi A2 Build/PKQ1.180904.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.136 Mobile Safari/537.36",
    "is24_hour": false,
    "is_emulator": false,
    "device_uid": "cc60682ee481ec0f"
}
`

**Comment by msach22** [comment]
Thanks @Nitheeshsalian. For Android, you can add the following:
```
<uses-feature android:name="android.hardware.camera.autofocus" android:required="true" />
```

to your app and it should make auto focus a requirement. This is because some devices don't support autofocus. 

If this still continues, please update me.

**Comment by nitheeshskiploop** [comment]
@msach22 I have tried this one problem still exist.

**Comment by ivorcho** [comment]
I had the same issue and setting the `OTSession` option `isCamera2Capable` to `true` seems to enable the autofocus feature.

**Comment by nitheeshskiploop** [comment]
@ivorcho i have tried this still no luck

**Comment by nitheeshskiploop** [comment]
@msach22 problem still exist.

**Comment by nitheeshskiploop** [comment]
@msach22 any word on this issue ?

**Comment by moffly** [comment]
Any update on this? Is Tokbox iOS SDK possible to auto focus or manual focus? Thanks.

**Comment by JayTokBox** [comment]
Hi @nitheeshskiploop 

Sorry for replying late. I am not sure what the issue is here, our code or the device in question. One way to figure that out will be to try an android app and check it (https://github.com/opentok/opentok-android-sdk-samples/tree/master/Custom-Video-Driver)
In the android custom video driver code we can check if auto-focus is enabled or not. If not, we can even add code to change the camera mode to do it. 

Doing customization like that it via React , currently, is not possible. 

One further question, is video clarity always out of focus or based on camera distance?  Is it possible to try a different phone of the same model?

I am assuming network congestion and bandwidth is not messing with the video quality. 

Thanks

**Comment by csguys** [comment]
```
SessionBuilder.sessionOptions(new Session.SessionOptions() {
                            @Override
                            public boolean isCamera2Capable() {
                                return super.isCamera2Capable();
                            }
                        })
```

works for me

**Comment by Abhishek9634** [comment]
in iOS how we can achieve??

**Comment by TalhaAhsan** [comment]
Is this still an issue with newer versions of the library?
