### ISSUE TITLE
Video is pixelated 

### ISSUE THREAD

**Issue by sharathchandramg** [opentok/opentok-react-native#281]
I am evaluating tokbox for react-native for a support application which has video streaming.

The basic video streaming is working fine, however the clarity on the video is very unclear. It appears that autofocus is not working.

I am able to reproduce the same issue on the example application provided @ https://github.com/opentok/opentok-react-native-samples/tree/master/BasicVideoChat

The only change I have done is to add the app settings and back the back camera as default. The same code is available @ https://github.com/nitheeshskiploop/opentokBasicVideo

I have tested taking the video on same device using **WhatsApp** and **Agora** and the video quality is good.

Below is my package.json configuration

```

{
  "name": "BasicVideoChat",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "opentok-react-native": "^0.10.1",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-device-info": "^1.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

The device information is 

```
{
	"app_name": "BasicVideoChat",
	"build_number": 1,
	"bundle_id": "com.basicvideochat",
	"carrier": "AIRTEL",
	"device_country": "US",
	"device_id": "sdm660",
	"device_locale": "en-US",
	"font_scale": 0.8500000238418579,
	"freedisk_storage": 9232261120,
	"manufacturer": "Xiaomi",
	"max_memory": 268435456,
	"model": "Mi A2",
	"readable_version": "1.0.1",
	"serial_number": "unknown",
	"system_name": "Android",
	"system_version": "9",
	"timezone": "Asia/Kolkata",
	"storage_size": 3121049600,
	"total_memory": 3921362944,
	"user_agent": "Mozilla/5.0 (Linux; Android 9; Mi A2 Build/PKQ1.180904.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.136 Mobile Safari/537.36",
	"is24_hour": false,
	"is_emulator": false,
	"device_uid": "cc60682ee481ec0f"
}
```

The images from all the applications are shown below 👍  

**Image from tokbox**

![video_tokbox](https://user-images.githubusercontent.com/11989798/57359119-7eebec80-7194-11e9-95dc-61fa3912cffb.png)

**Image from agora**

![video_agora](https://user-images.githubusercontent.com/11989798/57359084-6aa7ef80-7194-11e9-95da-454002650342.png)

**Image from WhatsApp**

![video_whatsapp](https://user-images.githubusercontent.com/11989798/57359128-8a3f1800-7194-11e9-8d03-041464e2d8e2.png)

**Comment by ggoldens** [comment]
@sharathchandramg Were you able to fix this? 
Could you please try with the Opentok demo app for Android and see if you can reproduce the same issue? thanks!

**Comment by ggoldens** [comment]
@sharathchandramg please follow the issue #277 that seems to be about this same problem.
