### ISSUE TITLE
got this error Type 'OTSubscriberVideoEventReason' has no member 'codecNotSupported' while building in ios xcode is 10.2 and opentok 2.16 mentioned in pod

### ISSUE THREAD

**Issue by reactdevrocks** [opentok/opentok-react-native#283]
```static func convertOTSubscriberVideoEventReasonToString(_ reason: OTSubscriberVideoEventReason) -> String {
        switch reason {
        case OTSubscriberVideoEventReason.publisherPropertyChanged:
            return "PublisherPropertyChanged"
        case OTSubscriberVideoEventReason.subscriberPropertyChanged:
            return "SubscriberPropertyChanged"
        case OTSubscriberVideoEventReason.qualityChanged:
            return "QualityChanged"
        case OTSubscriberVideoEventReason.codecNotSupported: // error in this line
            return "CodecNotSupported"
        }
    }```

**Comment by msach22** [comment]
@reactdevrocks Thanks for filing the issue. Could you please confirm using the Podfile.lock that you're using the native 2.16.0 SDK?

**Comment by pa-garcia** [comment]
I have experienced this issue too. But my Xcode version is 10.1  and the 'OpenTok' pod version is '2.15.3'

**Comment by reactdevrocks** [comment]
@msach22 - OpenTok (2.16.0). Confirmed

**Comment by msach22** [comment]
Hmm, I'm not seeing this issue. I'm using XCode 10.2.1 and I used the following sample app:
https://github.com/opentok/opentok-react-native-samples/tree/master/BasicVideoChat

This new video reason was introduced in the 2.16.0 SDK. Are you able to reproduce this using the sample app?

**Comment by reactdevrocks** [comment]
@msach22 i have commented and given default case in node_modules and then error has gone.

**Comment by Auggysg** [comment]
@reactdevrocks I'm experiencing the same issue as you, can you please explain what you mean by "commented and given default case in node_modules"?

**Comment by smakosh** [comment]
Having the same issue

**Comment by smakosh** [comment]
I confirm that it's fixed on the latest SDK
