### ISSUE TITLE
Minimum Android SDK version support

### ISSUE THREAD

**Issue by siliconavengers** [opentok/opentok-react-native#285]
Hello,

I'm planning to use OpenTok for my project, but my device requires Android version must be 5.1. 

I have checked the [build.gradle](https://github.com/opentok/opentok-react-native/blob/master/android/build.gradle) file.

```
def _ext = rootProject.ext
def _reactNativeVersion = _ext.has('reactNative') ? _ext.reactNative : '+'
def _compileSdkVersion = _ext.has('compileSdkVersion') ? _ext.compileSdkVersion : 23
def _buildToolsVersion = _ext.has('buildToolsVersion') ? _ext.buildToolsVersion : '23.0.1'
def _minSdkVersion = _ext.has('minSdkVersion') ? _ext.minSdkVersion : 16
def _targetSdkVersion = _ext.has('targetSdkVersion') ? _ext.targetSdkVersion : 23

```

It looks the library doesn't support Android SDK version below 23. Could you guys let me know more information about it? Am I wrong?

**Comment by msach22** [comment]
@siliconavengers The library does supports a minimum of API Level 16. Android 5.1 is API Level 22 so this should be supported. You can check out some basic samples here to run a standalone app and build for Android 5.1: 
https://github.com/opentok/opentok-react-native-samples

**Comment by manish-dalal** [comment]
@msach22 on API level 23 I always get a black screen on OTSubscriber view in the sample app
[https://github.com/opentok/opentok-react-native-samples/tree/master/BasicVideoChat](https://github.com/opentok/opentok-react-native-samples/tree/master/BasicVideoChat)
