### ISSUE TITLE
Custom renderer for children in OTSession

### ISSUE THREAD

**Issue by Pelsin** [opentok/opentok-react-native#287]
# Feature Request

**Description**
We are trying to add a transition when pressing on one of the subscribers to focus on that person, basically making that subscriber take up the entire screen.
- Currently no way of adding press handlers on the subscribers.
- No way of adding custom styling per subscriber

**Proposal**
Add more control of the way children for OTSession are being rendered, suggestion would be to do it through render prop convention. Would help with custom styling per child and we could wrap any handlers we want.

**Links / references**
https://reactjs.org/docs/render-props.html

**Comment by og2t** [comment]
This is now solved with PR #306 :)

**Comment by enricop89** [comment]
Version `0.11.2` published on NPM  🎉
