### ISSUE TITLE
handling session destroy

### ISSUE THREAD

**Issue by joelpiccoli** [opentok/opentok-react-native#291]
Hello everyone, I'm facing an issue within our app and would like the help from anyone that can help...

There's anyway to destroy a session by an action from the user? (i.e taping a button "close sessions")

**Comment by msach22** [comment]
@joelpiccoli You should be able to destroy the session by unmounting the `OTSession` component. For more docs, please see: https://github.com/opentok/opentok-react-native/blob/master/docs/OTSession.md
