### ISSUE TITLE
Crash when using iOS 13 Beta

### ISSUE THREAD

**Issue by Playfrog4u** [opentok/opentok-react-native#308]
I know iOS 13 is currently still in beta but wanted to bring this up.

I've also updated the project to react-native 0.60
Currently running iOS 13 Beta 3

Even crashed on an older react-native build that currently works on iOS 12

When starting the video chat it immediately crashes..

Below is the last few lines in Xcode 11 beta.
Doesn't really give good direction on what is causing the error..

Thanks!

Please update the following components: OTPublisher

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
2019-07-05 10:21:31.391190-0500[784:140876] Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: OTPublisher

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
2019-07-05 10:21:31.411 [info][tid:com.facebook.react.JavaScript] 1
2019-07-05 10:21:31.411181-0500[784:140876] 1
2019-07-05 10:21:31.434694-0500 ][784:140563] Metal GPU Frame Capture Enabled
2019-07-05 10:21:31.440304-0500[784:140563] Metal API Validation Enabled
(lldb)

**Comment by Playfrog4u** [comment]
Even with Metal API Validation disabled in the Scheme, it crashes at Metal GPU Frame Capture Enabled

**Comment by lynmije** [comment]
is this issue been fixed? I have also encountered this in Xcode 11 beta 6

**Comment by teodorostlund** [comment]
Same here. iOS 13 will be released very soon.
We're not using React Native, but this bug happens for us as well.

**Comment by enricop89** [comment]
HIi, we're going to release a fix for iOS 13 within two days

**Comment by jaredteladoc** [comment]
> Same here. iOS 13 will be released very soon.
> We're not using React Native, but this bug happens for us as well.

They aren't allowed to release any code until the Gold Master xCode is released and you wouldn't be able to submit that update anyway.   Thanks @enricop89 for the update and patiently waiting!

**Comment by teodorostlund** [comment]
> > Same here. iOS 13 will be released very soon.
> > We're not using React Native, but this bug happens for us as well.
> 
> They aren't allowed to release any code until the Gold Master xCode is released and you wouldn't be able to submit that update anyway. Thanks @enricop89 for the update and patiently waiting!

All productions apps using the current OpenTok version will crash on the day of iOS 13 release (which might be today). Too bad for the users who don’t have auto update enabled. They should’ve fixed this crash bug months ago  when iOS 13 beta first came out. Twilio works great on iOS 13, which we are migrating to.

**Comment by msach22** [comment]
Hi folks, happy to share that we just released iOS 2.16.3 with iOS 13 support. Thanks for your patience.
