### ISSUE TITLE
Android androidZOrder and androidOnTop does not cover all possible cases

### ISSUE THREAD

**Issue by akandaurov** [opentok/opentok-react-native#312]
You have added 2 settings to override zIndex on on Android. Everything worked fine for me before without those overrides - I could show publisher over subscriber and the opposite.
Now with default settings the subscriber is somewhere behind.
There should be a way to do not force any zOrder and work like it was before that feature, e.g. 'unspecified' state

**Comment by tomek29k** [comment]
Same here. It feels like the entire publisher/subscribers/RN-views priority needs to be fixed/rewritten for Android, it doesn't seem to follow the react-native draw order.

**Comment by ggoldens** [comment]
@akandaurov @tomek29k what are the version of OpenTok SDK that you are using, and which is the configuration of `androidOnTop` and `androidZOrder` ?

**Comment by akandaurov** [comment]
On Android 7+ those overrides are not needed and everything works fine if just enclose subscriber or publisher in a usual react-native view.
On older android it's better to set useTextureViews to true and everything works like a charm, but need to switch to older SDK (2.14.3) because in 2.15.* TextureViews are incorrectly resized, which is fixed in 2.16.1, but 2.16.* hangs on session disconnect.

**Comment by tomek29k** [comment]
@ggoldens Currently, for Android we are using @akandaurov's suggestion (SDK @ 2.14.3) that is working for us (thanks Andrey!), it seem to fix [crash on session disconnect](https://github.com/opentok/opentok-react-native/issues/294) and view drawing order.

For iOS we are using [our own fork](https://github.com/29ki/opentok-react-native/tree/patches) while waiting for the next SDK.

**Comment by t4ngth00** [comment]
@akandaurov I can see that using TextureViews will make Android devices hot quicker and drain more battery than keep using the default GLSurfaceView.

**Comment by TalhaAhsan** [comment]
Closing this issue as @tomek29k mentioned using useTextureViews resolves this issue here:
https://github.com/opentok/opentok-react-native/pull/259#issuecomment-537904984
As mentioned by @t4ngth00 as well.
