### ISSUE TITLE
Audiolevel 0 on ios

### ISSUE THREAD

**Issue by Kosal19901015** [opentok/opentok-react-native#313]
I am building video chat app.
Android has no issue, then ios has issue.
when i enter the chatroom on ios, at first, i can hear the voice.
out of room and enter again, then no voice.
By the way, restart the app, i can hear the voice.
This issue is only from ios, Android works well.
If someone had experience on this issue, please support me.
Thanks

**Comment by enricop89** [comment]
Duplicate #286
