### ISSUE TITLE
Hide subscriber view 

### ISSUE THREAD

**Issue by HenriqueMata** [opentok/opentok-react-native#315]
I want to hide subscriber view but using `height: 0`, `height: 0.1` or `display: 'none'` video does not disappear. Subscriber still on layout: 
![view](https://user-images.githubusercontent.com/35509741/61719768-e77e4a80-ad3b-11e9-8833-e45a18898294.png)

And when I do a conditional to hide in render app crash:
![error](https://user-images.githubusercontent.com/35509741/61719851-109edb00-ad3c-11e9-9b06-ebda5f1a65de.png)

**Comment by ggoldens** [comment]
Thanks @HenriqueMata for reporting. We'll take a look.

**Comment by tomek29k** [comment]
I suppose this is on Android @HenriqueMata?

We've had the same issue – impossible to hide the subscriber. I've had an idea to wrap the `OTSubscriber` with a `View` and set its style `height: 0; overflow: 'hidden'`, but not sure if this would work either.

**Comment by HenriqueMata** [comment]
Yes, it is. I didn't tried on iOS yet, but i supposed it works.

Im wrapping with a View, but not using these props, I will try using these and reply here

**Comment by HenriqueMata** [comment]
@tomek29k I tried use `height: 0`, `overflow: 'hidden'` but didnt work

**Comment by akandaurov** [comment]
I cover the Subscriber in one more view like this and it works fine, but I saw errors like described in this this thread in Crashlytics log.
<View style={{ justifyContent: 'center', ...(hidden ? { width: 0, height: 0 } : { flex: 1 }) }}>

**Comment by HenriqueMata** [comment]
Hiding and show multiple times sometime the bug in first image happens.

**Comment by ggoldens** [comment]
@HenriqueMata sorry for the late reply. 
I've been testing this. If you follow the recommendation from @akandaurov you should be able to hide the subscriber. Although in my case I was able to do it with display: 'none' in the View that wraps the subscriber.
Could you show how to get the error in your screenshot?

**Comment by HenriqueMata** [comment]
This is how I got the error:

`const subscriberView = show ? (
    <View
      style={[
        style,
        {
          backgroundColor: 'black',
          justifyContent: 'center'
        }
      ]}
    >
      <OTSubscriberView
        style={{ width: '100%', height: '80%' }}
        streamId={stream.streamId}
      />
    </View>
  ) : null;
  return subscriberView;`

**This text refers to the first image.**
I could not understand why sometimes set the style `height: 0`,` height: 0.1` or `display: 'none'`, the subscriber hides, but after a while doing this several times, View appears above another and the subscriber that is to hide remains in the layout but paused.

**This text refers to the second image.**
If the subscriber is already on the screen works fine, but when you hide and come back with the subscriber the error occurs. I think this is how @akandaurov recommend it, am I right? This error happens only on Android, I have tested on iOS and it works.

**Comment by ggoldens** [comment]
thanks @HenriqueMata. I just approved a PR that seems to fix this issue. I'll let you know when it's released.

**Comment by HenriqueMata** [comment]
Thanks @ggoldens

**Comment by ggoldens** [comment]
Opentok React Native 0.12.1 was released so this issue should be fixed now!
