### ISSUE TITLE
Network test

### ISSUE THREAD

**Issue by julisalis** [opentok/opentok-react-native#316]
Hi, is there something like [opentok-network-test-js](https://github.com/opentok/opentok-network-test-js) for testing connectivity and quality in react-native?

**Comment by enricop89** [comment]
@julisalis Hi Juli this one is an example for ReactNative: https://github.com/nexmo-saleseng/opentok-react-native-samples/tree/feature.network-test-sample/OTNetworkTest

**Comment by julisalis** [comment]
Thanks @enricop89! 
Yeah, I saw that example earlier, but I need the same results that opentok-network-test-js returns, specially the mos and error reasons.

**Comment by ggoldens** [comment]
@enricop89 @julisalis I think we can close this issue since it's not directly related with this package. You can open a new issue requesting a new feature in https://github.com/nexmo-saleseng/opentok-react-native-samples OR feel free to make a PR and we will review it. 
Thanks!!
