### ISSUE TITLE
undefined:session:sessionDidConnect 

### ISSUE THREAD

**Issue by ArtyCake** [opentok/opentok-react-native#329]
# Bug Report

**Current behavior**
The error appears after successful connection. 

Session parameters set on componentDidMount.

after the screen was displayed,  UI was shown for a second and then the error appears (attached below). As it's shown in Tokbox inspector session was connected (attached screenshot)

As I can see in OTSessionManager.swift it emits next event
`self.emitEvent("\(session.sessionId):\(EventUtils.sessionPreface)sessionDidConnect", data: sessionInfo);
`
so the sessionId at this moment became undefined somehow

**Relevant logs and/or screenshots**
![Simulator Screen Shot - iPhone X - 2019-08-16 at 11 38 42](https://user-images.githubusercontent.com/5197162/63155387-1a55ee80-c01b-11e9-8efe-dbc781c69e51.png)
<img width="551" alt="Screen Shot 2019-08-16 at 11 39 02 AM" src="https://user-images.githubusercontent.com/5197162/63155393-1c1fb200-c01b-11e9-9d43-4ba81397c4e7.png">
<img width="598" alt="Screen Shot 2019-08-16 at 11 47 59 AM" src="https://user-images.githubusercontent.com/5197162/63155673-b54ec880-c01b-11e9-83d4-2cfb46aa217d.png">

**Comment by tomek29k** [comment]
@ArtyCake: Can you check if you're wrapping `<OTSubscriber>` component in a `<View>`? It seems the `sessionId` prop is not getting through.

**Comment by ArtyCake** [comment]
Interesting
Thank's for advice 
I've removed `<View>` wrapper from `<OTPublisher>` and it's working 
But what if I need to stylize the call screen and add more views, including wrapper around `<OTPublisher>` and `<OTSubscriber>`?

**Comment by tomek29k** [comment]
You can use render props to [custom render streams](https://github.com/opentok/opentok-react-native/blob/master/docs/OTSubscriber.md#custom-rendering-of-streams).

However, you might experience weird [z-order bugs on Android](https://github.com/opentok/opentok-react-native/issues/312) with #315 and #324 – please report them if you do 🙏🏻

**Comment by ArtyCake** [comment]
Thank's a lot 
I will

**Comment by ggoldens** [comment]
Thanks @ArtyCake for reporting this. We'll review this.

**Comment by ggoldens** [comment]
This is now fixed in v0.12.1. Closing this issue.
