### ISSUE TITLE
Stop listening to a stream?

### ISSUE THREAD

**Issue by blind675** [opentok/opentok-react-native#338]
Is there a way for a OTSubscriber to stop listening to a stream. My session creates streams at a different random time and I would like the client to always be subscribed to the last stream. What I get now are all the streams for the session.

![Simulator Screen Shot - iPhone X - 2019-08-30 at 12 59 45](https://user-images.githubusercontent.com/2725079/64012464-71cd8180-cb26-11e9-9513-2f5e165f2a90.png)

**Comment by th317erd** [comment]
This may not be what you actually want, and you might need to figure out how to sort the `streams` array. But this might work for you:

```
renderSubscribers() {
  return (
    <OTSubscriber
      properties={subscriberProperties}
      eventHandlers={subscriberEventHandlers}
      streamProperties={streamProperties}
    >
      {(subscribers) => {
        return subscribers.map((streamId, index) => {
          if (index < (subscribers.length - 1))
            return null;
            
          return this.renderSubscriber(streamId);
        });
      }};
    </OTSubscriber>
  );
}
```

**Comment by enricop89** [comment]
@blind675 did you try to follow @th317erd advice? I think it's a good idea. Let me if it worked!

**Comment by msach22** [comment]
Thanks for the recommendation @th317erd - this should work!
