### ISSUE TITLE
do we have any solution for pixelated video and auto focus

### ISSUE THREAD

**Issue by Sach-SPF** [opentok/opentok-react-native#346]
@msach22 

I'm having serious trouble with blurry and autofocus issues on Subscriber end especially with moving video. Do let me know for any solution

Thanks
Sachin

**Comment by Sach-SPF** [comment]
I know this works in Android but I'm looking solution for iOS?

**Comment by abdulajet** [comment]
Thanks for the issue, can you check out the latest version of the library, and if your issue has not been resolved please reopen/create a new issue.
