### ISSUE TITLE
Black screen camera for ios 

### ISSUE THREAD

**Issue by lynmije** [opentok/opentok-react-native#348]
It only shows a black screen and the app crashed. 

![videoconference](https://user-images.githubusercontent.com/47166455/64404832-c8e7cf00-d0af-11e9-9e9f-9e188d8a8f16.jpg)

---
react-native/issues/new?template=bug.md)

**Comment by enricop89** [comment]
Hi @lynmije what are we looking for here? Could you please describe better the issue and steps to reproduce?

**Comment by lynmije** [comment]
@enricop89 Opentok publisher camera for ios showing a black screen and the app froze. i have already enable the camera permission and audio

**Comment by lynmije** [comment]
<img width="775" alt="error" src="https://user-images.githubusercontent.com/47166455/64508713-a99bac80-d310-11e9-8f36-8cdd04a8e8ae.png">

**Comment by enricop89** [comment]
@lynmije are you still facing this issue? I'll close for now, feel free to reopen if needed.
