### ISSUE TITLE
`OTSessionManager.getSessionInfo was called with 1 arguments but expects 2 arguments

### ISSUE THREAD

**Issue by hugoh59** [opentok/opentok-react-native#354]
`OTSessionManager.getSessionInfo was called with 1 arguments but expects 2 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.`

Error shows up after upgrading opentok-react-native to the latest released version. I've upgraded both the pod and the module to their respective latest version but this error still shows up when trying to create a session.

**Comment by enricop89** [comment]
@hugoh59 Could you please confirm you are using opentok-react-native: `0.12.1`, ios `2.16.3` and android `2.15.3`?
