### ISSUE TITLE
Unable to resolve module `./contexts/OTContext`

### ISSUE THREAD

**Issue by hugoh59** [opentok/opentok-react-native#355]
Unable to resolve module `./contexts/OTContext`

Getting this error after following all the installations tep using RN 0.60.3

**Comment by enricop89** [comment]
Are you using `opentok-react-native: 0.12.1`?

**Comment by ziarno** [comment]
same here; using opentok-react-native: 0.12.1

**Comment by ziarno** [comment]
restarting the bundler worked for me... :P

**Comment by enricop89** [comment]
I close this one. @hugoh59 please check the bundler and restart it as @ziarno suggested
