### ISSUE TITLE
Certain users, upon starting a session, are experiencing numerous NetInfo connectionChange events and sessionReconnecting/sessionReconnected events

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#362]
Some of our users' logs revealed the following happening multiple times, in quick succession (roughly 20 of these per minute), whenever an OpenTok session is first instantiated:
* NetInfo connectionChange events
* OTSession eventHandler sessionReconnecting events
* OTSession eventHandler sessionReconnected events

Our app uses opentok-react-native 0.12.1 with Android OpenTok SDK 2.16.2 and RN 0.61.2.

In case it is helpful, two of our users confirmed with us that it's happening consistently for both of them with Samsung Galaxy S10+ devices running Android Pie (SDK 28). We couldn't find any reasons for NetInfo to detect connectionChange events or OpenTok to require reconnection; our analytics show that they didn't switch internet sources.

**Comment by sunweiyang** [comment]
Some relevant background: our  app shows information to the user and kicks off important processes whenever NetInfo connectionChange events occur, so this significantly impacts our app.

**Comment by ggoldens** [comment]
Hi @sunweiyang can you please share logs and the session ID that we can inspect? This might be related to network conditions.

**Comment by sunweiyang** [comment]
@ggoldens Below are a few OpenTok tokens for sessions where this happened. Our first guess was that it was network conditions, but since we started recording analytics of network changes, we only see this strange behavior when OpenTok inits are attempted. Thank you for looking into this.
```
T1==cGFydG5lcl9pZD00NTgyODk0MiZzaWc9MTJmZTE3ODZhM2U1YjYwNGM2YWYyMGM0MmY1MDViMjZhZWVkYmE1MjpzZXNzaW9uX2lkPTFfTVg0ME5UZ3lPRGswTW41LU1UVTNNVFF6TlRRd01EazROMzVGVGxKR1ZrWmpOR1pzVlhwUGQwRTFjbTR6WTNaRWRDdC1mZyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PWxlYXJuZXImcm9sZT1wdWJsaXNoZXImbm9uY2U9NDY4NTAwJmNvbm5lY3Rpb25fZGF0YT1za2FsZV9zZXNzaW9uX2lkJTNEMzMyNjQlMkNlbWFpbCUzRGZpbGxpZS5naWJzb24lNDBjZWxsb25seS5jb20lMkNyb2xlJTNEbGVhcm5lciZjcmVhdGVfdGltZT0xNTcxNDM1NDAxJmV4cGlyZV90aW1lPTE1NzE1MjE4MDE=
```
```
T1==cGFydG5lcl9pZD00NTgyODk0MiZzaWc9ZWIxODk2MTUwYjZiZWE5NjFiZmViNjgwNTU3OTg0MDE5YTUxZWE1ZDpzZXNzaW9uX2lkPTFfTVg0ME5UZ3lPRGswTW41LU1UVTNNVFF6TlRBMk5UZ3lOSDVLTDI5S0swOHhhMUJTYUZKaWFIUjNLelJ5YUdwNU1DOS1mZyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PWxlYXJuZXImcm9sZT1wdWJsaXNoZXImbm9uY2U9NDQ2MDk5JmNvbm5lY3Rpb25fZGF0YT1za2FsZV9zZXNzaW9uX2lkJTNEMzMyNjMlMkNlbWFpbCUzRGZpbGxpZS5naWJzb24lNDBjZWxsb25seS5jb20lMkNyb2xlJTNEbGVhcm5lciZjcmVhdGVfdGltZT0xNTcxNDM1MDY1JmV4cGlyZV90aW1lPTE1NzE1MjE0NjU=
```
```
T1==cGFydG5lcl9pZD00NTgyODk0MiZzaWc9MjcwYTc0MjFjZmEwMzQzMmVmZmE5OWNkZDUzNjQ4NDk2MWQxZTdhNDpjb25uZWN0aW9uX2RhdGE9c2thbGVfc2Vzc2lvbl9pZCUzRDMzMjU2JTJDZW1haWwlM0RmaWxsaWUuZ2lic29uJTQwY2VsbG9ubHkuY29tJTJDcm9sZSUzRGxlYXJuZXImcm9sZT1wdWJsaXNoZXImZXhwaXJlX3RpbWU9MTU3MTI0MDEyMyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PWxlYXJuZXImc2Vzc2lvbl9pZD0yX01YNDBOVGd5T0RrME1uNS1NVFUzTVRFMU16Y3lNelV3T1g0MGRXNXRVVk5XYUV4c1pYVmhhMmxQYlVVM01VNWlTbEItZmcmY3JlYXRlX3RpbWU9MTU3MTE1MzcyMyZub25jZT0zMjE1Ng==
```
```
T1==cGFydG5lcl9pZD00NTgyODk0MiZzaWc9MDYxZDMzNzE5N2ZlOWVjOWJkYWE0ZDc2MzViNWFhYTFiYmE5MWRjYzpjb25uZWN0aW9uX2RhdGE9c2thbGVfc2Vzc2lvbl9pZCUzRDMzMjU1JTJDZW1haWwlM0RmaWxsaWUuZ2lic29uJTQwY2VsbG9ubHkuY29tJTJDcm9sZSUzRGxlYXJuZXImcm9sZT1wdWJsaXNoZXImZXhwaXJlX3RpbWU9MTU3MTIzOTg5MyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PWxlYXJuZXImc2Vzc2lvbl9pZD0yX01YNDBOVGd5T0RrME1uNS1NVFUzTVRFMU16UTVNell5TUg1cFV6VnlNRGRVZEhKMEszRklhbkZMVFVGUlNuWjRVRUYtZmcmY3JlYXRlX3RpbWU9MTU3MTE1MzQ5MyZub25jZT02ODU4MTU=
```
```
T1==cGFydG5lcl9pZD00NTgyODk0MiZzaWc9ODZiZTNjMTVkN2MxYjVlZTVlYzY5NDhlOWFkYTc1MWM3MzNhNzkyODpleHBpcmVfdGltZT0xNTcwOTA1MzI4JmNyZWF0ZV90aW1lPTE1NzA4MTg5MjgmaW5pdGlhbF9sYXlvdXRfY2xhc3NfbGlzdD1sZWFybmVyJnJvbGU9cHVibGlzaGVyJnNlc3Npb25faWQ9Ml9NWDQwTlRneU9EazBNbjUtTVRVM01EZ3hPRGt5T0RJME4zNWhSemxsYWpWVGNsRjFiR0ZrVGpaU1JXSm9VVzk1VEVWLWZnJm5vbmNlPTk4MTQ0OSZjb25uZWN0aW9uX2RhdGE9c2thbGVfc2Vzc2lvbl9pZCUzRDMzMjUxJTJDZW1haWwlM0RmaWxsaWUuZ2lic29uJTQwY2VsbG9ubHkuY29tJTJDcm9sZSUzRGxlYXJuZXI=
```

**Comment by enricop89** [comment]
@sunweiyang we need sessionId, not tokens, sorry :) session reconnect events are usually triggered when there is a network change (from 4g to Wi-Fi for example). Is it the case?

**Comment by sunweiyang** [comment]
This was a long time ago, so unfortunately the logs were lost. It wasn't accompanied by network changes. I'll report back if we see this issue appear again.
