### ISSUE TITLE
1004 Connection failure error

### ISSUE THREAD

**Issue by podvipodvert** [opentok/opentok-react-native#373]
After updating my project to react-native version 0.61.5, I receive an error in opentok inspector 1004 Connection failure. Issue not upper in opentok-react-native-samples (it has react-native version 0.59.9)
I've written to support (Ticket #1230769) they just spend a week of my time by checking all my credentials then redirect me in here. 
If you create a new project with RN version 0.61.5 you will get this error. Please help

**Comment by ggoldens** [comment]
Hi @podvipodvert. 
I have tested in both ios and android using react-native 0.61.5 and I'm able to connect, publish, subscribe, etc.
This error is basically that the token could be expired. Have you tried with a new token?
In order to help you better, can you please provide more information: Logs, credentials if possible, and package.json just to see what are the version of your deps.



Thanks.

**Comment by podvipodvert** [comment]
My tokens generated on node js side (opentok 2.9.1) then I receive token on front end side. When I set this token on your sample ( RN version  0.59.9) there is no issue. But on new project issue upper. What credentials you need from me

**Comment by ggoldens** [comment]
Sorry for the confusion, I meant your opentok credentials.

Please note that for Android and RN 0.61.5 you would need to migrate to AndroidX. See this link for more info: https://developer.android.com/jetpack/androidx/migrate
You need also to install jetifier: https://stackoverflow.com/questions/56717351/react-native-migrate-to-androidx
In the case of iOS you don't need further updates.
Could you please share the info I requested above? mainly logs, App.js and package.json.
Thanks.

**Comment by podvipodvert** [comment]
issue upper in iOS too. I don't understand what is "mainly logs". 

  "dependencies": {
    "@react-native-community/async-storage": "^1.6.3",
    "@react-native-community/netinfo": "^4.6.1",
    "card-validator": "^6.2.0",
    "libphonenumber-js": "^1.7.28",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "opentok-react-native": "^0.12.2",
    "payment": "^2.3.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-action-button": "^2.8.5",
    "react-native-action-sheet": "^2.2.0",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-axios": "^0.17.1",
    "react-native-callkeep": "^3.0.8",
    "react-native-camera-roll-picker": "^2.0.0",
    "react-native-country-picker-modal": "^1.9.8",
    "react-native-date-picker": "^2.7.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^5.3.1",
    "react-native-gesture-handler": "^1.5.1",
    "react-native-gifted-chat": "^0.12.0-beta-0",
    "react-native-image-crop-picker": "^0.26.1",
    "react-native-image-picker": "^1.1.0",
    "react-native-incall-manager": "^3.2.6",
    "react-native-keep-awake": "^4.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^1.3.1",
    "react-native-netinfo": "^1.1.0",
    "react-native-onesignal": "^3.5.0",
    "react-native-picker": "^4.3.7",
    "react-native-pin-code": "^0.5.3",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-reanimated": "^1.4.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^9.13.3",
    "react-native-vector-icons": "^6.6.0",
    "react-native-voip-push-notification": "^1.1.5",
    "react-native-wheel-picker-android": "^2.0.5",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-redux-helpers": "^4.0.1",
    "react-navigation-stack": "^1.10.3",
    "react-redux": "^7.1.3",
    "recompose": "^0.30.0",
    "redux": "^4.0.4",
    "redux-actions": "^2.6.5",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.3.0",
    "uuid": "^3.3.3"
  },

what for you need App.js file? there is only navigation set up in it. There is code from call screen

`import React, {Component} from 'react';
import {
  View,
  TouchableOpacity,
  Text,
  Alert,
  ActivityIndicator,
  Image,
} from 'react-native';
import InCallManager from 'react-native-incall-manager';
// import RNCallKit from 'react-native-callkit';

import {OTSession, OTPublisher, OTSubscriber, OT} from 'opentok-react-native';
import KeepAwake from 'react-native-keep-awake';

import {connect} from 'react-redux';
import {
  visitScreen,
  connectToCall,
  changeValue,
  terminateCall,
} from '../../../store/actions';
import {deviceWidth, deviceHeight} from '../../../styles/variables';

import CommonStyles from '../../../styles/CommonStyles';
import images from '../../../assets/images';
import styles from './styles';
import {showAlert} from '../../../utils/helpers';
import SocketService from '../../../services/socketService';
import OfflineNotice from '../../../components/OfflineNotice';

class Session extends Component {
  state = {
    showStream: true,
    isAlert: false,
    streamProperties: {},
    publisherProperties: {
      publishAudio: true,
      cameraPosition: 'front',
    },
    streamConnected: false,
  };

  constructor(props) {
    super(props);

    InCallManager.stopRingtone();

    this.sessionEventHandlers = {
      streamCreated: event => {
        // console.log('event', event);
        const streamProperties = {
          ...this.state.streamProperties,
          [event.streamId]: {
            subscribeToAudio: true,
            subscribeToVideo: true,
          },
        };
        this.setState({streamProperties, showStream: true});
      },
      error: error => {
        // console.log(`There was an error with the SESSION: ${error}`);
      },
    };

    this.subscriberEventHandlers = {
      error: error => {
        // console.log(`There was an error with the subscriber: ${error}`);
      },
      connected: event => {
        this.setState({streamConnected: true});
      },
      videoDisabled: event => {
        // console.log('subscriber stream videoDisabled!', event);
      },
    };

    this.publisherEventHandlers = {
      error: error => {
        // console.log(`There was an error with the publisher: ${error}`);
      },
      streamCreated: event => {
        // console.log('Publisher stream created!', event);
        const streamProperties = {
          ...this.state.streamProperties,
          [event.streamId]: {
            subscribeToAudio: true,
            subscribeToVideo: true,
          },
        };
        this.setState({streamProperties, showStream: true});
      },
    };
  }

  componentDidMount() {
    InCallManager.stopRingtone();
    SocketService.socket.on('user_end_call', this.onCallEnd);
  }

  componentWillReceiveProps(np) {
    if (np.callEnded && !this.props.callEnded) {
      this.leaveSession();
      this.props.changeValue('callEnded', false);
    }
  }

  componentWillUnmount(): void {
    SocketService.socket.removeListener('user_end_call', this.onCallEnd);
  }

  onCallEnd = () => {
    const {viewingAppointment} = this.props;
    if (this.props.currentUser.type === 'doctor' && !this.state.isAlert) {
      this.setState(() => ({isAlert: true}));
      showAlert(
        'Call ended',
        `${viewingAppointment.patientName || 'User'} has ended call`,
      );
    }
    this.leaveSession();
  };

  leaveSession = () => {
    this.setState({showStream: false}, () => {
      OT.disconnectSession(this.props.sessionId, () => {});
      // navigate away
      if (this.props.currentUser.type === 'doctor') {
        this.props.visitScreen('AppointmentsScreen');
      } else {
        this.props.visitScreen('MainServiceScreen');
      }
    });

    // disconnect from opentok session
  };

  switchCamera = () => {
    this.setState(({publisherProperties}) => ({
      publisherProperties: {
        ...publisherProperties,
        cameraPosition:
          publisherProperties.cameraPosition === 'front' ? 'back' : 'front',
      },
    }));
  };

  selfBoxStyle = {
    position: 'absolute',
    top: 30,
    left: 20,
    width: 120,
    height: 164,
    zIndex: 200,
    // borderBottomRightRadius: 10,
    // backgroundColor: 'rgb(17,61,98)',
  };

  otherBoxStyle = {
    height: deviceHeight,
    width: deviceWidth,
    position: 'absolute',
  };

  rejectCall = () => {
    const {streamConnected} = this.state;
    const {
      currentUser,
      patientId,
      doctorId,
      callUuid,
      terminateCall,
      roomName,
      token,
    } = this.props;
    const oppositeId = currentUser.type === 'doctor' ? patientId : doctorId;

    SocketService.socket.emit('user_end_call', {oppositeId});
    SocketService.socket.removeListener('user_end_call', this.onCallEnd);
    if (callUuid) {
      // RNCallKit.endCall(callUuid);
    }
    if (!streamConnected) {
      terminateCall(currentUser.id, patientId, roomName, token);
    }
    this.leaveSession();
  };

  render() {
    const {showStream} = this.state;

    return (
      <View style={{flex: 1, justifyContent: 'center'}}>
        <OfflineNotice />
        <View style={{flex: 1}}>
          <View style={styles.header} />
          {showStream ? (
            <OTSession
              apiKey="46013052"
              sessionId={this.props.sessionId}
              token={this.props.callToken}
              eventHandlers={this.sessionEventHandlers}>
              <OTPublisher
                properties={this.state.publisherProperties}
                eventHandlers={this.publisherEventHandlers}
                style={this.selfBoxStyle}
              />
              <OTSubscriber
                streamProperties={this.state.streamProperties}
                eventHandlers={this.subscriberEventHandlers}
                style={this.otherBoxStyle}
              />
            </OTSession>
          ) : (
            <ActivityIndicator
              style={CommonStyles.activityIndicator}
              size="large"
              color="#45b9c2"
            />
          )}
        </View>
        <View style={styles.buttonsContainer}>
          <TouchableOpacity style={styles.reject} onPress={this.rejectCall}>
            <Image source={images.phone} />
          </TouchableOpacity>
          <TouchableOpacity style={styles.approve} onPress={this.switchCamera}>
            <Image source={images.switchCamera} />
          </TouchableOpacity>
        </View>
        <KeepAwake />
      </View>
    );
  }
}
`

**Comment by podvipodvert** [comment]
And yes I have migration in my project to AndroidX.

**Comment by podvipodvert** [comment]
the problem was because my opentok account was on pause, lol. Sorry, Thank you for your time
