### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by RanjithkumarPop** [opentok/opentok-react-native#377]
<img width="1131" alt="Screen Shot 2019-12-30 at 1 27 32 PM" src="https://user-images.githubusercontent.com/52271028/71573146-5a1ffd00-2b08-11ea-9d61-79d3e0df0a56.png">
I have updated my react native to 0.61.3 and Xcode to 11.3. So all the libraries are linked through pod instead of manual linking. So the pod for opentok also installed through pod and then got an Nativemodule null error and after running the link command then I am getting the "'React/RCTBridgeModule.h' file not found" error in XCode as there are no react libraries linked to the library folder.

and tried install through pod file and I am getting the below issue.
<img width="573" alt="Screen Shot 2019-12-30 at 1 41 18 PM" src="https://user-images.githubusercontent.com/52271028/71573505-407fb500-2b0a-11ea-886a-fd9fa51eed21.png">

**Comment by sunweiyang** [comment]
I've experienced this too. Simply closing/opening Xcode and/or restarting your computer (sometimes a few times) or reinstalling pods usually resolves this for me. It's definitely frustrating, though; does anyone know a more permanent solution?

**Comment by enricop89** [comment]
closing/opening Xcode solved the issue for me.
I think it's more a problem related to the changes between RN 0.60 versions than to this library, so, unfortunately, I don't have any other solution :(

**Comment by abdulajet** [comment]
Try a `pod deintegrate` before installing
