### ISSUE TITLE
Membership getters for OTSession, OTSubscriber, and OTPublisher?

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#378]
There doesn't seem to be a way to get membership session information about an active session. For example, being able to get some variant or subset of these on demand would be useful:
* Number of users in a session (and even better, these users' info too)
* Whether subscriber is active and receiving an active publisher

**Comment by jeffswartz** [comment]
The application can track the state of the session by listening to the `connectionCreated`, `connectionDestroyed`, `streamCreated`, and `streamDestroyed` events dispatched by the Session object. Use the `connection` property of these events to identify connections.
