### ISSUE TITLE
OTPublisher can't work

### ISSUE THREAD

**Issue by momomojing** [opentok/opentok-react-native#387]
There's no picture of OTPublisher on the screen.but the session is connected.

OTPublisher screen is blocked by OTSubscriber.

            <OTSession
              // eventHandlers={this.sessionEventHandlers}
              ref={this.otSessionRef}
              apiKey={apiKey}
              style={{height: height, width: width}}
              sessionId={sessionId}
              token={videoToken}>
              <View
                style={{
                  position: 'absolute',
                  top: 0,
                  height: height,
                  width: width,
                }}>
                <OTSubscriber
                  properties={this.subscriberProperties}
                  eventHandlers={this.subscriberEventHandlers}
                  style={{
                    width: '50%',
                    height: '50%',
                  }}
                  // streamProperties={this.state.streamProperties}
                />

                <View
                  style={{
                    width: 125,
                    height: 200,
                    position: 'absolute',
                    bottom: 0,
                    right: 0,
                  }}> 
                  <OTPublisher
                    style={{
                      flex: 1,
                    }}
                    properties={this.state.publisherProperties}
                    eventHandlers={this.publisherEventHandlers}
                  />
                </View>
              </View>
            </OTSession>

**Comment by enricop89** [comment]
I do think you're missing a `View` tag.

```
<OTSession
          // eventHandlers={this.sessionEventHandlers}
          ref={this.otSessionRef}
          apiKey={apiKey}
          style={{height: height, width: width}}
          sessionId={sessionId}
          token={videoToken}>
          <View
            style={{
              position: 'absolute',
              top: 0,
              height: height,
              width: width,
            }}>
            <OTSubscriber
              properties={this.subscriberProperties}
              eventHandlers={this.subscriberEventHandlers}
              style={{
                width: '50%',
                height: '50%',
              }}
              // streamProperties={this.state.streamProperties}
            />
              </View>
            <View
              style={{
                width: 125,
                height: 200,
                position: 'absolute',
                bottom: 0,
                right: 0,
              }}> 
              <OTPublisher
                style={{
                  flex: 1,
                }}
                properties={this.state.publisherProperties}
                eventHandlers={this.publisherEventHandlers}
              />
            </View>
        </OTSession>
```
