### ISSUE TITLE
Build error in new version RN

### ISSUE THREAD

**Issue by romreed** [opentok/opentok-react-native#388]
I try run opentok-react-native at new version rn but got error:

`duplicate symbol '_OpenTokVersionNumber' in:
    /Users/imac/Library/Developer/Xcode/DerivedData/OpenTok-fucgfbgbnihdwmckpmphqzucajhh/Build/Intermediates.noindex/OpenTok.build/Debug-iphonesimulator/OpenTok.build/Objects-normal/x86_64/OpenTok_vers.o
    /Users/imac/WebstormProjects/OpenTok/ios/Pods/OpenTok/OpenTok.framework/OpenTok(OpenTok-x86_64-master.o)
duplicate symbol '_OpenTokVersionString' in:
    /Users/imac/Library/Developer/Xcode/DerivedData/OpenTok-fucgfbgbnihdwmckpmphqzucajhh/Build/Intermediates.noindex/OpenTok.build/Debug-iphonesimulator/OpenTok.build/Objects-normal/x86_64/OpenTok_vers.o
    /Users/imac/WebstormProjects/OpenTok/ios/Pods/OpenTok/OpenTok.framework/OpenTok(OpenTok-x86_64-master.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

    "opentok-react-native": "^0.12.2",
    "react": "16.9.0",
    "react-native": "0.61.5"  
Xcode Version 11.3.1 (11C504)
OS: mac Os Mojave  10.14.6 (18G103)

**Comment by SaveYourTime** [comment]
Same here!

**Comment by enricop89** [comment]
@romreed let me know if you fixed. Feel free to reopen the issue if needed
