### ISSUE TITLE
How to manually disconnect call?

### ISSUE THREAD

**Issue by apoorv-1310** [opentok/opentok-react-native#391]
Support parent call to child but due to some reason child disconnects the call.

so there seems no way that parent gets to know that child has hanged up the call.

instead the parent keeps on listing for call to be picked up 

how to fix this ?

i am using the following formats

import { OT, OTSession, OTPublisher, OTSubscriber } from "opentok-react-native";

anyhting that can be done ?

**Comment by enricop89** [comment]
Listen to onSessionDisconnect event and call a parent function from the child component should work.

```
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isConnected: false,
    };
    this.otSessionRef = React.createRef();
    this.sessionEventHandlers = {
      sessionDisconnected: event => {
        console.log('Stream created!', event);
        this.props.callSomeParentFunction("disconnected!");
      },
    };
  }
```

**Comment by apoorv-1310** [comment]
no it does't work,
it works when call is picked up and then disconnected.
in my case, call is never picked up.
can you please double chk ?

**Comment by enricop89** [comment]
I'm sorry, do you want to pick up or disconnect the call? Can you explain better your issue and indicate us steps to reproduce?

**Comment by apoorv-1310** [comment]
just disconnect,
as soon as it rings,
i dont want to pick it up, just disconnect

**Comment by Asalem1** [comment]
@enricop89 I think I'm running into a similar issue where I'm unable to forceDisconnect (or even disconnect) using the `OTSession`.

```

const sessionRef = useRef<any>(null);

const handleEndCall = () => sessionRef.current.disconnect()

...

return (
    <OTSession
        apiKey={OPENTOK_API_KEY}
        sessionId={sessionId}
        token={token}
        ref={sessionRef}
        eventHandlers={handleEventSignals}
      > 
           <Button onPress={handleEndCall} />
     </OTSession>
)

```

In this case, my expectations would be that the `Session` that's being referenced by the `OTSession`would generate a valid Session object with the `disconnect` property:

https://tokbox.com/developer/sdks/js/reference/Session.html#disconnect

Since it seems like there's some disconnect between the RN implementation and the SDK docs, I was wondering if there's a way to manually trigger a session disconnect. Put simply, is there any way I can use the `sessionRef` in the example above to disconnect a call?

**Comment by enricop89** [comment]
@Asalem1 can you try by calling **disconnectSession** and not disconnect please?

```
const sessionRef = useRef<any>(null);
const handleEndCall = () => sessionRef.current.disconnectSession()

...

return (
    <OTSession
        apiKey={OPENTOK_API_KEY}
        sessionId={sessionId}
        token={token}
        ref={sessionRef}
        eventHandlers={handleEventSignals}
      > 
           <Button onPress={handleEndCall} />
     </OTSession>
)
```

**Comment by Asalem1** [comment]
@enricop89 yup, was just about to comment on this saying that's the trick. 

Did some digging in the source to find that out. Any chance we can get an update on the docs to make that explicit? Or at least a link in the docs to somewhere that declares the session props?

**Comment by avinashyalgonde** [comment]
@enricop89 const sessionRef = useRef(null); and other things worked for me. Thanks man..!
