### ISSUE TITLE
How we publish live stream with multiple publisher in React Native

### ISSUE THREAD

**Issue by varunsdcet** [opentok/opentok-react-native#393]
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by msach22** [comment]
Thanks for filing an issue. This is possible by simply creating two `OTPublisher` components. Please see the documentation: https://github.com/opentok/opentok-react-native/blob/master/docs/OTPublisher.md
