### ISSUE TITLE
Sudden connectionDestroyed event fired, but the video/audio was working fine both before and after the event fired

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#394]
One of our users experienced a `connectionDestroyed` event in `OTSession`'s `eventHandlers` during an OpenTok session containing 2 users. However, users of both devices experienced a properly-working realtime video chat throughout the time both before and after the `connectionDestroyed` event fired. 

The session ID of this session is:
```
1_MX40NTgyODk0Mn5-MTU4NTMzOTQxMzQxM35oOEdoSEhSKytRYjhGUU1uV0djVit4RDl-fg
```

**Comment by evillemez** [comment]
This sounds like the behavior we see in certain cases, so wondering if it could be a duplicate of #271  ?

Do you know if there could have been any case shortly before this occurred where the `OTSession` component was remounted?  If so, 271 might be the reason.

**Comment by sunweiyang** [comment]
My codebase does not remount the `OTSession` component after initial instantiation. If it helps, this seems to happen more frequently for longer OpenTok sessions (greater than 30 minutes).

**Comment by Sach-SPF** [comment]
Guys - Any solution on this one?

**Comment by adaerodriguez** [comment]
Please, any change on this issue?

**Comment by HarshitPadalia** [comment]
Any solution on this one I am also facing same issue with latest 0.14.0 version?

**Comment by TalhaAhsan** [comment]
Are you still facing this issue?

**Comment by TalhaAhsan** [comment]
Closing this issue as is stale now. If required, a new issue can be opened.
