### ISSUE TITLE
How to check if the stream is connected in other device

### ISSUE THREAD

**Issue by apoorv-1310** [opentok/opentok-react-native#395]
i have 3 devices and all 3 ring togather.

if i pick any one of them, the other 2 should stop ringing, so i need some event in background(during ringing) and stop ringing other 2 

i tired using events,

   streamPropertyChanged(event) {
      console.log("streamPropertyChanged", streamPropertyChanged)
    },
    disconnected(event) {
      console.log("disconnected", event);
      PushNotificationService.setApplicationIconBadgeNumber(0);
    },
    streamDestroyed: event => {
      console.log("streamDestroyed",streamDestroyed);
    },
    signal(event) {
      console.log("signal", signal)
    }

 none of these works

@msach22 how can this be achieved ?

**Comment by liveclinic** [comment]
@msach22 Hello Manik, Can you please help with the issue above? Thank you.

**Comment by msach22** [comment]
This is not an issue with this library. This is application specific logic that is outside the scope of this library.

What you're looking for is to manage a state outside of OpenTok that allows you to see who has picked up the "call". The events that you have listed are not made for that, they are there to dispatch if a stream has been destroyed or a signal has been received, etc.
