### ISSUE TITLE
Screen sharing not working for react viro components

### ISSUE THREAD

**Issue by RahulJain7** [opentok/opentok-react-native#396]
I am successfully able to achieve Screen sharing with my publisher on android and a web based subscriber. The issue I am facing is that when in use Viro React native components, I am not able to render the Viro react components (eg. ViroARScene ) on the subscriber side ( it come black ). Although when I use native react component ( eg. View ), it runs perfectly. How can I go about screen sharing the Viro react native components as well. I have attached the App.js code below and the screen shots of publisher and subscriber. Please refer to the attached files for screen shots. Following is  the link my App.js https://drive.google.com/file/d/1NoK5Rku2gUMrihHszfn_Q7iBR9a-ar6a/view?usp=sharing

![publisher_screen_android](https://user-images.githubusercontent.com/13780713/78454377-655d6880-76b5-11ea-981f-4dbf522e8483.png)
<img width="366" alt="subscriber_web" src="https://user-images.githubusercontent.com/13780713/78454393-727a5780-76b5-11ea-81ac-4b272597af04.png">

**Comment by yashukla47** [comment]
did you find any solution @RahulJain7
