### ISSUE TITLE
Android: Video unavailable after another app uses camera, even after other app is closed

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#397]
I've verified this issue on opentok-react-native@0.12.2 (Android). When an OpenTok session is running, and then another app uses the camera (such as the default camera app, etc.), session video becomes disabled for my app, even after the the other app is killed. Session audio still works.

This is only an Android issue; iOS sessions seem to recover video after the other app is done with the camera.

Returning camera control to the OpenTok session would be ideal, since opening the camera app is a common Android accident (some models have features for quickly accessing the camera, i.e. a specific button, squeezing, etc.).

**Comment by sunweiyang** [comment]
I'll also add that there are some issues that happen when a phone is participating in an OpenTok session and a regular cellular phone call arrives (even if the user dismisses the call). Perhaps not directly related, but related in that hardware control is temporarily moved away from OpenTok and must be re-established or re-claimed by OpenTok for a smooth session.

**Comment by HarshitPadalia** [comment]
I am facing same issue in android devices

**Comment by abdulajet** [comment]
Can you try the latest version of the library?

**Comment by TalhaAhsan** [comment]
Are you still facing this issue?

**Comment by TalhaAhsan** [comment]
Closing this issue as it is old. If the issue still persists, a new issue can be opened.
