### ISSUE TITLE
Screen Sharing Not Working. After Few Seconds It not responding.

### ISSUE THREAD

**Issue by EfteazTE** [opentok/opentok-react-native#398]
I am creating an app for screen sharing in react native. Screen sharing is started and after few seconds its not responding even publisher app touch not working.
Code Snippet 
this.publisherPropertiesScreen = {
            publishAudio: false,
            publishVideo: true,
            videoSource: 'screen',
        };

publisher session
<OTSession
                    apiKey={this.apiKey}
                    sessionId={this.sessionId}
                    token={this.token}
                    eventHandlers={this.sessionEventHandlers}
                    style={call.opentokSession}>
                    <OTPublisher
                        properties={this.state.publisherProperties}
                        style={{display: 'none',}}
                    />
                </OTSession>

subscriber session
<OTSession
                    apiKey={this.apiKey}
                    sessionId={this.sessionId}
                    token={this.token}
                    eventHandlers={this.sessionEventHandlers}
                    style={call.opentokSession}>
                        <OTSubscriber style={call.opentokSubscriberScreen}/>
                </OTSession>

I am stuck in my developemnt. Please help me as soon as possible. Thanks

**Comment by msach22** [comment]
Have you specified a width and height in the publisher? Are you seeing any errors?

**Comment by EfteazTE** [comment]
@msach22 i have not used height and width. even using height and width same issue happens. and i am not getting any errors in console. please help

**Comment by EfteazTE** [comment]
@msach22 can you please help me as i am stuck in screen sharing part.

**Comment by msach22** [comment]
@EfteazTE I would recommend adding a width and height to the publisher as that's required for the native view when it's rendered. Unfortunately, we don't have the bandwidth to currently investigate the issue.

**Comment by EfteazTE** [comment]
@msach22 sir, using width and height to the publisher getting same issue. after few seconds publisher stops in android.

**Comment by abdulajet** [comment]
Thanks for the issue, can you check out the latest version of the library, and if your issue has not been resolved please reopen/create a new issue.
