### ISSUE TITLE
Keep audio for background app - Android

### ISSUE THREAD

**Issue by gwendall** [opentok/opentok-react-native#402]
Right now, when a connection is established to a stream and the user leaves the app, the audio shuts down. Is there a way to keep it on ?

**Comment by schonfeld** [comment]
I've been able to achieve this simply by adding the Background State: Audio capability to my Info.plist. The rest happens "automagically". There's a useful doc (with instructions) about this on [Tokbox's iOS SDK docs](https://tokbox.com/developer/sdks/ios/background-state.html). The same applies to this React Native wrapper.

**Comment by eduardoZapata** [comment]
Has anyone found a similar way to enable this for android?

**Comment by chaawlaapooja** [comment]
Has someone achieved this on android?

**Comment by gab07** [comment]
In our app we use a [Foreground Service](https://developer.android.com/guide/components/foreground-services)

**Comment by TalhaAhsan** [comment]
As already mentioned by gab07, the Android way to handle this would be by using a [Foreground Service](https://developer.android.com/guide/components/foreground-services). Background work is done only when you want to perform some task that is not visible to the user, you can read more about this [here](https://developer.android.com/guide/background)

**Comment by TalhaAhsan** [comment]
Closing this issue as there were no further queries made.

**Comment by KiranRadish** [comment]
@TalhaAhsan could you please give some steps to achieve this
