### ISSUE TITLE
How to add small video on top of full screen background video. 

### ISSUE THREAD

**Issue by ankitsdglobal** [opentok/opentok-react-native#405]
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---
![image](https://user-images.githubusercontent.com/56858237/81493379-76ac1d00-92d2-11ea-851f-6b395b8c5974.png)

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by ankitsdglobal** [comment]
I am able to fix this on ios but not working on android with position absolute. I am testing with 2 phones. If i publishes uses android then video is coming over video. But when i open with ios with same session the above video is going in the background

**Comment by freddiecabrera** [comment]
I am also having this same issue. On Android if a single person is on the call you can see the `OTPublisher` but when someone joins it disappears.

**Comment by HarshitPadalia** [comment]
I am also having this same issue. On some  Android devices having android 10

**Comment by jauggy** [comment]
> I am also having this same issue. On Android if a single person is on the call you can see the `OTPublisher` but when someone joins it disappears.

That's because it is appearing behind. You need to set sessionOptions correctly.

Here is sample code that I got working:
```

interface OpenTokViewProps {
  orientation: string;
  apiKey: string;
  token: string;
  sessionId: string;
}

const OpenTokView = (props: OpenTokViewProps) => {
  const navigation = useNavigation();
  const windowWidth = useWindowDimensions().width;
  const windowHeight = useWindowDimensions().height;
  const orientation = props.orientation;
  const sessionOptions = {
    androidOnTop: 'publisher',
    androidZOrder: 'mediaOverlay',
    useTextureViews: true,
  };

  const publisherWrapperStyle =
    orientation === 'portrait'
      ? styles.publisherWrapperPortrait
      : styles.publisherWrapperLandscape;

  const sessionEventHandlers = {
    connectionDestroyed: (connection: any) => {
      console.log('connectionDestroyed event');
    },
  };

  const subscriberEventHandlers = {
    disconnected: () => {
      console.log('subscriber disconnected event');
    },
  };

  return (
    <View style={{flex: 1}}>
      <OTSession
        eventHandlers={sessionEventHandlers}
        style={{flex: 1}}
        apiKey={props.apiKey}
        sessionId={props.sessionId}
        token={props.token}
        options={sessionOptions}>
        <OTSubscriber
          eventHandlers={subscriberEventHandlers}
          style={{
            width: windowWidth,
            height: windowHeight,
          }}></OTSubscriber>
        <View style={publisherWrapperStyle}>
          <OTPublisher style={styles.publisher}></OTPublisher>
        </View>
      </OTSession>
      <BluetoothGate />
      <MeasurementNotification />
    </View>
  );
};

export default OpenTokView;
```

and my styles:
```
 publisher: {
    height: '98%',
    width: '98%',
  },
  publisherWrapperPortrait: {
    position: 'absolute',
    height: '27%',
    width: '28%',
    bottom: 5,
    left: 5,
    alignItems: 'center',
    backgroundColor: 'white',
    justifyContent: 'center',
  },
  publisherWrapperLandscape: {
    position: 'absolute',
    height: '32%',
    width: '21%',
    bottom: 5,
    left: 5,
    alignItems: 'center',
    backgroundColor: 'white',
    justifyContent: 'center',
  },
```

**Comment by mzruiz** [comment]
Hola,

Here is the solution we are using to show a small video on top of another. Our project is using TS in all places but this component.


**conference.js**
```
const [publisher, setPublisher] = useState(0);

...

<>
  <OTSession
    apiKey={vonageAPIKey}
    sessionId={sessionId}
    token={token}>
      <OTPublisher style={[publisher === 0 ? styles.bigVideo : styles.smallVideo]} />
      <OTSubscriber style={[publisher === 0 ? styles.smallVideo : styles.bigVideo]}/>
  </OTSession>
</>
```

**styles**
```
  bigVideo: {
    position: 'absolute',
    width: DEVICE_WIDTH,
    height: undefined,
    aspectRatio: 3 / 4,
  },

  smallVideo: {
    position: 'absolute',
    width: 100,
    height: undefined,
    aspectRatio: 3 / 4,
    right: 10,
    top: 10,
    zIndex: 2,
  },
```

Which results in a working version for both iOS and Android: 
<img width="335" alt="Screen Shot 2020-11-03 at 8 58 32 AM" src="https://user-images.githubusercontent.com/51554976/97993956-c156af80-1db2-11eb-86ea-2449b25e2966.png">

Hopefully, this helps.

**Comment by abdulajet** [comment]
Thanks folks
