### ISSUE TITLE
Phone gets locked even when the video streaming is going on. How to keep it enable?

### ISSUE THREAD

**Issue by ankitsdglobal** [opentok/opentok-react-native#407]
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by schonfeld** [comment]
You can use a library like [react-native-idle-timer](https://github.com/marcshilling/react-native-idle-timer) to disable the device's idle timer. That should keep the screen on while you're in video.

Something like this should work:

```js
useEffect(() => {
  IdleTimerManager.setIdleTimerDisabled(true)

  return () => {
    IdleTimerManager.setIdleTimerDisabled(false)
  }
}, [])
```

**Comment by ankitsdglobal** [comment]
ok thanks i will check

**Comment by adaerodriguez** [comment]
Hi @ankitsdglobal I use react-native-keep-awake:

```
import KeepAwake from 'react-native-keep-awake';

render() {
    return (
        <View>
            <KeepAwake />
        </View>
)
```

**Comment by hdachrekar** [comment]
can you please provider a resolution for the same when launched from the browser on mobile devices.
