### ISSUE TITLE
Include missing timestamp field for audioStats and videoStats 

### ISSUE THREAD

**Issue by joekim** [opentok/opentok-react-native#409]
# Bug Report

**Current behavior**

subscriberEventHandlers.videoNetworkStats does not return a timestamp object

**Steps to reproduce**

Create OTSubscriber with eventHandler for videoNetworkStats and audioNetworkStats

          <OTSubscriber
            style={{ width: 100, height: 100 }}
            eventHandlers= {{videoNetworkStats: (obj) => {
               assert(obj.timestamp, "Should be defined");
            }} />

**Example Project**

I can create if requested.

**What is the current *bug* behavior?**

`videoNetworkStats.videoStats.timestamp` are both undefined
`audioNetworkStats.audioStats.timestamp`

**What is the expected *correct* behavior?**
It should have the milliseconds from the epoch

**Relevant logs and/or screenshots**
Can be included if requested.

**Comment by joekim** [comment]
I can make a PR. Two line change.

https://github.com/HappyDojo/opentok-react-native

**Comment by schonfeld** [comment]
On a related, but also unrelated matter... It'd be great to get avStats for OTPublisher, as well. Any idea why this lib only implements the OTSubscriber side of this?

**Comment by abdulajet** [comment]
@joekim did you make the PR?

**Comment by joekim** [comment]
> @joekim did you make the PR?

No. I just have the change in my repro linked above.

**Comment by abdulajet** [comment]
> No. I just have the change in my repro linked above.

Can you make a quick PR so I can merge it upstream for everyone

**Comment by TalhaAhsan** [comment]
This seems to have been solved in [this](https://github.com/opentok/opentok-react-native/pull/567) pull request. You can open the issue again if this PR hasn't solved the issue.
