### ISSUE TITLE
Using this library alongside the Nexmo SDK

### ISSUE THREAD

**Issue by brwinkle** [opentok/opentok-react-native#410]
# Bug Report

We're trying to use both the OpenTok React Native library and the Nexmo SDK, which we've written a Native Module wrapper over.

**Current behavior**
> (Summarize the bug encountered concisely)

Both the OpenTok and Nexmo libraries appear to include competing versions of the org.webrtc libraries. When the android build is run we get many instances of errors like this:

```
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class org.webrtc.AndroidVideoDecoder found in modules jetified-google-webrtc-1.0.30039-runtime.jar (org.webrtc:google-webrtc:1.0.30039) and jetified-opentok-android-sdk-v3-3.1.5-runtime.jar (com.opentok.android.v3:opentok-android-sdk-v3:3.1.5)
  Duplicate class org.webrtc.AndroidVideoDecoder$1 found in modules jetified-google-webrtc-1.0.30039-runtime.jar (org.webrtc:google-webrtc:1.0.30039) and jetified-opentok-android-sdk-v3-3.1.5-runtime.jar (com.opentok.android.v3:opentok-android-sdk-v3:3.1.5)
  Duplicate class org.webrtc.AndroidVideoDecoder$DecodedTextureMetadata found in modules jetified-google-webrtc-1.0.30039-runtime.jar (org.webrtc:google-webrtc:1.0.30039) and jetified-opentok-android-sdk-v3-3.1.5-runtime.jar (com.opentok.android.v3:opentok-android-sdk-v3:3.1.5)
...
```

**Steps to reproduce**
> (How one can reproduce the issue - this is very important)

Start a React Native project and include `"opentok-react-native": "^0.13.0",` in the package JSON. Also, add `implementation 'com.nexmo.android:client-sdk:2.6.2'` to the build.gradle file for the app (we have created a native module wrapper around this SDK for use in React Native). Then run the android build.

**Example Project**
> (If possible, please create an example project here on GitHub.com that exhibits the problematic behaviour, and link to it here in the bug report)

**What is the current *bug* behavior?**
> (What actually happens)

The errors above are output.

**What is the expected *correct* behavior?**
> (What you should see instead)

The app should launch and the libraries should play well together.

**Relevant logs and/or screenshots**
> (Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

**Comment by msach22** [comment]
If you upgrade to the latest Android SDK (2.17.0), it should be able to resolve this issue.

**Comment by brwinkle** [comment]
Thank you, @msach22. So just to be clear, the recommendation is to fork this library to update the underlying dep?

**Comment by msach22** [comment]
@brwinkle Please feel free to submit a PR to the main repo to update the native SDKs to 2.17.0. We really appreciate all contributions :)
