### ISSUE TITLE
React Native ios duplicate publishing and not subscribing issue

### ISSUE THREAD

**Issue by htuzel** [opentok/opentok-react-native#413]
# Bug Report

**Current behavior**
> (Summarize the bug encountered concisely)

**Steps to reproduce**
I am trying to connect 2 people from browser and phone. I am just trying to simple connection without extra feature. 

**Example Project**
> (If possible, please create an example project here on GitHub.com that exhibits the problematic behaviour, and link to it here in the bug report)

```
        <OTSession
          apiKey={this.state.apiKey}
          sessionId={this.state.sessionId}
          token={this.state.token}>
          <OTPublisher style={{width: 100, height: 100}} />
          <OTSubscriber
            subscribeToVideo={true}
            style={{width: 100, height: 100}}
          />
        </OTSession>

```

**What is the current *bug* behavior?**
> it is working fine with android but there are some problems 
Problem 1:
I am generally seeing multiple videos on web browser. (it is fine on android) (So, it seems react native creating multiple publishers)
Problem 2:
I can't see other side's video on ios (so it seems, it is not subscribing publisher's stream.)

**What is the expected *correct* behavior?**
> 

- I need to see only one subscriber on web side
- I need to see web browser's publishing

**Relevant logs and/or screenshots**
I am taking this error on console:
```OTRN JS: There was an error:  {message: "The operation couldn’t be completed. (OTSessionErrorDomain error 1015.)", code: 1015}```
It is a private repo, but if you ping me, I can share it.

Also, I tried it with sample repo: https://github.com/opentok/opentok-react-native-samples and it is working. I think there are a problem with react version and it is not compatible with 0.62.2

**Comment by abdulajet** [comment]
We have update the library, give it a try and see if it fixes your issue https://github.com/opentok/opentok-react-native/releases/tag/v0.17.0
