### ISSUE TITLE
No audio with bluetooth device during a video

### ISSUE THREAD

**Issue by adaerodriguez** [opentok/opentok-react-native#415]
Hello guys,

I have a weird issue when I 'm connected in a video from PC(Web) to mobile Android/iOS. If during the video I try to change the audio output to a bluetooth sound device (from mobile) I can't heard anything and the other person in the call doesn't heard me. 
When I change the output to the mobile again I can re-establish the sound. There is any possibility to control  the output sound or this is automatic?

I did the test with bluetooth earphones and bluetooth speaker. What can I do?

Thanks for your help!!!! :)

**Comment by chaawlaapooja** [comment]
@adaerodriguez You'll have to explicitly switch the audio output to `headphones`. 

I achieved this with the help of `react-native-switch-audio-output`

Here is the code that you can help you :

if you explicitly want user to switch to headphones by selecting an option :
`RNSwitchAudioOutput.selectAudioOutput(RNSwitchAudioOutput.AUDIO_HEADPHONE)`

if you automatically want to detect it with the help of `react-native-device-info`, you can make use of `useEffect`

`import { useIsHeadphonesConnected } from 'react-native-device-info'`
`const { result } = useIsHeadphonesConnected()
  useEffect(() => {
    if (result) {
      setAudioOutput('Bluetooth')
      setAudioIcon('icons24pxheadphones')
    } else {
      setAudioOutput('Speaker')
      setAudioIcon('icons24pxspeaker')
      RNSwitchAudioOutput.selectAudioOutput(RNSwitchAudioOutput.AUDIO_SPEAKER)
    }
  }, [result])`

**Comment by abdulajet** [comment]
Thanks @chaawlaapooja
