### ISSUE TITLE
Audio is not reproducing when the camera don't have permissions on video call

### ISSUE THREAD

**Issue by Matti93GL** [opentok/opentok-react-native#417]
Hello people! We are facing an issue that is quite difficult to solve, the issue happens when we make a video call and we do not give permission to the camera, the microphone does not reproduce any type of sound, the call remains without sound, however if we give permission to the camera we can listen normally. This issue is only happening to us on Android.
I await your comments!
Thanks!!!!

**Comment by abdulajet** [comment]
Thanks for the issue, can you check out the latest version of the library, and if your issue has not been resolved please reopen/create a new issue.
