### ISSUE TITLE
Set the subscribeToVideo of OTSubscriber is false, but still to subscribe stream

### ISSUE THREAD

**Issue by TerrenceTang** [opentok/opentok-react-native#42]
I set OTSubscriber which value of subscribeToVideo is false, but it still to play video.

**Comment by msach22** [comment]
Thanks for reporting this, @TerrenceTang ! As of now, the library does not support `subscribeToVideo` or `subscribeToAudio`, but we can totally add that in the next release!

**Comment by msach22** [comment]
I just saw that the READMe has the `subscribeToVideo` and `subscribeToAudio` which is an issue. I will add this feature ASAP!

**Comment by msach22** [comment]
@TerrenceTang could you please let me know which platform you're using? iOS or Android? Could you also share what your `OTSubscriber` component looks like?

**Comment by TerrenceTang** [comment]
Thank you for your response.  I am using in  Android platform.
The example code is in below.
```javascript
this.subscriberProperties = {
      subscribeToAudio:false,
      subscribeToVideo:false
}
<OTSession  apiKey={APP_CONFIG.OpenTokAPIKey} 
    sessionId={this.state.sessionID} 
    token={this.state.accessToken}>
   <OTSubscriber style={localstyles.rtc} properties={this.subscriberProperties}  
        eventHandlers={this.subscriberEventHandlers }/>
</OTSession>
```

**Comment by msach22** [comment]
@TerrenceTang Thanks for sharing me your code. It looks like there is a bug on the Android end: https://github.com/opentok/opentok-react-native/blob/master/android/src/main/java/com/opentokreactnative/OTSessionManager.java#L144

This should be 
```
        mSubscriber.setSubscribeToVideo(properties.getBoolean("subscribeToVideo"));
```

If you're up for it, please send a PR, if not I'm happy to patch this on Monday!

**Comment by msach22** [comment]
@TerrenceTang Are you changing this in the `node_modules` or in your Android studio project? If you change it in the `node_modules`, you have to re-link the library by running: `react-native link opentok-react-native`.

I tested this out and it's now working as expected.

**Comment by msach22** [comment]
Please use `v0.5.1` for the fix!
