### ISSUE TITLE
Error not called when publish fails

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-react-native#424]
# Bug Report

**Current behavior**
Under certain circumstances android publisher does not raise error (otrnerror or error) or success (streamCreated) event. 

When this happen, the other users can not subscribe (which indicates clearly that publish did not work). This is a problem as whithout any feedback to users, we sometimes are in a strange situation where two people think that everything is working fine but only one of the two see and hear the other !

**Steps to reproduce**
A reproducible scenario is to start a google meet meeting and share you screen in this meeting than go in your opentok react native application which can not publish anymore but never reports it.

**What is the expected *correct* behavior?**
In this case an error should be raised or a the publisher should publish !

**Relevant logs and/or screenshots**
I investigated a little and it seems that the problem is not really in opentok-react-native but in opentok android SDK. Indeed, in the OTSessionManager class, none of the PublisherListener method are called.

**Comment by mbouxin** [comment]
I reproduced and filled an issue with the native SDK examples
https://github.com/opentok/opentok-android-sdk-samples/issues/295

**Comment by enricop89** [comment]
@mbouxin Thank you, I'll follow up on the native one 😄
