### ISSUE TITLE
Rendered text won't go away after updating state

### ISSUE THREAD

**Issue by pydlv** [opentok/opentok-react-native#426]
# Bug Report

**Current behavior**
> I have a `<Text>` element conditionally rendered next to `<OTPublisher>` like so:
```
<View style={style.localVideo}>
    <OTPublisher
        properties={this.publisherProperties}
        style={style.rtcView}
        eventHandlers={this.publisherEventHandlers}
    />
    {!this.state.hasLocalStream &&
        <Text>
            {this.state.localMessage}
        </Text>
    }
</View>
```

When I update `this.state.hasLocalStream` from `false` to `true`, the `<Text>` element continues to render on the screen, despite React DevTools no longer showing the `<Text>` element to be a part of the DOM. Also in the devtools, the state is correct.

Changing to the following code results in no text being visible after the state update, which is the correct behavior, but it is a hacky solution and took me a while to figure out:
```
{!this.state.hasLocalStream &&
    <Text>
        {this.state.localMessage}
    </Text>
    || <Text></Text>
}
```
**What is the expected *correct* behavior?**
> It is expected that once `this.state.hasLocalStream` is updated from `false` to `true` using this.setState, the `<Text>` element would no longer render on screen.

**Examples:**
Code:
```
<View style={style.localVideo}>
    <OTPublisher
        properties={this.publisherProperties}
        style={style.rtcView}
        eventHandlers={this.publisherEventHandlers}
    />
    {!this.state.hasLocalStream &&
        <Text>
            {this.state.localMessage}
        </Text>
    }
</View>
```

Result after setting `this.state.hasLocalStream` to `true`:
![image](https://user-images.githubusercontent.com/24441042/87478908-64ef3a80-c5df-11ea-8843-b64c6065fef7.png)

Code:
```
<View style={style.localVideo}>
    <OTPublisher
        properties={this.publisherProperties}
        style={style.rtcView}
        eventHandlers={this.publisherEventHandlers}
    />
    {!this.state.hasLocalStream &&
        <Text>
            {this.state.localMessage}
        </Text>
        || <Text></Text>
    }
</View>
```

Result after setting `this.state.hasLocalStream` to `true`:
![image](https://user-images.githubusercontent.com/24441042/87479027-97993300-c5df-11ea-9980-e9db610d425a.png)

This is react native version 0.62.2.

**Comment by abdulajet** [comment]
This seems like a bug with react-native? We have updated the library to the lastest version, try it out and see if it fixed your issue
