### ISSUE TITLE
Publisher not showing

### ISSUE THREAD

**Issue by vinoth12594** [opentok/opentok-react-native#427]
Once call connected successfully publisher not visible, getting 409 conflict error.
`POST https://api.opntok.com/v2/project/{project-id}/archive resultes in a conflict Response: ("code": 15001, "message": "HTTP 409 conflict ", "description": "HTTP 401 Conflict")`

**Comment by enricop89** [comment]
Hi, please see documentation https://tokbox.com/developer/rest/#start_archive

```
The HTTP response has a 409 status code if you attempt to start an archive for a session that does not use the OpenTok Media Router or if the session is already being recorded.
```
