### ISSUE TITLE
Very frequent "Dimensions changed for publisher/subscriber" event logs for sessions, as seen in the web Inspector Tool

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#429]
In our RN app, we have very clearly defined widths, heights, and positions for our `OTPublisher` and `OTSubscriber` components, which don't change throughout each session. Despite this, when we go onto the TokBox online Inspector Tool, we see lots of "Dimensions changed for publisher" and "Dimensions changed for subscriber to User" event logs (more than one per minute)

- Is this part of normal operation, or an indicator of a problem?
- Could this affect session quality? We've been getting some reports of degraded performance, and are wondering if addressing this issue would help (in addition to decreasing publisher bitrate/resolution, etc.).

Session ID of one of these sessions exhibiting these event logs:
2_MX40NTgyODk0Mn5-MTU5NDkyNjM2MzYwOX5CRUhpS3B0YUsvdnBkdEdHbmV3SkovY2l-fg

**Comment by mingyjongo** [comment]
Experiencing the same, would love some insight here

**Comment by enricop89** [comment]
Hello, those events are about frame rate or resolution change. It's not a problem at all, but I agree that the name could be confusing

**Comment by sunweiyang** [comment]
@enricop89 Thank you for clarifying.
