### ISSUE TITLE
Toggle camera not working expected when 2 or more camera available on device

### ISSUE THREAD

**Issue by Sach-SPF** [opentok/opentok-react-native#432]
I have an issue on Android especially with a device that has more than 2 cameras like Samsung Note 9/10 etc.  whereas ToggleCamera function is not working as expected with the intention to focus on the rear camera.

**Comment by abdulajet** [comment]
Hey can you post a project/follow the issue template please https://github.com/opentok/opentok-react-native/tree/main/.github/ISSUE_TEMPLATE

We have released a new version of the library so try it and see if it helps
