### ISSUE TITLE
OT.changeCameraPosition not trigger

### ISSUE THREAD

**Issue by vinoth12594** [opentok/opentok-react-native#437]
When i use OT.changeCameraPosition(this.state.publisherId, 'back') it's not working as per my expectation.
I get my publisherId in 
`this.publisherEventHandlers = {
      streamCreated: event => {event.streamId}`

Anything mistake from my side.

**Comment by msach22** [comment]
You can change the camera position by updating `cameraPosition` property in  `OTPublisher`:
https://github.com/opentok/opentok-react-native/blob/master/docs/OTPublisher.md

**Comment by hanishsharma31** [comment]
I am facing the same issue. Below code is not working 

OT.changeCameraPosition(publisherId, publisherProperties.cameraPosition);

I am changing the cameraPosition programatically and passing the updated value to the above code. But when I use OT.publishAudio(publisherId, publisherProperties.publishAudio) or OT.publishVideo(publisherId, publisherProperties.publishVideo) the cameraPosition changes. Please assist.
