### ISSUE TITLE
screen share stream in zoom in using open tok

### ISSUE THREAD

**Issue by Ayubbabaxelits** [opentok/opentok-react-native#439]
I am using function components in the react-native where I am using opentok for video call and screen sharing for me the screen sharing view is getting zoom in like the image I had attached  also I am giving full width and height of the screen for the subscriber please once check it I am not getting an idea why it's happening like please help me out friends

[Please click on the image it's zooming in like that][1]

View.tsx
 

    <View style={videoScreenStyles.oTSubscriberStyles}>
                <OTSession apiKey={OPENTOKAPI_KEY} sessionId={currentSelectedSchedule.sessionId}
                           token={currentSelectedSchedule.token} eventHandlers={sessionEventHandlers} ref={otSessionRef}>
                    {videoCallConnected ? <OTPublisher properties={publisherProperties}
                                                       style={videoScreenStyles.oTPublisherStyles}
                    /> : null}
                    {loading ? <View style={videoScreenStyles.centered}>
                        <ActivityIndicator size="large" color={primaryColor}/>
                        <Text style={videoScreenStyles.texTherapist}>Please wait still therapist join the call</Text>
                        <Button
                            ViewComponent={LinearGradient}
                            onPress={() => cancelHandler()}
                            linearGradientProps={{
                                colors: [primaryColor, secondaryColor],
                                start: {x: 0.5, y: 0},
                                end: {x: 0.5, y: 1},
                            }}
                            buttonStyle={{height: 30, width: 70, borderRadius: 15}}
                            title={appointmentCancel}
                            titleStyle={{fontSize: 12, marginTop: 0, paddingTop: 0, fontWeight: 'bold'}}
                        />
                    </View> : null}
                    <OTSubscriber
                        style={videoScreenStyles.oTSubscriberStyles}
                        properties={subscriberProperties}
                    />
                </OTSession>
                {loading ? null : <View style={videoScreenStyles.bottomBar}>
                    <TouchableWithoutFeedback onPress={endCallHandler}>
                        <Image source={require('./../../assets/video/endcall_icn.png')}/>
                    </TouchableWithoutFeedback>
                    <TouchableWithoutFeedback onPress={micHandler}>
                        <Image
                            source={!mic ? require('./../../assets/video/micicn_mute.png') : require('./../../assets/video/mic_icn.png')}/>
                    </TouchableWithoutFeedback>
                    <TouchableWithoutFeedback onPress={videoHandler}>
                        <Image
                            source={!video ? require('./../../assets/video/videoicn_off.png') : require('./../../assets/video/video_icn.png')}/>
                    </TouchableWithoutFeedback>
                    <TouchableWithoutFeedback onPress={rotatoHandler}>
                        <Image style={videoScreenStyles.videoCallImage}
                               source={rotato == 'front' ? require('./../../assets/video/front_rotate.png') : require('./../../assets/video/back_rotate.png')}/>
                    </TouchableWithoutFeedback>
                </View>}
            </View>

styles.tsx

    import {
        StyleSheet, Dimensions, Platform
    } from 'react-native';
    
    const { width, height } = Dimensions.get('screen');
    
    const videoScreenStyles = StyleSheet.create({
        container: {
            flex: 1,
        },
        oTPublisherStyles: {
            position: 'absolute',
            zIndex: 999,
            width: 150,
            height: 200,
            right: 10,
            top: Platform.OS === 'ios' ? 40 : 10,
        },
        oTSubscriberStyles: {
            position: 'absolute',
            width: width,
            height: height,
            resizeMode:'contain',
        },
        bottomBar: {
            position: 'absolute',
            flexDirection: 'row',
            bottom: 50,
            backgroundColor: '#0C233C50',
            justifyContent: 'space-between',
            right: 10,
            left: 10,
            padding: 12,
            borderRadius: 20,
            borderColor: '#707070'
        },
        timerBar: {
            position: 'absolute',
            top: 50,
            backgroundColor: '#0C233C50',
            right: 10,
            left: 10,
            padding: 12,
            borderRadius: 20,
            borderColor: '#707070'
        },
        centered: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            flexDirection:'column'
        },
        texTherapist:{
            marginTop:20,
            marginLeft:20,
            marginRight:20,
            fontFamily:Platform.OS === 'ios' ? 'SF Mono' : 'sfmono',
            textAlign:'center'
        },
        videoCallImage:{
            width:48,
            height:48
        }
    
    });
    
    export default videoScreenStyles;

  [1]: https://i.stack.imgur.com/ymMvI.png

**Comment by kundanthe** [comment]
Hi @Ayubbabaxelits  have you got any fix ..?

**Comment by pietgk** [comment]
is this fixed now?

**Comment by beHaze** [comment]
Hi @Ayubbabaxelits we haven't heard back from you in a while so we're closing this issue for now. Please, reach out if you still need help.
