### ISSUE TITLE
Session unmount in functional component

### ISSUE THREAD

**Issue by Ayubbabaxelits** [opentok/opentok-react-native#440]
Hi guys,

can anybody tell me how to unmount the session for disconnect on the button click below method I tried it's not working because of this I am getting multiple events callbacks any solution for this?

```
useEffect(() => {
        return () => {
            otSessionRef.current.disconnectSession();
        }
    }, []);
```

As well as i tried in the button click as well below code 

 ```
otSessionRef.current.disconnectSession();
        navigation.navigate('AppointmentsTab');
```

**Comment by smartsatheesh** [comment]
<TouchableOpacity
          style={BTN_ICON_CLOSE}
          onPress={() => session.current.disconnectSession()}>
          <Icon icon='callClose' />
        </TouchableOpacity>

**Comment by muzammil-kt** [comment]
is it will turf the camera and microphone automatically? for me, Camera is still running in the background.
