### ISSUE TITLE
Zoom In and Zoom out for screen sharing in subscriber

### ISSUE THREAD

**Issue by menasSawwaf** [opentok/opentok-react-native#441]
Is there way to zoom in and zoom out  for subscriber view when publisher start screen sharing?

**Comment by tusharpsychonline** [comment]
Hello mesasSawwaf,

Were you able to get that resolved? I tried and I see cropped screenshare, only the middle section is visible.

**Comment by christophby** [comment]
@menasSawwaf @tusharpsychonline did you fix it somehow?

**Comment by abdulajet** [comment]
seems like a duplicate of #439
