### ISSUE TITLE
Unpredictable OTSubscriber events for video availability (for video placeholders, etc.)

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#442]
We have a 1-to-1 video chat app using opentok-react-native 0.14.0, and are trying to implement a placeholder overlay (partner's profile photo within a `position: 'absolute'` View component) that appears whenever video is unavailable. We have a boolean state `placeholderIsVisible` that changes based on OTSubscriber events:

```
  const [setPlaceholderIsVisible, setPlaceholderIsVisible] = useState(false);

  ...

  const subscriberEventHandlers = {
    videoDataReceived: (event) => {
      setPlaceholderIsVisible(false);
    },
    videoDisabled: (event) => {
      setPlaceholderIsVisible(true);
    },
    videoDisableWarning: () => {
      setPlaceholderIsVisible(true);
    },
    videoDisableWarningLifted: () => {
      setPlaceholderIsVisible(false);
    },
    videoEnabled: () => {
      setPlaceholderIsVisible(false);
    },
  };

  ...

  <OTSubscriber
    ...
    eventHandlers={subscriberEventHandlers}
    ...
    />
```

Essentially, we want `placeholderIsVisible` to be `false` whenever video is coming through. This seems to work sometimes, but the  problem is that more often than not (roughly 30% of the time), the placeholder would be present even though the video is clearly available (i.e. `placeholderIsVisible` is `true`).
1. Are we misunderstanding the usage of the `videoDataReceived` event? (We assume that it should trigger whenever a video frame is decoded based on what the documentation says, but that doesn't seem to be happening.)
2. If this is an incorrect approach, what is the recommended way to implement a video placeholder?

**Comment by enricop89** [comment]
@sunweiyang the approach seems ok, but how would you filter by a subscriber (streamId)? Could it be that you are receiving an event that refers to another subscriber?

**Comment by sunweiyang** [comment]
@enricop89 Ohh are you saying that both users' subscribers are triggering the same set of eventHandlers? If not, please help me understand.

**Comment by enricop89** [comment]
@sunweiyang Sorry for the delay in this, I meant the first one you said (I thought that there was more than one subscriber).
In your use case, a simple one-one call, your approach should work.

You are setting `placeholderIsVisible` to true only when you receive the `videoDisabledWarning` event right? If so, it should work as intended.

**Comment by sunweiyang** [comment]
@enricop89 I'm also setting `placeholderIsVisible` to true when i receive the `videoDisabled` event. Am I not supposed to? Am I only supposed to do it for `videoDisabledWarning`?

**Comment by enricop89** [comment]
@sunweiyang yes, sorry I didn't spot it. I think it's correct as well, so I would try debugging the code and see when the events (videoDisabledWarning and videoDisabled) are triggered but the video is visible.
