### ISSUE TITLE
App crashes when permissions dialog comes up on Android

### ISSUE THREAD

**Issue by jauggy** [opentok/opentok-react-native#443]
# Bug Report

**Current behavior**
When I make a video conference call and the permissions dialog comes up and don't do anything eventually the app will crash. Looking at the logs there I see the error: 
```
OTRN JS: There was an error:  {"message": "Error publishing. Could not find native publisher instance."}"
```

Once permissions are enabled and I restart the app everything works fine. 

Tested on Android device.

**Steps to reproduce**
Make sure to reset app permissions.
Begin a video conference call. When the dialog to accept permission comes up wait a few seconds.

**Example Project**
I don't have a sample project. But my component looks like this:
```
interface OpenTokViewProps {
  orientation: string;
  apiKey: string;
  token: string;
  sessionId: string;
}

const OpenTokView = (props: OpenTokViewProps) => {
  const windowWidth = Dimensions.get('window').width;
  const windowHeight = Dimensions.get('window').height;
  const orientation = props.orientation;
  const sessionOptions = {
    androidOnTop: 'publisher',
    androidZOrder: 'mediaOverlay',
    useTextureViews: true,
  };

  let publisherWrapperStyle =
    orientation === 'portrait'
      ? styles.publisherWrapperPortrait
      : styles.publisherWrapperLandscape;

  const sessionEventHandlers = {
    otrnError(error: any) {
      console.log('otrnError', error);
    },
  };

  return (
    <View style={{flex: 1}}>
      <OTSession
        eventHandlers={sessionEventHandlers}
        style={{flex: 1}}
        apiKey={props.apiKey}
        sessionId={props.sessionId}
        token={props.token}
        options={sessionOptions}>
        <OTSubscriber
          style={{
            width: windowWidth,
            height: windowHeight,
          }}></OTSubscriber>
        <View style={publisherWrapperStyle}>
          <OTPublisher style={styles.publisher}></OTPublisher>
        </View>
      </OTSession>
    </View>
  );
};

export default OpenTokView;
```

Package version:
opentok-react-native@0.14.0
react-native@0.62.2

**What is the current *bug* behavior?**
See above.

**What is the expected *correct* behavior?**
No crash

**Relevant logs and/or screenshots**
Here's the dialog and my app has already crashed at this point.
https://imgur.com/jkIWYa3

**Comment by Pyroboomka** [comment]
Bumping this one, cause having similar issues. 

In our app flow we had this error happing quite frequently based on sentry reports. We tried to move permissions handling to react native side and do not mount session/publisher/subscriber components until permissions are granted. But our case is a little bit different since we allow audio-only calls - so we mount components when we have **at least** microphone permission granted even when camera permission is denied. In that case

 ```properties={ ..., publishVideo: false }```

 is passed to OTPublisher yadayada.

Can this be the culprit? Should we try mounting the components only when both camera/microphone permissions are granted even for audio-only calls?

**Comment by abdulajet** [comment]
Thanks for the issue, can you check out the latest version of the library, and if your issue has not been resolved please reopen/create a new issue

**Comment by flogy** [comment]
@abdulajet Having the same error in version `0.20.4`. It happened on an Android 7.1.1 device after the app was in background and then moved back to foreground again (having a foreground service active).

I am not sure if there also were any permission dialogs coming up as the error occurred on a customer's device and was reported by our error reporting software which does not include logs of permission dialogs.

Thanks in advance.
