### ISSUE TITLE
Audio stops working when there is an interruption in ongoing opentok session

### ISSUE THREAD

**Issue by vishnu-ramineni** [opentok/opentok-react-native#445]
# Bug Report

**Current behavior**
> If user-x didn't accept the call and call ringing is going on from application A then user-x still won't be able to hear what user-y is talking about and microphone also didn't work from user-x side.

**Steps to reproduce**
> Let's say there are two users user-X(uses android/iOS app) and user-Y(web/mobile app). And there is an ongoing opentok session(audio/video) between user-X and user-Y. User-x received a call from other applications like WhatsApp or MSTeams at this moment User-x can't hear anything what User-Y is talking about and User-Y can only listen to User-X incoming call ringtone and microphone at user-X end will stop working. And the mentioned scenario is handled by other audio/video calling apps like WhatsApp and MSTeams.

**Example Project**
> not applicable

**What is the current *bug* behavior?**
> Audio stopped working at the user end when there is interruption from other apps like whatsapp call or msteams call. User can't hear anything in the ongoing opentok audio/video session.

**What is the expected *correct* behavior?**
> Desired behaviour should be User-X microphone should work and User-X should be able to hear what User-Y talking about even if there is an interruption from other apps in the device.

**Relevant logs and/or screenshots**
> not applicable

**Comment by voxiel** [comment]
I'm facing the same problem. Have you found a solution?

**Comment by minuitagency** [comment]
Hi, same issue here

**Comment by voxiel** [comment]
I finally got it! I created a service for the connection and used a custom audio driver. Got the code for custom audio driver here: 

https://github.com/opentok/opentok-android-sdk-samples

Hope it helps!

**Comment by mehulTank** [comment]
I am getting the same issue if we are calling from the same platform i.e Android to Android it is working fine but if calling from ios to android then Video is displaying but the audio is not getting audio is lost.

**Comment by abdulajet** [comment]
@mehulTank is your issue to do with call interruptions?

**Comment by gautammukoo** [comment]
Hi Opentok Team,
We are facing the exact same issue in production, can you please take a look at this and fix this in priority!

**Comment by abhinavbussa** [comment]
We are facing the same issue on our app and it's a bug from our production. Can you please look more into this and provide a fix on priority?

**Comment by gautammukoo** [comment]
> @mehulTank is your issue to do with call interruptions?

@abdulajet I am facing the similar issue but on ios device. If i join a opentok video session from mobile and recieve a VoIP call in between the vonage session, as soon as i disconnect / decline the VoIP call , the audio is lost in vonage session. Whereas i don't see any changes in publisher properties. We are facing this issue in production level and is affectinf our customers, can you please help ?

**Comment by manupou** [comment]
We are facing same issue in production. And its impacting our customers. Can you please look into it on priority?? Thanks!

**Comment by abdulajet** [comment]
Can everyone share what version on the library they are using and which devices specifically are encountering the issue (so iOS 14 running on iPhone 12 etc) thanks

**Comment by gautammukoo** [comment]
@abdulajet I am using opentok-react-native 0.19.0
Devices where i am facing this issue : iOS (iPhone 12, 12 mini ,10, SE 2nd gen) , Software Version (15.1, 14.7)

**Comment by abhinavbussa** [comment]
@abdulajet we are using opentok-react-native  @0.19.0
We are facing on iOS devices and most of them are latest version devices
iOS (iPhone 11, 11 mini, 12, 10), Software Version (15.1, 14.7)

**Comment by abdulajet** [comment]
So *only* iOS you have the issue or has anyone seen it on Android too?

**Comment by NileshDeshmukh27** [comment]
for us, the issue _only_ with IOS @abdulajet

**Comment by gautammukoo** [comment]
@abdulajet only on iOS, on android its working

**Comment by gautammukoo** [comment]
@abdulajet any update on this issue ?

**Comment by enricop89** [comment]
Just to be clear, does this happen also on the basic iOS app https://github.com/opentok/opentok-ios-sdk-samples-swift/tree/main/Basic-Video-Chat?

**Comment by gautammukoo** [comment]
@enricop89 We are using opentok-react-native @0.19.0
I tried the similar using BasicVideoChat, it will be helpful if we get a fix for this with current package as we are facing this in production level and is a priority bug
Thanks 
 link : https://github.com/opentok/opentok-react-native-samples/tree/main/BasicVideoChat

**Comment by abdulajet** [comment]
Still trying to figure it out, Can you try setting the audio session to active when your iOS application resumes from the background in the Appdelegate file? https://developer.apple.com/documentation/avfaudio/avaudiosession/1616627-setactive

**Comment by gautammukoo** [comment]
Hi @abdulajet , i tried setting the AVAudioSession setActive to TRUE when app enters foreground, but still the audio doesn't work . Also to note this, whenever we try to cancel the call, the connectionDestroyed event handler is not being called which leads to my App crash

**Comment by abhinavbussa** [comment]
> Still trying to figure it out, Can you try setting the audio session to active when your iOS application resumes from the background in the Appdelegate file? https://developer.apple.com/documentation/avfaudio/avaudiosession/1616627-setactive

I tried this on iOS and still has the same issue.

**Comment by gautammukoo** [comment]
@abdulajet Hi , please refer https://github.com/opentok/opentok-react-native/issues/562 , there is a features update provided by vonage itself . This can solve our problem. 
Request to update the package to the latest. 
Thankyou

**Comment by TalhaAhsan** [comment]
Latest version of the library fixes this, see #562.
