### ISSUE TITLE
Not officially supported

### ISSUE THREAD

**Issue by alexbrazier** [opentok/opentok-react-native#450]
This line has recently been added to the top of the readme in #447:

> Please note that this library is not officially supported by Vonage.

Are you able to clarify what this means for the repo?
- Does it mean there will be no more updates to the repo, e.g. updating the native sdk to `2.18.x`, or bug fixes;
- or development will just be a bit slower but you will still update it and merge pull requests?

Do we need to fork this repo and maintain it separately or should we continue relying on this repo?

**Comment by enricop89** [comment]
Hi @alexbrazier, although I understand your concerns about the statement, I just wanted to clarify that nothing has changed recently, all of our accelerator sample code and apps are officially community-supported and this has always been the case. 

This means it is supported by our user base and also is internal developer relation team on a best effort basis.
