### ISSUE TITLE
BasicVideoChat UI is not displayed. "Could not find generated Setter" & "not  allowing consideration lib/x86/libopentok.so"

### ISSUE THREAD

**Issue by DanielMenke** [opentok/opentok-react-native#453]
# Bug Report

**Current behavior**
Starting up the example app BasicVideoChat. All credentials provided (Using a publisher token) on Android. Tested on phsyical device and on emulator device

Emulator Device: Pixel 3, API 29
Physical Device: Pixel 3, Androd 11

**Steps to reproduce**
Follow the instructions to start the android app

**Example Project**
BasicVideoChat

**What is the current *bug* behavior?**
Permissions for audio and video are requested but after that, the app just shows a blank screen. If I put a text component in the render function, it gets displayed, but nothing else. No errors shown in remote debugging.

**What is the expected *correct* behavior?**
App shows some kind of interface. Or at least an error is shown why nothing gets displayed.

**Relevant logs and/or screenshots**
The following logs are displayed in `adb logcat`
```
 5492 D ApkSoSource: not allowing consideration of lib/x86/libopentok.so: deferring to libdir
 5533 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.opentokreactnative.OTPublisherViewManager
```

**Comment by abdulajet** [comment]
The sample apps have been updated can you test them out and reopen/create a new issue if your problem hasnt been solved. Thanks
