### ISSUE TITLE
OT.connect() fails, and I see a blank screen.

### ISSUE THREAD

**Issue by spyshower** [opentok/opentok-react-native#454]
# Bug Report

**Current behavior**
I see nothing in the screen. The module fails at `OT.connect()` in `OTSession.js`.

**Steps to reproduce**
Add the basic example code provided in the repo alongside with `token`, `sessionId` and `apiKey`.

The following doesn't work:
 
```
import { OTSession, OTPublisher, OTSubscriber } from 'opentok-react-native'

<OTSession
        apiKey='xxx'
        sessionId='yyy'
        token='zzz'
      >

        <OTPublisher style={{ width: 100, height: 100 }} />
        <OTSubscriber style={{ width: 100, height: 100 }} />
      </OTSession>
```

**Comment by enricop89** [comment]
Did you enable camera permissions? https://github.com/opentok/opentok-react-native#installation Point 9

Are you able to repro with (samples)[https://github.com/opentok/opentok-react-native-samples/tree/master/BasicVideoChat]?

**Comment by spyshower** [comment]
> Did you enable camera permissions? https://github.com/opentok/opentok-react-native#installation Point 9

Forgot to mention that I only tested Android. And yes, I have approved camera permissions.

> Are you able to repro with (samples)[https://github.com/opentok/opentok-react-native-samples/tree/master
/BasicVideoChat]?

Will do so and reply back.

**Comment by spyshower** [comment]
@enricop89 The sample project works fine, although it uses RN 0.59.9 and I use 0.63.3. It also uses an older version of this package so I tried installing it too but had no luck.

I also tried linking - still doesn't work.

**Comment by enricop89** [comment]
@spyshower https://github.com/enricop89/multiparty-video-react-native try out this one please, it uses the latest RN and Opentok RN

**Comment by spyshower** [comment]
@enricop89 Turns out if was a token error; got to that conclusion from the logs in the new repo you pointed me at. Thank you for your help 👍
