### ISSUE TITLE
Android Screen Sharing changes

### ISSUE THREAD

**Issue by rrnara** [opentok/opentok-react-native#457]
I have changes here which allow sharing screen even when outside the app, it would be helpful if it is actually merged here instead. Can anyone review/merge it?

https://github.com/opentok/opentok-react-native/compare/master...rrnara:master

**Comment by enricop89** [comment]
@rrnara can you open a Pull Request please?

**Comment by rrnara** [comment]
I don't seem to have permissions to push to a branch, which is why asking if someone can do it

**Comment by enricop89** [comment]
You need to fork the repo and push the branch :) Instructions here: https://github.com/opentok/opentok-react-native/blob/master/CONTRIBUTING.md

**Comment by rrnara** [comment]
Thanks, created a PR here: https://github.com/opentok/opentok-react-native/pull/458
