### ISSUE TITLE
Change Audio/Video Subscription for Publisher and Subscriber

### ISSUE THREAD

**Issue by RockinGarg** [opentok/opentok-react-native#459]
How to update below property on RUNTIME

```
publishVideo: false,
publishAudio: false
subscribeToVideo: true,
subscribeToAudio: true
```

I looked at issues but couldn't find any Proper Solution for this.

I tried changing **OTPublisher** _properties_ field and also _streamProperties_ but none worked

I even passed static values to those 4 nothing worked

NOTE: using iOS Simulator 

I am not using Any native code all in react-native.

This works well if I pass true/false while initialising OTPublisher after if I update it doesn't work

Needed:
Start and stop Publishing Audio or video on button press

UPDATE:

Tested on real device also:
audio publish is not getting stooped for publisher. Help

**Comment by enricop89** [comment]
if the properties are in the React state and you call `setState`, the props are updated. 
Please check here a working example: https://github.com/enricop89/multiparty-video-react-native/blob/master/App.js#L112

```
this.state = {
      subscriberIds: [], // Array for storing subscribers
      localPublishAudio: true, // Local Audio state
      localPublishVideo: true, // Local Video state
};

this.publisherProperties = {
      publishAudio: true,
    };

  toggleAudio = () => {
    let publishAudio = this.state.localPublishAudio;
    this.publisherProperties = { ...this.publisherProperties, publishAudio: !publishAudio };
    this.setState({
      localPublishAudio: !publishAudio,
    });
  };


<OTPublisher
  properties={this.publisherProperties}
  eventHandlers={this.publisherEventHandlers}
  style={styles.publisherStyle}
/>

```

**Comment by RockinGarg** [comment]
I have done same @enricop89 

here are my properties
```
constructor(props) {
        super(props)
        this.state = ({
            publisherProperties: {
                publishVideo: true,
                publishAudio: true,
                cameraPosition: 'front'
            },
            streamProperties: {}
        })
    }
```

This is how I toggle
```
setVolumeOnOff() {
        const currentStatus = this.state.publisherProperties.publishAudio
        var currentProperty = this.state.publisherProperties
        currentProperty.publishAudio = !currentStatus
        
        this.publisherPropertiesOne.publishAudio = !currentStatus
        console.log('being updated for audio: ', this.publisherPropertiesOne)
        this.setState({
            publisherProperties: currentProperty
        })
    }
```

after setState `Render()` function is called I also added `console.log` statement in `render` function and also verified value of `publishAudio` is changed

I have created different React.component for publisher and subscriber and just call on main screen like below.

               ```
<OTSession
                    style={{ width: '100%', height: '100%'}}
                    apiKey={this.state.apiKey}
                    sessionId={this.state.sessionId}
                    token={this.state.token}
                    eventHandlers={this.sessionEventHandlers}
                >
                    <View style={styles.publisherSubscriberViewStyle}>
                        <OTPublisherView 
                            publisherProperties={this.state.publisherProperties} /// Unused just passing handled this in state of react.component
                        />
                    </View>
                    <View style={styles.publisherSubscriberViewStyle}>
                        <OTSubscriberView 
                            subscriberProperties={this.state.subscriberProperties}
                        />
                    </View>
                    </OTSession>
```

NOTE: `OTPublisherView and OTSubscriberView` I created those custom not using what is provided by default

**Comment by RockinGarg** [comment]
Updating Code Syntax and Formatting in sequence for readability

**Comment by enricop89** [comment]
@RockinGarg on your custom OTPublisher, I think you should use the `props.publisherProperties` (passed down by the main file) and not the state of the component.

```
<OTPublisher
     style={{ width: '100%', height: '100%' }}
     eventHandlers={this.publisherEventHandlers}
     properties={this.props.publisherProperties}
 />
```

**Comment by RockinGarg** [comment]
Does it means all the subscriber properties including stream properties and all publisher properties need to be controlled from same component where session is created. ?

**Comment by enricop89** [comment]
Absolutely not, but this is how React works. If you are changing the state of the parent component, to see the reflected changes in the child component, you need to use the props that you passed from the component. 

https://reactjs.org/docs/lifting-state-up.html

**Comment by RockinGarg** [comment]
> Absolutely not, but this is how React works. If you are changing the state of the parent component, to see the reflected changes in the child component, you need to use the props that you passed from the component.
> 
> https://reactjs.org/docs/lifting-state-up.html

Hi 
I did passed some property from parent to child but that’s unused from start
I’ve configured and initiated OTPunblisher in child class and called that in parent class. 
Parent class has OTSession and child has OTPublisher (setting and all properties are there only)

**Comment by RockinGarg** [comment]
Adding code for Details

import React from "react";
import { View, TouchableOpacity, Image, StyleSheet } from "react-native";
import PropTypes from 'prop-types';
import { OTSession, OTPublisher, OTSubscriber } from 'opentok-react-native'

const expandImage = require('../assets/images/expandView.png');
const volumeOnImage = require('../assets/images/volumeOn.png');
const volumeOffImage = require('../assets/images/volumeOff.png');
const videoOnImage = require('../assets/images/videoOn.png');
const videoOffImage = require('../assets/images/videoOff.png');

export default class OTPublisherView extends React.Component {
    constructor(props) {
        super(props)
        this.state = ({
            publisherProperties: {
                publishVideo: true,
                publishAudio: true,
                cameraPosition: 'front'
            },
            streamProperties: {}
        })
    }

    publisherEventHandlers = {
        streamCreated: event => {
            console.log("streamCreated publisher", event);
            const streamProperties = {...this.state.streamProperties, [event.streamId]: {
                publishAudio: false,
                publishVideo: false
              }};
              console.log('stream properties: ', streamProperties)
              this.setState({
                streamProperties: streamProperties
              })
        },
        streamDestroyed: event => {
            console.log("streamDestroyed", event);
        },
        error: event => {
            console.log("error", event);
        }
    };

    setVolumeOnOff() {
        const currentStatus = this.state.publisherProperties.publishAudio
        var currentProperty = this.state.publisherProperties
        currentProperty.publishAudio = !currentStatus
        console.log('being updated for audio: ', currentProperty)
        this.setState({
            publisherProperties: currentProperty
        })
    }

    setVideoOnOff() {
        const currentStatus = this.state.publisherProperties.publishVideo
        var currentProperty = this.state.publisherProperties
        currentProperty.publishVideo = !currentStatus
        console.log('being updated for video: ', currentProperty)
        this.setState({
            publisherProperties: currentProperty
        })
    }

    render() {
        console.log('data is rendered')
        const properties = this.state.publisherProperties
        return (
            <View style={{ width: '100%', height: '100%' }}>
                <OTPublisher
                    style={{ width: '100%', height: '100%' }}
                    eventHandlers={this.publisherEventHandlers}
                    properties={this.state.publisherProperties}
                />
                <View style={styles.settingButtonsBaseViewStyle}>
                    <TouchableOpacity>
                        <Image source={expandImage} style={styles.internalButtonImageStyle} />
                    </TouchableOpacity>
                    <TouchableOpacity
                        onPress={this.setVolumeOnOff.bind(this)}
                    >
                        <Image
                            source={properties.publishAudio ? (volumeOnImage) : (volumeOffImage)}
                            style={styles.internalButtonImageStyle}
                        />
                    </TouchableOpacity>
                    <TouchableOpacity
                        onPress={this.setVideoOnOff.bind(this)}
                    >
                        <Image
                            source={properties.publishVideo ? (videoOnImage) : (videoOffImage)}
                            style={styles.internalButtonImageStyle}
                        />
                    </TouchableOpacity>
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    settingButtonsBaseViewStyle: {
        position: 'absolute',
        marginLeft: 0,
        width: '100%',
        marginLeft: 10,
        height: 60,
        bottom: 0,
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row'
    },
    internalButtonImageStyle: {
        resizeMode: 'contain',
        width: 40,
        height: 40
    },
})

OTPublisherView.propTypes = {
    publisherProperties: PropTypes.object.isRequired
};

**Comment by RockinGarg** [comment]
I even moved OTPublisher out of my custom class
still I got same output
Audio doesn't get stop publishing 

```
    <OTSession
                    style={{ width: '100%', height: '100%'}}
                    apiKey={this.state.apiKey}
                    sessionId={this.state.sessionId}
                    token={this.state.token}
                    eventHandlers={this.sessionEventHandlers}
                >
                    <View style={styles.publisherSubscriberViewStyle}>
                        {/* <OTPublisherView 
                            publisherProperties={this.state.publisherProperties}
                        /> */}
                            <OTPublisher
                                style={{ width: '100%', height: '100%' }}
                                eventHandlers={this.publisherEventHandlers}
                                properties={this.state.publisherProperties}
                            />
                    </View>
                    <View style={styles.publisherSubscriberViewStyle}>
                        <OTSubscriberView 
                            subscriberProperties={this.state.subscriberProperties}
                        />
                    </View>
                    </OTSession>
```

**Comment by RockinGarg** [comment]
@enricop89

**Comment by avinashyalgonde** [comment]
So far I tried this and worked for me.

const handleSetAudio = () => {
    console.log('Audio change', audio);
    setAudio(!audio);
  };

  const handleSetVideo = () => {
    console.log('Video change', video);
    setVideo(!video);
  };

<OTPublisher style={{ width: width, height: height, position: 'relative' }}
                  properties={{
                    audioTrack: audio,
                    videoTrack: video,
                    publishAudio: audio, 
                    publishVideo: video,
                  }}
                  handleSetAudio={handleSetAudio}
                  handleSetVideo={handleSetVideo}
                />

**Comment by rohit-32** [comment]
> I even moved OTPublisher out of my custom class
> still I got same output
> Audio doesn't get stop publishing
> 
> ```
>     <OTSession
>                     style={{ width: '100%', height: '100%'}}
>                     apiKey={this.state.apiKey}
>                     sessionId={this.state.sessionId}
>                     token={this.state.token}
>                     eventHandlers={this.sessionEventHandlers}
>                 >
>                     <View style={styles.publisherSubscriberViewStyle}>
>                         {/* <OTPublisherView 
>                             publisherProperties={this.state.publisherProperties}
>                         /> */}
>                             <OTPublisher
>                                 style={{ width: '100%', height: '100%' }}
>                                 eventHandlers={this.publisherEventHandlers}
>                                 properties={this.state.publisherProperties}
>                             />
>                     </View>
>                     <View style={styles.publisherSubscriberViewStyle}>
>                         <OTSubscriberView 
>                             subscriberProperties={this.state.subscriberProperties}
>                         />
>                     </View>
>                     </OTSession>
> ```

This is not a bug with opentok but with the way react sets its props, so you will have to set the props using the spread operator `...
`
so your code
```
<OTPublisher
                    style={{ width: '100%', height: '100%' }}
                    eventHandlers={this.publisherEventHandlers}
                    properties={this.state.publisherProperties}
                />
```

becomes 
```
<OTPublisher
                    style={{ width: '100%', height: '100%' }}
                    eventHandlers={this.publisherEventHandlers}
                    properties={
                    {...this.state.publisherProperties}
                   }
                />
```
