### ISSUE TITLE
Network test

### ISSUE THREAD

**Issue by renanpupin** [opentok/opentok-react-native#46]
Is it possible to expose the functionality of connection testing between clients from native SDKs?

**Comment by msach22** [comment]
@renanpupin Could you please elaborate more on what you mean by connection testing? This library allows you to listen to all events such as the `audioNetworkStats` and the `videoNetworkStats`.

**Comment by renanpupin** [comment]
Exactly what I need. Thanks.

**Comment by msach22** [comment]
Happy to help @renanpupin!
I will create another issue where I will list out all of the events that you can listen to :)

**Comment by renanpupin** [comment]
Maybe we can specify this at documentation.
Thanks again.

**Comment by msach22** [comment]
@renanpupin Yup, exactly! I will add them as docs

**Comment by enricop89** [comment]
@renanpupin I added some sample code for the Network Test feature. You can check it out here: [https://github.com/nexmo-saleseng/opentok-react-native-samples/tree/feature.network-test-sample/OTNetworkTest](https://github.com/nexmo-saleseng/opentok-react-native-samples/tree/feature.network-test-sample/OTNetworkTest)

**Comment by renanpupin** [comment]
@pedro-cerdera
