### ISSUE TITLE
Android subscriber wrong video scaling from landscape publisher

### ISSUE THREAD

**Issue by Lemaro86** [opentok/opentok-react-native#460]
**Current behavior**
>  If I try to create session with 2 devices ios or android in landscape orientation and android with portrait orientation, in Android in portrait orientation I got about 2x scaling video. But it would be cool if I'll get video without scale. If I try it reproduce with android in landscape and ios in portrait all works fine.

**Steps to reproduce**
> My config: 
`
...otherProps,
publisherProps: {
				audioBitrate: 40000, 
				audioFallbackEnabled: true, 
				audioTrack: true, 
				videoTrack: true, 
				videoSource: 'camera', 
				cameraPosition: 'front', 
				frameRate: 30, 
				name: '', 
				publishAudio: false, 
				publishVideo: false, 
				resolution: '1280x720', 
			},
			subscriberProps: {
				subscribeToAudio: true,
				subscribeToVideo: true,
			},`

**What is the current *bug* behavior?**
> Wrong scale for video in OTSubscriber in android. Devices: Xiaomi Redmi 6, Redmi Note 9, iPhone 7.

**What is the expected *correct* behavior?**
> I expected video without scale, like as in ios.

**Logs**
> Subscriber connected {"stream": {"connection": {"connectionId": "***", "creationTime": "Thu Nov 26 14:47:23 GMT+03:00 2020", "data": "user_id=*|room_id=*****"}, "connectionId": "****", "creationTime": "Thu Nov 26 14:47:23 GMT+03:00 2020", "hasAudio": true, "hasVideo": true, "height": 1280, "name": "", "sessionId": "*****", "streamId": "*", "videoType": "camera", "width": 720}}
 LOG  currentOrientationDimensions--------- {"height": 720, "width": 360}
 LOG  Publisher stream created! {"connection": {"connectionId": "***", "creationTime": "Thu Nov 26 14:47:26 GMT+03:00 2020", "data": "user_id=*|room_id=*****"}, "connectionId": "******", "creationTime": "Thu Nov 26 14:47:26 GMT+03:00 2020", "hasAudio": true, "hasVideo": true, "height": 640, "name": "", "sessionId": "***", "streamId": "*****", "videoType": "camera", "width": 480}
 LOG  streamPropertyChanged {"changedProperty": "videoDimensions", "newValue": {"height": 720, "width": 1280}, "oldValue": {"height": 1280, "width": 720}, "stream": {"connection": {"connectionId": "****", "creationTime": "Thu Nov 26 14:47:23 GMT+03:00 2020", "data": "user_id=***|room_id=****"}, "connectionId": "****", "creationTime": "Thu Nov 26 14:47:23 GMT+03:00 2020", "hasAudio": true, "hasVideo": true, "height": 720, "name": "", "sessionId": "****", "streamId": "****", "videoType": "camera", "width": 1280}}
 LOG  currentOrientationDimensions--------- {"height": 720, "width": 360}

P.S. As you can see in logs, if I rotate iPhone to landscape I got width: 1280, and android try to put it to container width: 360px. Btw if i use iPhone in portrait orientation all looks good.

**Comment by Lemaro86** [comment]
If I'll change resolution to 640*480 it can be fixed, but it's bad idea for me and my project.

**Comment by christophby** [comment]
@Lemaro86 did you find another fix?

**Comment by Lemaro86** [comment]
> @Lemaro86 did you find another fix?

No, It hasn't fixed yet

**Comment by abdulajet** [comment]
Thanks for the issue, since it has been a while since it has been posted, can you check out the latest version of the library, and if your issue has not been resolved please reopen/create a new issue.
