### ISSUE TITLE
we have implement voice call using opentok in backend and mobile app both, mobile to mobile and web to web voice call working fine, but in mobile to web voice not heard in web.

### ISSUE THREAD

**Issue by team3rddigital** [opentok/opentok-react-native#467]
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by abdulajet** [comment]
Hey can you post a project/follow the issue template please https://github.com/opentok/opentok-react-native/tree/main/.github/ISSUE_TEMPLATE
