### ISSUE TITLE
Create a list of all events this library supports

### ISSUE THREAD

**Issue by msach22** [opentok/opentok-react-native#47]
Create documentation on all of the events this library supports

**Comment by renanpupin** [comment]
@msach22 could you check if videoNetworkStats event is working properly?
![captura de tela 2018-04-25 as 11 24 49](https://user-images.githubusercontent.com/8743530/39252136-5c100086-487b-11e8-9a82-964ea4c5043e.png)

**Comment by renanpupin** [comment]
I have check on iOS and android, on android the videoNetworkStats works perfect, but on iOS it is not working.

**Comment by msach22** [comment]
@renanpupin Since this issue is not about the docs, I've created a separate issue: https://github.com/opentok/opentok-react-native/issues/50

**Comment by msach22** [comment]
added with `0.6.0`
