### ISSUE TITLE
Please update package.josn with new axios version 

### ISSUE THREAD

**Issue by sumeet07** [opentok/opentok-react-native#471]
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

Currently package is dependent on "axios": "^0.19.0" which has high security vulnerability. Please update to version "0.21.1"
---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by abdulajet** [comment]
Thanks for the contribution, solved this issue in 0.17.0
