### ISSUE TITLE
Contain whole video in SubscriberView (vs. zoom to fit)

### ISSUE THREAD

**Issue by deermichel** [opentok/opentok-react-native#472]
Is there a way to set the SubscriberView's display mode to contain the whole video (potentially with black bars) rather than zoom it to cover the view area? Currently, we loose content at the edges of the video when publishing a 3:4 stream to a 9:16 subscriber (we use fullscreen views in our application, this is a problem especially when mixing portrait & landscape streams). If this behaviour cannot be achieved by the library itself, is there a simple flag in the native SDKs which can be passed through? Thanks 🎉

**Comment by deermichel** [comment]
Ok, i figured out that the native SDKs for iOS and Android offer a property to change the view scale behavior. I'll try to create a PR with the property passed through to the RN components.

**Comment by deermichel** [comment]
PR is up: https://github.com/opentok/opentok-react-native/pull/474.

**Comment by tahagates97** [comment]
Hey @deermichel I'm facing exact issue on title rn. Can you provide more information about this idk what is PR and how to use it?
