### ISSUE TITLE
Video behaving disturbingly in split screen mode on iPad

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-react-native#475]
# Feature Request

**Description**
I use opentok-react-native in my application and it works fine. 

On iOS when entering background, the sound keeps on being played but the video is not published anymore. 
This is specially disturbing when using the split screen mode on iPad because in this case you see the application but the video may not be working if the application is not the active one.

I'd be glad to make a PR to improve this behavior but I did not find from where to start and even don't know if it is possible to keep on capturing the camera when app is in background so if you have any clues on where to start, maybe I could give it a try

**Comment by abdulajet** [comment]
Seen to be a limitation from iOS https://developer.apple.com/documentation/avfoundation/avcapturesessioninterruptionreason/avcapturesessioninterruptionreasonvideodevicenotavailablewithmultipleforegroundapps?language=objc
