### ISSUE TITLE
Lots of warnings in build for latest OpenTok pod (2.19.0)

### ISSUE THREAD

**Issue by sruli** [opentok/opentok-react-native#476]
# Bug Report

**Current behavior**
> Since updating to latest OpenTok pod (2.19.0), I've been seeing over 1K warnings in my build

**Steps to reproduce**
> Go to [BasicVideoChat example Podfile](https://github.com/opentok/opentok-react-native-samples/blob/master/BasicVideoChat/ios/Podfile) and set `pod 'OpenTok', '2.19.0`'. Build the app in Xcode.

**Example Project**
> Reproduced in the [opentok react native samples BasicVideoChat](https://github.com/opentok/opentok-react-native-samples/blob/master/BasicVideoChat) example

**What is the current *bug* behavior?**
> When I build the app, either via Xcode or the command line (`npm run ios`) I see many warnings like this: 
```
Direct access in function 'webrtc::FlexfecReceiveStreamImpl::FlexfecReceiveStreamImpl(webrtc::Clock*, webrtc::RtpStreamReceiverControllerInterface*, webrtc::FlexfecReceiveStream::Config const&, webrtc::RecoveredPacketReceiver*, webrtc::RtcpRttStats*, webrtc::ProcessThread*)' from file '/Users/sethrapps/Projects/opentok-react-native-samples/BasicVideoChat/ios/Pods/OpenTok/OpenTok.framework/OpenTok(OpenTok-x86_64-master.o)' to global weak symbol 'void rtc::webrtc_logging_impl::LogStreamer<>::Call<rtc::webrtc_logging_impl::Val<(rtc::webrtc_logging_impl::LogArgType)13, rtc::webrtc_logging_impl::LogMetadata>, rtc::webrtc_logging_impl::Val<(rtc::webrtc_logging_impl::LogArgType)9, char const*> >(rtc::webrtc_logging_impl::Val<(rtc::webrtc_logging_impl::LogArgType)13, rtc::webrtc_logging_impl::LogMetadata> const&, rtc::webrtc_logging_impl::Val<(rtc::webrtc_logging_impl::LogArgType)9, char const*> const&)::t' from file '/Users/sethrapps/Projects/opentok-react-native-samples/BasicVideoChat/ios/Pods/OpenTok/OpenTok.framework/OpenTok(OpenTok-x86_64-master.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

**What is the expected *correct* behavior?**
> These warnings should not appear. I did not notice them on 2.18.1 or 2.17.1.

**Relevant logs and/or screenshots**
> Pasted above ^^

**Comment by sruli** [comment]
I was asked to include crash reports that may be related. Here are examples:
https://gist.github.com/sruli/c7e66564a39127a074270fdd4696f049
https://gist.github.com/sruli/3989d5550b98c55789032d1399ab821d

**Comment by enricop89** [comment]
@sruli thank you for filing the issue. The target is to fix it on the next version release 👍

**Comment by sruli** [comment]
Awesome thank you 🙏
