### ISSUE TITLE
sometimes camera and microphone don't seem to work when connecting to a session

### ISSUE THREAD

**Issue by xXDeonoXx** [opentok/opentok-react-native#479]
when connecting to a Session sometimes this problem happen, the only way to "fix" that is disconnecting and connecting again to the Session, i've implemented the error and otrnerror events in all 3 OT pieces and any of them have caught any error or exception.

in [this video](https://streamable.com/ooajlv) you can see it is already connected but had to go back and reconnect to have functional audio and video, any help or hint to help me solve the problem ?

[my VideoChat component code](https://pastebin.com/vn4iuRbq), we use Styled Components, the styles are [here](https://pastebin.com/E4yyGA6j)

[this](https://pastebin.com/cQzeP0mP) is how i create the client token and return the session data to connect. The SessionId is pre created when a Schedule is generated, this i way we have a guarantee that sessionId always exists.

Ejected Expo project with unimodules
react native 0.63.4
opentok-react-native 0.15.0

**Comment by enricop89** [comment]
@xXDeonoXx is it normal that there are not OTSession or OTPublisher component in the render function? 🤔 

Additionally, do you have clear steps to reproduce it? If so, can you try with https://github.com/opentok/opentok-react-native-samples?

**Comment by xXDeonoXx** [comment]
The OTSession and OTPublusher are in the styles, we use styled components to style the opentok components, you can check they [here](https://pastebin.com/E4yyGA6j) in my pastebin.

Container = OTSession
MyCamera = OTPublisher
Subscriber = OTSubscriber

> Additionally, do you have clear steps to reproduce it?

i wish we had, this problem is a little bit random, when me and my coworkers test it in dev enviroment, 1 in 40 chances of this problem happening, in production it seems to be more recurrent , no error log, no exception, nothing, the only way we could work around this problem is exiting and entering the call but that's not the solution. I'm trying to fix this issue or at least find out the reason this is happening, no success.

**Comment by abdulajet** [comment]
Can you check out the latest version of the library, and if your issue has not been resolved please reopen/create a new issue. Thanks
