### ISSUE TITLE
Can't use borderRadius on <OTPublisher> is there a way to do it?

### ISSUE THREAD

**Issue by davibarberini** [opentok/opentok-react-native#480]
I'm trying to have a rounded publisher view, but it seems like OT only ignores the style attribute.
Am i missing some kinda of way to do it? 

Ty

**Comment by cristian473** [comment]
+1

**Comment by hardikjs** [comment]
Same here i have given below style to the `OTPublisher` but borderRadius didn't applied to it.

```
publisherStyle: {
	position: 'absolute',
	top: 5,
	right: 5,
	zIndex: 5000,
	borderRadius: 10,
	borderWidth: 1
}
```

**Comment by KevMac19** [comment]
@davibarberini - Wrap your `OTPublisher` inside `View` and give styling to that `View` and also give `overflow:hidden` style to that
