### ISSUE TITLE
Audio shifted from Speaker to Handset automatically

### ISSUE THREAD

**Issue by Zydus001** [opentok/opentok-react-native#483]
I received a call during the VD call, declined the call, as soon as I went back to the VD call, the Audio shifted from Speaker to Handset automatically, so I had to leave & re-join the call. 

(I was not using earphones during the entire call)

**Comment by rktalusani** [comment]
@Zydus001 you are testing on iOS/iPad correct?

**Comment by Zydus001** [comment]
This is happening in mobile phone (iOS/Android).

**Comment by enricop89** [comment]
Close as the customer wasn't using react-native.
