### ISSUE TITLE
Screen sharing start/stop 

### ISSUE THREAD

**Issue by Zydus001** [opentok/opentok-react-native#484]
In RN application we are using opentok-react-native": "0.15.0" library. 

We are facing issue while we are sharing the screen and stop screen. Same issue reported by many people here: https://github.com/opentok/accelerator-sample-apps-ios/issues/15

**Comment by abdulajet** [comment]
hanks for the issue, since it has been a while since it has been posted, can you check out the latest version of the library, and if your issue has not been resolved please reopen/create a new issue. Thanks again

**Comment by RohitDhingra0786** [comment]
@abdulajet In RN application we are using opentok-react-native": "0.17.2" library.
