### ISSUE TITLE
OT undefined error

### ISSUE THREAD

**Issue by rogerarce** [opentok/opentok-react-native#49]
Having trouble today (cause yesterday this was working).
I'm not sure what's causing the error but this issue exists both on android emulator and android device.

![image](https://user-images.githubusercontent.com/37185501/39226883-d515e1a6-4887-11e8-865f-14a5dc716814.png)

and my package.json file

![image](https://user-images.githubusercontent.com/37185501/39227347-bba26dc2-488a-11e8-815a-1e1c9085422c.png)

**Comment by msach22** [comment]
@rogerarce Could you please confirm that you followed the Android instructions? You need to use `react-native link opentok-react-native` so you can link the Android Native Modules.

Could you please also share your code implementation?

**Comment by msach22** [comment]
@rogerarce Thanks for sharing, the code looks great. Could you please share your project and app `build.gradle` files.

**Comment by rogerarce** [comment]
![image](https://user-images.githubusercontent.com/37185501/39227757-0b47124a-488d-11e8-8253-2850dd1288f9.png)

my project is at bitbucket sorry, this is quite strange cause yesterday this was working fine

**Comment by msach22** [comment]
No problem @rogerarce. The project's build.gradle looks great, but can you also share the app module's `build.gradle`?

**Comment by rogerarce** [comment]
@msach22 I'm sorry where can I locate that?

**Comment by msach22** [comment]
You should be able to see it in Android Studio under `Gradle Scripts`

The highlighted one: https://cl.ly/2p0z3v1G3T2D

**Comment by rogerarce** [comment]
I'm not using Android Studio actually.

**Comment by msach22** [comment]
@rogerarce Is your app built with `create-react-native-app` or `react-native init` ? 
Please keep in mind that this library will not work with apps built with `create-react-native-app`. 
If it's built with `react-native init`, could you please re-run `react-native link opentok-react-native` to verify that the native modules have been linked.

**Comment by rogerarce** [comment]
@msach22  Yeah I've created my react native with `react-native init`. Okay sure I'll paste the result here. Thanks man for quick response, really appreciate it.

**Comment by rogerarce** [comment]
I've actually link this before but still here's the result 

![image](https://user-images.githubusercontent.com/37185501/39280809-fb00bcae-4933-11e8-81b3-4e4c4aca5ee3.png)

**Comment by rogerarce** [comment]
@msach22 Hi I think the problem was the client token I was using has expired on stale or something which was causing the issue thanks closing the ticket!

**Comment by msach22** [comment]
Happy to hear that it's working! Let me know if you have any questions!
