### ISSUE TITLE
Update native Android and iOS SDKs to 2.19.1?

### ISSUE THREAD

**Issue by sunweiyang** [opentok/opentok-react-native#494]
This package seems to be using the 2.18.1 Android and iOS SDKs from last October. 2.19.1 includes many significant improvements (performance, memory, and bug fixes), and opentok-react-native can benefit from them. Is it possible to bump the SDKs?

**Comment by enricop89** [comment]
`0.18.0` has been released and has 2.20.0 on iOS and 2.20.1 on Android.
