### ISSUE TITLE
videoNetworkStats on iOS is not showing the video network stats

### ISSUE THREAD

**Issue by msach22** [opentok/opentok-react-native#50]
![Issue](https://user-images.githubusercontent.com/8743530/39252136-5c100086-487b-11e8-9a82-964ea4c5043e.png)

Thanks @renanpupin for reporting

**Comment by msach22** [comment]
@renanpupin The fix should be going out in the 0.5.2 release

**Comment by msach22** [comment]
This has been fixed and released. Please use  `v0.5.2`.

**Comment by renanpupin** [comment]
I tested and approved that it is now working on iOS.
Thanks.
