### ISSUE TITLE
Can we have earpiece option available for audio output source?

### ISSUE THREAD

**Issue by chaawlaapooja** [opentok/opentok-react-native#500]
# Feature Request

**Description**
> (Include problem, use cases, benefits, and/or goals)
Problem : No support for earpiece option

Goal: I am using opentok-react-native in my project and my goal is to allow the user to use phone(earpiece), speaker and bluetooth options. 

Use case: If someone needs to have privacy while streaming for audio-only calls, there can be two things to achieve that - earpiece or headphones. For instance, if the headphones are not charged or are not available for some other, we need to give the user the option to switch to phone(earpiece mode)

**Proposal**
I see opentok-react-native is using custom driver which is preventing me to switch to earpiece mode despite of trying many solutions and packages that force turn off the speaker. Is it possible to modify the audio driver so that it can support earpiece option. Additionally I tried implementing airplay to check for phone and speaker but that doesn't seem to pick both options because of the limitation we have for audio sources.

**Links / references**
Image of available options shown by airplay in opentok-react-native
![image](https://user-images.githubusercontent.com/26603297/116806103-7bec2280-ab48-11eb-95c8-14b656413ff7.png)

**Comment by enricop89** [comment]
Duplicate #159
