### ISSUE TITLE
Crash with latest version 17.2 (can't find uuid/v4)

### ISSUE THREAD

**Issue by JB-CHAUVIN** [opentok/opentok-react-native#511]
I can use the latest version because of this error : 

error: Error: Unable to resolve module uuid/v4 from XXXX/Maiia/Mobile/maiia-mobile-develop/node_modules/opentok-react-native/src/OTPublisher.js: uuid/v4 could not be found within the project or in these directories:
  node_modules/opentok-react-native/node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  10 | import OTContext from './contexts/OTContext';
  11 |
> 12 | const uuid = require('uuid/v4');

**Comment by enricop89** [comment]
This is fixed on `0.18.0`
