### ISSUE TITLE
Crash when starting a publisher

### ISSUE THREAD

**Issue by JB-CHAUVIN** [opentok/opentok-react-native#512]
crypto.getRandomValues() not supported

With latest version 1.17.2...

![image](https://user-images.githubusercontent.com/8957878/120212338-25026780-c232-11eb-8d2e-45ed4a50b02a.png)

**Comment by abdulajet** [comment]
Hey can you share a sample project with this breaking? I haven't been able to reproduce with the sample apps running 0.17.2, same for #511

**Comment by enricop89** [comment]
This is fixed on `0.18.0`
