### ISSUE TITLE
Black screen when subscriber turn off video

### ISSUE THREAD

**Issue by hardikjs** [opentok/opentok-react-native#518]
# Bug Report

**Current behavior**
> Shows black screen when subscriber video is turned off.
> If i try to show custom view above subscriber using position and zIndex that's also not working.

- The code i followed is from [here](https://github.com/enricop89/multiparty-video-react-native)
- Version i am using is 0.17.2 of opentok-react-native
- React-Native: 0.63.4

**Steps to reproduce**
> Turn of subscriber video and and keep only audio.

**What is the current *bug* behavior?**
> Shows black screen when subscriber turn off his/her video.

**What is the expected *correct* behavior?**
> Instead of black screen would like to show user placeholder.

**Relevant logs and/or screenshots**
(![Screenshot 2021-06-20 220952](https://user-images.githubusercontent.com/33776753/122683127-f406c880-d21a-11eb-9520-427fbe5ca923.png)

**Comment by enricop89** [comment]
@hardikjs you should be able to do it using `onVideoDisabled` on the subscriber object.

**Comment by hardikjs** [comment]
I am closing this issue as I am able to solve it now with some efforts.

If someone has to do it in future then please refer my below solution because i don't think there is another way to do it.

```
<View style={styles.fullView} activeOpacity={1}>
	<OTSubscriberView
		streamId={subscribersList[0]}
		key={subscribersList[0]}
		style={{width: '100%', height: '100%', zIndex: 1}}
	/>
	{
		subscriberVideoDisabled && (
			<View
				style={{
					width: '100%',
					height: '100%',
					zIndex: 2,
					backgroundColor: AppTheme.colors.white,
					position: 'absolute',
					top: 0,
					bottom: 0,
					display: 'flex',
					alignSelf: 'center',
					justifyContent: 'center'
				}}
			>
				<Image source={Images.avtar} style={styles.placeholderImage} />
			</View>
		)
	}
</View>
```

**Comment by elie-chaaban** [comment]
videoEnabled or videoDisbaled in not workign


const subscriberEventHandlers = {
    connected: () => {
      console.log('[subscriberEventHandlers - connected]');
    },
    disconnected: () => {
      console.log('[subscriberEventHandlers - disconnected]');
    },
    error: (error) => {
      console.log('subscriberEventHandlers error:', error);
    },
    videoEnabled: (ev) => {
      console.log(ev);
    }
  };
        <OTSubscriber style={{ height: hp(100), width: wp(100) }} subscriberEventHandlers={subscriberEventHandlers} />
