### ISSUE TITLE
React native mavel is not forbidden so project not run

### ISSUE THREAD

**Issue by hgvansh** [opentok/opentok-react-native#526]
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by enricop89** [comment]
Duplicate #527
