### ISSUE TITLE
enableStereoOutput is a required type despite having a default value on OTSessionSessionOptions

### ISSUE THREAD

**Issue by chrisbruford** [opentok/opentok-react-native#531]
# Bug Report

**Current behavior**
> (Summarize the bug encountered concisely)

As per title; TypeScript gives type error `Property 'enableStereoOutput' is missing in type '{}' but required in type 'OTSessionSessionOptions'` despite having a default as [per documents here](https://github.com/opentok/opentok-react-native/blob/86ecf2f796ec67819dd133080006ba65fdc1c26c/docs/OTSession.md#setting-session-options)

**Steps to reproduce**
> (How one can reproduce the issue - this is very important)

Create an OTSession type passing in an empty object to options prop

**What is the current *bug* behavior?**
> (What actually happens)

As above

**What is the expected *correct* behavior?**
> (What you should see instead)

Either documents should not imply a default, or the prop should be updated to accept no value

**Relevant logs and/or screenshots**
> (Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

**Comment by t4ngth00** [comment]
It was a typing issue so you can either set a default value for "enableStereoOutput" key in your implementation of OTSessionSessionOptions object. Another way would be using [patch-package](https://www.npmjs.com/package/patch-package) to create a patch which make [enableStereoOutput]((https://github.com/opentok/opentok-react-native/blob/main/%40types/index.d.ts#L130) optional like that `enableStereoOutput?: boolean;`

**Comment by chrisbruford** [comment]
Indeed - we set to the default (false) to get around this. Would just be nice if the typings didn't force us to put this extrenuous property

**Comment by enricop89** [comment]
This will be fixed #542
