### ISSUE TITLE
On Android audio output doesn't seem to be correctly released after a call. 

### ISSUE THREAD

**Issue by Alan-Billi** [opentok/opentok-react-native#532]
# Bug Report

**Current behavior**
When disconnecting from a video call we've noticed that on Android the Audio output seems affected.
If we Play some music from an other app right after the call, the overall source seems in a low quality mode.
Like if our app modified the phone global audio behavior.

Does someone already experienced this?

We're running the last version of the module.
No issues on iOS.

Thanks

**Comment by abdulajet** [comment]
Thanks for the issue, can you please try the latest version of the library which includes updates to the underlying Android and iOS native SDKs. If the issue persists please reopen this issue or create a new one.
