### ISSUE TITLE
Camera not turning off after the publisher stream is destroyed

### ISSUE THREAD

**Issue by devevignesh** [opentok/opentok-react-native#535]
# Bug Report

**Current behavior**
The issue is that after the internet connection is lost and the publisher stream destroyed, the camera is turned on

**Steps to reproduce**
1.  Session connected
2. Publisher stream created
3. Turn of mobile internet 
4. Session reconnecting
5. Publisher stream destroyed (Here the microphone is turned off but the camera is *not*)
6. Session error due to a lost internet connection (ConnectionDropped)
7. Session disconnected

**Example Project**
[BasicVideoChat](https://github.com/opentok/opentok-react-native-samples/tree/main/BasicVideoChat)

**What is the current *bug* behavior?**
When the publisher stream is destroyed due to a lost internet connection the camera is turned on

**What is the expected *correct* behavior?**
If the publisher stream is destroyed due to a lost internet connection it should destroy or turn off the camera (like how it is working for microphone access)

**Comment by abdulajet** [comment]
Thanks for the issue, can you please try the latest version of the library which includes updates to the underlying Android and iOS native SDKs. If the issue persists please reopen this issue or create a new one.
