### ISSUE TITLE
How to reconnect to session, if session is already ended. 

### ISSUE THREAD

**Issue by usamatekrowe** [opentok/opentok-react-native#538]
I want to know how to rejoin the call if one user already ends the call intentionally or by any other means.

Actually, when the screen loads the first time it mounts components and joins to the session but I did not find any way to re-join the call.

**Comment by moficodes** [comment]
hey @usamatekrowe 

If i understand your problem correctly, you want to connect to the same session if you get disconnected. 

You can look at this example on how to do that

https://github.com/enricop89/multiparty-video-react-native

Basically you want to connect to the call with same sessionid and you should be able to rejoin.
