### ISSUE TITLE
Add audioNetworkStats and videoNetworkStats event for Publisher

### ISSUE THREAD

**Issue by hussainsherwani** [opentok/opentok-react-native#539]
# Feature Request

**Description**
with these two events we can handle the video and and audio call quality with help of packet lost information, I want to convert video call to audio if there packet lost issue at publisher end,  there is already video to audio fallback mechanism, but it convert audio lately in a very low network bandwidth.

**Proposal**
like subscriber we have audio and video network stats there should also be for publisher 
**Links / references**
https://tokbox.com/developer/sdks/android/reference/com/opentok/android/PublisherKit.AudioStatsListener.html
https://tokbox.com/developer/sdks/android/reference/com/opentok/android/PublisherKit.html#videoStatsListener

**Comment by danieljcorreac** [comment]
Is it planned to add this functionality? We need it to indicate the quality of the connection.

**Comment by jeffswartz** [comment]
We will add this functionality with this PR (which is under review): https://github.com/opentok/opentok-react-native/pull/668.

**Comment by marinaserranomontes** [comment]
Hi @hussainsherwani @danieljcorreac, 

FYI, RTCStats info added in v2.25.3:

- OTPublisher `audioNetworkStats` and `videoNetworkStats` events
- `OTPublisher.getRtcStatsReport()` method and OTPublisher `rtcStatsReport` event


Thanks.
