### ISSUE TITLE
OT.connect error RN 0.63.3

### ISSUE THREAD

**Issue by gonzalormonja** [opentok/opentok-react-native#551]
# Bug Report

**Current behavior**
When using the <OTSession> component, the application stops and generates an error that returns on screen: customsServers. In sessionEventHandlers the callback otrnError is triggered with the text "error connecting to session. The native instance of the session could not be found".

**Steps to reproduce**
create a react native application using "npx react-native init videoChat2 --version 0.63.3 and then install opentok-react-native" following the steps in the installation guide. Initialize <OTSession> and generate error

**What is the expected *correct* behavior?**
The expected behavior is like in the RN 0.66 version, where following the same steps it generates correctly the session (with the same credentials apiKey, token and sessionId) and I can establish a video call.

**Relevant logs and/or screenshots**
![image](https://user-images.githubusercontent.com/48839385/140357151-4c4497dc-9814-41d8-830f-323052a55e2e.png)

build.gradle
`  

buildscript {
      ext {
          buildToolsVersion = "29.0.3"
          minSdkVersion = 24
          compileSdkVersion = 29
          targetSdkVersion = 29
      }
      repositories {
          google()
          jcenter()
      }
      dependencies {
          classpath("com.android.tools.build:gradle:3.5.3")
          // NOTE: Do not place your application dependencies here; they belong
          // in the individual module build.gradle files
      }
  }
  
  allprojects {
      repositories {
          mavenLocal()
          maven {
              // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
              url("$rootDir/../node_modules/react-native/android")
          }
          maven {
              // Android JSC is installed from npm
              url("$rootDir/../node_modules/jsc-android/dist")
          }
          google()
          jcenter()
          maven { url 'https://www.jitpack.io' }
          maven {
              url "http://tokbox.bintray.com/maven"
          }
      }
  }

`

PD: when requesting permissions, the application closes in RN 0.63.3 but not in 0.66

PD: Sorry for my English, I used a translator to improve it as much as possible.

**Comment by enricop89** [comment]
Is this happening only with RN `0.63.3`? I believe it's something related to the latest release. A quick fix is to downgrade opentok-react-native to `0.18.0`

**Comment by gonzalormonja** [comment]
I tried but to no avail.

It only happens with version 0.63.3, is the version that I have my apps. Later versions work great.

**Comment by FreshWebCoder** [comment]
I faced same issue, and I had to pass empty array to the `customServers` options.

```
<OTSession
  apiKey="your-api-key"
  sessionId="session-id"
  token="token"
  options={{
    iceConfig:{
      transportPolicy: 'all', // Valid options are 'all' or 'relay'. Default is 'all'
      includeServers: 'all', // Valid options are 'all' or 'custom'. Default is 'all'
      customServers: [],
    },
  }}
>
```
