### ISSUE TITLE
`SIGABRT` when `OTSubscriberView` is used with `Animated.View`

### ISSUE THREAD

**Issue by fabien0102** [opentok/opentok-react-native#554]
# Bug Report

**Current behavior**
Combined with `Animated.View` from `react-native`, I have a `SIGABRT` error on opentok-react-native

This is blocking me to have some feedback animation for the `audioLevel` around of the stream (as in zoom for example)

**Steps to reproduce**
```tsx
  <OTSession {...sessionProps}>
    <OTSubscriber>
      {(streamIds: string[]) => {
        return streamIds.map((streamId) => {
          return (
            <Animated.View key={streamId}>
              <OTSubscriberView streamId={streamId} />
            </Animated.View>
          );
        });
      }}
    </OTSubscriber>
  </OTSession>
);
```

**What is the current *bug* behavior?**
XCode is crashing

**What is the expected *correct* behavior?**
I’m expecting to be able to wrap the `OTSubscriberView` with `Animated.View` without having everything crashing.

**Relevant logs and/or screenshots**
![image](https://user-images.githubusercontent.com/1761469/143027873-a5d3b395-5059-486e-899f-b8c7feec488c.png)

**Comment by abdulajet** [comment]
Thanks for the issue, can you please try the latest version of the library which includes updates to the underlying Android and iOS native SDKs. If the issue persists please reopen this issue or create a new one.
