### ISSUE TITLE
Bad Gateway (android app crash)

### ISSUE THREAD

**Issue by KiranRadish** [opentok/opentok-react-native#557]
# Bug Report

**Current behavior**
> (Summarize the bug encountered concisely)

Not able to run application
App getting crashed on android

**Steps to reproduce**
> (How one can reproduce the issue - this is very important)
on android click join call it will crash

**Example Project**
> (If possible, please create an example project here on GitHub.com that exhibits the problematic behaviour, and link to it here in the bug report)

**What is the current *bug* behavior?**
> (What actually happens)
crash

**What is the expected *correct* behavior?**
> (What you should see instead)
it should not crash

**Relevant logs and/or screenshots**
> (Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

http://tokbox.bintray.com/maven/com/facebook/react/react-native/maven-metadata.xml

502 bad gateway

**Comment by nishanth-saka** [comment]
same issue!

**Comment by SrinuCape** [comment]
same issue!

**Comment by 15110011** [comment]
tokbox server is dead?

**Comment by nishanth-saka** [comment]
bintray is dead!

**Comment by enricop89** [comment]
https://github.com/opentok/opentok-react-native/issues/527

**Comment by Lexical-Luke** [comment]
Jcenter and bintray are dead. Suggestions appreciated.

![Screenshot 2021-12-10 at 9 53 35 AM](https://user-images.githubusercontent.com/6750242/145553837-d625758b-c22c-4bdf-8a3f-9f37055fd2d6.png)

**Comment by vijayrit22** [comment]
i am also having the same issue anyone having solution please update. Thankyou.

**Comment by enricop89** [comment]
Which version of `opentok-react-native` are you using?

**Comment by Lexical-Luke** [comment]
@enricop89, I'm not even using `opentok-react-native`, I have issues with react-native itself due to bintray being down.

``
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://google.bintray.com/flexbox-layout/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/flexbox-layout/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/flexbox-layout/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
``

**Comment by enricop89** [comment]
https://github.com/facebook/react-native/issues/32734#issue-1076799635

**Comment by Lexical-Luke** [comment]
@enricop89 https://github.com/facebook/react-native/issues/31165

**Comment by leah9227-arkus** [comment]
Guys, if you still have the bad gateway issue, you are gonna need to update the url with the new package domain. In my case the issue was related to this package:

https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp-bom/4.4.1/okhttp-bom-4.4.1.pom

So I updated the url from this:
http://tokbox.bintray.com/maven

to this:
https://repo1.maven.org/maven2

And the issue got corrected. Hopefully this is gonna help to anybody. Cheers.

**Comment by Lexical-Luke** [comment]
@leah9227-arkus, most unfortunately this did not solve it for me.

**Comment by GualbertoVannini** [comment]
> Guys, if you still have the bad gateway issue, you are gonna need to update the url with the new package domain. In my case the issue was related to this package:
> 
> https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp-bom/4.4.1/okhttp-bom-4.4.1.pom
> 
> So I updated the url from this: http://tokbox.bintray.com/maven
> 
> to this: https://repo1.maven.org/maven2
> 
> And the issue got corrected. Hopefully this is gonna help to anybody. Cheers.

OMG MAAAAAN Finally my project works again!

**Comment by leah9227-arkus** [comment]
@GualbertoVannini I'm happy you solved your issue 👍
