### ISSUE TITLE
Bintray sunset

### ISSUE THREAD

**Issue by bryanstevens314** [opentok/opentok-react-native#558]
Android installation step 4 in the read me says to add "http://tokbox.bintray.com/maven" as a maven dependency which throws a 502 in the browser & android studio when attempting to build.

https://status.bintray.com states that bintray has been sunset so not sure how to proceed, my existing react native android app no longer builds because of this. 

Looking online it sounds like it's possible to manually download and add the dependency to android studio but would prefer to stick with an existing workflow.

**Comment by GualbertoVannini** [comment]
Somebody can share a github repo as a substitute for `http://tokbox.bintray.com/maven`? 

Before realising this problem I also deleted all cached elements so I am not able to run a project anymore also in offline mode.

**Comment by bryanstevens314** [comment]
Replacing http://tokbox.bintray.com/maven with https://repo1.maven.org/maven2 as mentioned in @GualbertoVannini 's link fixed my issue and android builds are now working again. Thank you!

**Comment by enricop89** [comment]
I updated the sample app removing jCenter dependencies and adding mavenCentral. You can find [here](https://github.com/opentok/opentok-react-native-samples/blob/main/BasicVideoChat/android/build.gradle) a working example.

I am going to close the issue
