### ISSUE TITLE
How to access session capabilities object

### ISSUE THREAD

**Issue by vsk-pvr** [opentok/opentok-react-native#559]
Is there any way to get Capabilities object upon a successfull session creation? 

https://tokbox.com/developer/sdks/js/reference/Capabilities.html

**Comment by jeffswartz** [comment]
We will add this functionality with this PR (which is under review): https://github.com/opentok/opentok-react-native/pull/668.

**Comment by kapilmishr** [comment]
This functionality has been incorporated in [#668](https://github.com/opentok/opentok-react-native/pull/668) and released in react-native version [2.25.3 (September 2023)](https://github.com/opentok/opentok-react-native/blob/main/CHANGELOG.md#2253-september-2023). So, closing this issue.
