### ISSUE TITLE
iOS app crashs when reload on simulator

### ISSUE THREAD

**Issue by renanpupin** [opentok/opentok-react-native#56]
After start a call and try to refresh the simulator, the app crashs. I think is something related with application context.
On android it is not happening.

**Comment by msach22** [comment]
Thanks for reporting this @renanpupin! If you have a fix, please open up a PR, if not, I will investigate further!

**Comment by ythecombinator** [comment]
Haven't seen that issue here before, @msach22. Perhaps I was mistaken and this is really on the lib's side.

**Comment by renanpupin** [comment]
To simulate that bug, you must reload the simulator while the video is active.
I will ask a native mobile developer from my team to have a look at OpenTok context. I have seen this issue in another projects, if I am not mistaken, it is related with library context while RN uses Live Reload.

**Comment by msach22** [comment]
@renanpupin This should be fixed in 0.6.0

**Comment by msach22** [comment]
fixed with `0.6.0`
