### ISSUE TITLE
Opentok initialization crash on iOS 15

### ISSUE THREAD

**Issue by serzmerz** [opentok/opentok-react-native#561]
# Bug Report

**Current behavior**
There is broken behavior upon initializing opentok, using the latest react-native 0.66 and pod version 2.20.2.  
We receive a crash when opentok tries to initialize itself.  

**Steps to reproduce**
App crashes randomly in production and in e2e tests using detox

**What is the current *bug* behavior?**
Crash when initializing opentok

**What is the expected *correct* behavior?**
App not crash

**Relevant logs and/or screenshots**
![146770734-d8dec693-ac6d-4481-b56c-93761f4b2ebe](https://user-images.githubusercontent.com/24809641/149174530-e0c837a0-f1ed-4fb5-9605-be5a2e1110f1.png)

**Comment by enricop89** [comment]
Can you reproduce it with https://github.com/opentok/opentok-react-native-samples/blob/main/BasicVideoChat please?

**Comment by enricop89** [comment]
Please feel free to reopen the issue if it's reproducable

**Comment by wolfej94** [comment]
This is happening on the iOS SDK also, I'm not sure if it being reproducible is entirely relevant as it's literally crashing on the initialiser in iOS 15.

<img width="966" alt="Screenshot 2022-07-20 at 09 49 40" src="https://user-images.githubusercontent.com/56296015/179939878-f6fa3b4b-f0b0-4e4a-9d4b-826136335186.png">

**Comment by wolfej94** [comment]
Yes

**Comment by enricop89** [comment]
@wolfej94 can you provide steps to reproduce, please? We are not having any reports from customers about this crash, so if you could provide any pointers it would help a lot

**Comment by wolfej94** [comment]
I honestly don't have any steps, it happens intermittently on devices with iOS 15+ and this is the stack at the time of crashing and it throws an unhandled exception.

![](https://user-images.githubusercontent.com/56296015/179939878-f6fa3b4b-f0b0-4e4a-9d4b-826136335186.png)

**Comment by wolfej94** [comment]
@enricop89 can you confirm if someone is looking into this please?

**Comment by enricop89** [comment]
@wolfej94 can you open a ticket at support@tokbox.com please?

**Comment by enricop89** [comment]
This should be fixed with the new version `0.21.1`
