### ISSUE TITLE
app audio gets lost after declining an incoming phone call

### ISSUE THREAD

**Issue by gautammukoo** [opentok/opentok-react-native#562]
Commenting to update the opentok-react-native version compatible to Vonage Video API iOS SDK --> Version 2.21.3

This version fixes an issue where app audio gets lost after declining an incoming phone call.

please refer --> https://tokbox.com/developer/sdks/ios/release-notes.html

**Comment by gautammukoo** [comment]
@abdulajet

**Comment by enricop89** [comment]
It's fixed on the latest version of the library
