### ISSUE TITLE
Does opentok-react-native work with Expo?

### ISSUE THREAD

**Issue by snobear** [opentok/opentok-react-native#58]
Hi, I'm looking to build an app with `create-react-native` which uses Expo, but I'm reading that Expo [does not have support for WebRTC](https://docs.expo.io/versions/latest/introduction/why-not-expo.html). 

I only have experience developing w/ Opentok SDKs on desktop, but I'm assuming the WebRTC protocol is still used under the hood on mobile as well. But before I completely rule out using Expo, I wanted to confirm whether or not I could use Expo + opentok-react-native. Thanks for any info.

**Comment by snobear** [comment]
OK cool thanks for confirming, and for your work on this @msach22 !

**Comment by msach22** [comment]
No problem, @snobear! It should work if you eject the app :D

**Comment by bigethan** [comment]
as it's been 4 years, is this still the case?

**Comment by garyThrels** [comment]
@msach22 would be grate to know if this is still the case? or if support is planned?

**Comment by feliperugai** [comment]
That would be great. Expo gives us great features and is a very good starter.
Now they have a [Config Plugins](https://docs.expo.dev/guides/config-plugins/) feature that enable native features to be "embed" in the build process.
Is this support planned?

**Comment by bfarrgaynor** [comment]
I'm also very interested if this could be accomplished using config plugins.
