### ISSUE TITLE
Stereo Audio

### ISSUE THREAD

**Issue by RishiSingh1234567890** [opentok/opentok-react-native#580]
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by RishiSingh1234567890** [comment]
How to enable Stereo Audio in openTok ?

**Comment by enricop89** [comment]
On the session component, there is a property called `enableStereoOutput ` (https://github.com/opentok/opentok-react-native/blob/main/docs/OTSession.md#setting-session-options). If you set it to true, stereo output is enabled
