### ISSUE TITLE
Incompatible with Apple Silicon (arm64)

### ISSUE THREAD

**Issue by relm923** [opentok/opentok-react-native#584]
# Bug Report

**Current behavior**
Unable to run app on iOS simulator from Mac with Apple Silicon (arm64)

**Steps to reproduce**
https://github.com/opentok/opentok-react-native-samples/issues/89

**Example Project**
https://github.com/opentok/opentok-react-native-samples/issues/89

**What is the current *bug* behavior?**
Fails to build app on simulator

**What is the expected *correct* behavior?**
App successfully builds on Intel and Arm Macs

**Comment by enricop89** [comment]
This bug is not related to the opentok-react-native library but to the Opentok iOS SDK. 

From Opentok documentation: 


> The Vonage Video API iOS SDK does not currently include support for arm64, 
> which the Simulator requires when running on an M1 Mac. 
> To work around this issue, run Xcode (and Simulator) 
> in [Rosetta](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment).


https://tokbox.com/developer/sdks/ios/release-notes.html#issues-using-xcode-simulator-to-preview-your-app-on-a-mac-with-an-m1-chip
