### ISSUE TITLE
Brodcast Stream

### ISSUE THREAD

**Issue by krishna8077** [opentok/opentok-react-native#590]
Hi Team  Actually i am facing a issue in samsung s21 ultra when i start event the camera is not open with OTSession ,OTPublisher..
i have set the event id,and all the param in OTSession,OTPublisher Properties...

Please suggest me any solution about it thanks..

**Comment by enricop89** [comment]
Can I please try to reproduce with https://github.com/opentok/opentok-react-native-samples/tree/main/BasicVideoChat?
