### ISSUE TITLE
new NativeEventEmitter() was called with a non-null argument without the required

### ISSUE THREAD

**Issue by Playfrog4u** [opentok/opentok-react-native#592]
# Bug Report

**Current behavior**
> Getting `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method
and `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method yellow box warnings only on android. iOS does not present this issue

**Steps to reproduce**
> Using the opentok-react-native-samples, Android gets 2  yellow box warnings. Bug is not present in iOS
"react": "17.0.2",
"react-native": "0.65.1"

**Example Project**
> [opentok-react-native-samples/BasicVideoChat](https://github.com/opentok/opentok-react-native-samples)

**Relevant logs and/or screenshots**
> 
![Screenshot_20220513-232909](https://user-images.githubusercontent.com/1095542/168411254-e1002b94-27d0-4f5b-81c2-3887ce047b79.jpg)
![Screenshot_20220513-232905](https://user-images.githubusercontent.com/1095542/168411255-a609e441-dc44-42b3-afaa-843319977274.jpg)

**Comment by TalhaAhsan** [comment]
Can you verify if this is still causing an issue for you after the change by @enricop89
