### ISSUE TITLE
ViewPropTypes will be removed from React Native

### ISSUE THREAD

**Issue by Playfrog4u** [opentok/opentok-react-native#593]
# Bug Report

**Current behavior**
> Getting yellow box "ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'."

**Steps to reproduce**
> Set needed api, session, and token then start the app.

**Example Project**
>  [opentok-react-native-samples/BasicVideoChat](https://github.com/opentok/opentok-react-native-samples)

**Possible fix**
> `Image.propTypes`, `Text.propTypes`, `TextInput.propTypes`, `ColorPropType`, `EdgeInsetsPropType`,` PointPropType`, and `ViewPropTypes` from react-native are deprecated, and starting from react-native@0.68

[react-native 0.68 Changelog](https://github.com/facebook/react-native/blob/66419ed8f5be4e0efca4e0f261d902607408f29c/CHANGELOG.md#changed)

The file that  needs updates is the `/src/OTSession.js` on line 2

**Relevant logs and/or screenshots**
> ![Screenshot_20220514-001954_BasicVideoChat](https://user-images.githubusercontent.com/1095542/168412009-270348d0-2b26-4ef3-9138-42f997300c7a.jpg)

**Comment by enricop89** [comment]
Thanks for reporting, I'll have a look soon

**Comment by Playfrog4u** [comment]
> Thanks for reporting, I'll have a look soon

Thank you!

**Comment by enricop89** [comment]
@Playfrog4u  would you mind testing #609 ?

**Comment by noaholsson** [comment]
@enricop89 I'm experiencing the same problem and #609 fixed the problem for me. 
When can I expect it to get released?

**Comment by enricop89** [comment]
@noaholsson we are currently having a problem with the 0.21.0 release which crashes on iOS - let me think of a way to cherry-pick #609 and push it to a new 0.20.4

**Comment by enricop89** [comment]
This should be fixed with the `0.20.4` version: https://www.npmjs.com/package/opentok-react-native
