### ISSUE TITLE
Session does not fully disconnect after component is dismounted

### ISSUE THREAD

**Issue by renanpupin** [opentok/opentok-react-native#60]
Apparently the native application context or the javascript thread are not being reset after the video call scene is dismounted. After opening, exiting, and re-entering a call, the events from the previous session keeps executing.

Steps to simulate the error.

1. Open a call
2. Set listeners for Session, Publisher, and Subscriber and print with the random number.
3. Exit call screen
4. Start the call again

**Comment by msach22** [comment]
@renanpupin Just to verify, you are unmounting the `OTSession` component when you exit the call screen and the native events are still firing?

**Comment by renanpupin** [comment]
Exactly, the listeners are not removed when the session component is closed.

**Comment by renanpupin** [comment]
We have removeNativeEvent function at OT.js .
https://github.com/opentok/opentok-react-native/blob/26f67941ceb955eda800d97e06ea0972d1770bf6/src/OT.js#L42-L48

At componentWillMount from session, we have setNativeEvents.
https://github.com/opentok/opentok-react-native/blob/26f67941ceb955eda800d97e06ea0972d1770bf6/src/OTSession.js#L18

But at componentWillUnmount, there is a call for disconnectSession() that does not call removeNativeEvent().

We have removeNativeEvent() call from OTPublisher, but not from OTSession and OTSubscriber.
https://github.com/opentok/opentok-react-native/blob/26f67941ceb955eda800d97e06ea0972d1770bf6/src/OTPublisher.js#L54


Hope this can help.

**Comment by msach22** [comment]
@renanpupin yup that's exactly what we need to do. Something very similar to this: https://github.com/opentok/opentok-react-native/blob/master/src/OTPublisher.js#L59

Thanks for catching this btw! If you're up for it, please send a PR, if not, I can push this change in `0.6.0`.
