### ISSUE TITLE
Cannot attach to new session when sessionId of OTsession is changed

### ISSUE THREAD

**Issue by billy220** [opentok/opentok-react-native#602]
# Bug Report

**Current behavior**
If the sessionId is changed after the OTSession is mounted, you cannot start a call with a new session. Is this a known issue?

**Steps to reproduce**
Change sessionId after OTsession is mounted

**What is the current *bug* behavior?**
If the sessionId is changed after the OTSession is mounted, you cannot start a call with a new session

**What is the expected *correct* behavior?**
If you change sessionId after OTsession is mounted, it is attached to a new session.

**Relevant logs and/or screenshots**
```
OTRN JS: There was an error:  {"message": "Error connecting to session. Could not find native session instance"}
```

**Comment by ShubhamSharma-iOS** [comment]
I am also getting the same error, after updating from 0.18.0 to 0.20.3. Any ideas on how to resolve this issue?

**Comment by enricop89** [comment]
It's not how it is supposed to work. You should unmount the OTSession component and use a new sessionID
