### ISSUE TITLE
Option to mute microphone of the publisher through a button

### ISSUE THREAD

**Issue by prabhat13528** [opentok/opentok-react-native#611]
Currently, I can hover over the video and mute the mic but is there any other way to access the function/method to mute the microphone through a button?

I am using the window.OT.initsession to create the session and the below code is used to create the publisher stream:

```
this.sessionHelper = createSessionHelper({
      apiKey: session.apiKey,
      sessionId: session.sessionId,
      token: session.token,
      onStreamsUpdated: (streams) => {
        this.setState({ streams });
      },
      onConnect: function () {
        setTimeout(function () {
          const publisherOptions = {
            frameRate: 15,
            resolution: "1280x720",
            showControls: true,
            facingMode: "environment",
            fitMode: "contain",
            height: "100%",
            width: "100%",
            mirror: false,
            publishAudio: me.state.demo,
          };
          me.publisherHelper = new Publisher();
          me.publisherHelper
            .publish(publisherOptions, null, true)
            .then(function publishThen(publisher) {
              me.sessionHelper.session.publish(publisher, me.handleError);
              me.publisher = publisher;
            })
            .catch(me.handleError);
        }, 100);
      },
      onIncomingSignal: function (data) {
        me.handleIncomingSignal(data);
      },
    });
```

I know that the **publishAudio** can be used to mute but once the publisher stream has started, changing the state variable it's being assigned to doesn't update the publisher property.

Is there any way to update the publisher property once the stream is published or access the mute method/function outside of the video ?

**Comment by enricop89** [comment]
This is part of your implementation. You can see an example here: 

1. Button: https://github.com/enricop89/multiparty-video-react-native/blob/master/App.js#L337
2. Action: https://github.com/enricop89/multiparty-video-react-native/blob/master/App.js#L115

**Comment by prabhat13528** [comment]
Thank you for the samples and the quick response but I mistakenly posted on the react-native project instead of the node js project. But would the implementation differ for node? Or Should I post it on opentok-node project?

**Comment by prabhat13528** [comment]
Correction: Opentok-react(https://github.com/opentok/opentok-react). I am fairly new to this so got confused.
