### ISSUE TITLE
SubscribeToSelf Does Not Work

### ISSUE THREAD

**Issue by bahalperin** [opentok/opentok-react-native#612]
# Bug Report

**Current behavior**
The prop `subscribeToSelf` on `OTSubscriber` does not seem to do anything.

**Steps to reproduce**
Pull down [this branch](https://github.com/bahalperin/opentok-react-native-samples/tree/bh/subscribe-to-self-bug) and run the example app.  Join a session and you'll see yourself once (just the publisher).  I would expect to see a second video for the subscriber.  If another person joins, you will see them.

**Example Project**
https://github.com/bahalperin/opentok-react-native-samples/tree/bh/subscribe-to-self-bug

**What is the current *bug* behavior?**
No subscriber is created for the publisher's stream when `subscribeToSelf` is true

**What is the expected *correct* behavior?**
You should see a second video of yourself when `subscribeToSelf` is true

**Comment by jeffswartz** [comment]
We are looking into this.

**Comment by pietgk** [comment]
any status update?
