### ISSUE TITLE
Cannot read property 'OTSession' of undefined

### ISSUE THREAD

**Issue by izbari** [opentok/opentok-react-native#614]
opentok-react-native version => ^0.21.0
    react-native  version=> 0.69.1

I am getting an error as below;
I watched the right steps while installing the package. But React Native 0.69 with Auto Linking was removed. Since I could not link manual, I downgrade the react native version and link. I continued to get the same error.
Openok Creadentals Are True i Tested in Playground.

![image](https://user-images.githubusercontent.com/73957984/181524382-7035ff44-2646-42c9-b69a-b93f1f75a819.png)

SECOND ISSUE When I add this code as below to Build.Gradle file, Android Build duration increased 10 minutes from 1min

![image](https://user-images.githubusercontent.com/73957984/181526527-1b308c7d-2329-4abe-a7b9-ce2a36160cdd.png)

Code snipped;
```
import React, {Component} from 'react';
import {View} from 'react-native';
import {OTSession, OTPublisher, OTSubscriber} from 'opentok-react-native';

class App extends Component {
  constructor(props) {
    super(props);
    this.apiKey = 'x';
    this.sessionId =
      'x';
    this.token =
      'xxx';
  }

  render() {
    return (
      <View
        style={{
          flex: 1,
          flexDirection: 'column',
          paddingHorizontal: 100,
          paddingVertical: 50,
        }}>
        <OTSession
          apiKey={this.apiKey}
          sessionId={this.sessionId}
          token={this.token}>
          <OTPublisher style={{width: 200, height: 200}} />
          <OTSubscriber style={{width: 200, height: 200}} />
        </OTSession>
      </View>
    );
  }
}

export default App;


```
Any help ?

**Comment by izbari** [comment]
i solved the issue. the issue is OTSession file importing ViewPropTypes but it was deprecated. I produces error instead of warning. I solved the error by importing ViewPropTypes from deprecated-prop-types package.

**Comment by TalhaAhsan** [comment]
Closing this issue as it was solved.

**Comment by rtmruczek** [comment]
Hello! Was this issue actually solved? It looks like OTSession (and a few other components) are still importing `ViewPropTypes`. 

This is going to break on RN versions > `0.69` because the `prop-types` system was removed. Perhaps I can put up a PR for this.
