### ISSUE TITLE
Please bump the opentok Android to 2.24.0

### ISSUE THREAD

**Issue by nicwise** [opentok/opentok-react-native#629]
We've been hitting this a lot

https://tokbox.com/developer/sdks/android/release-notes.html

```
This version fixes an issue in which participants could not hear audio published by clients using certain models of Huawei devices.
```

We are going to patch node_modules for the moment, but it'd be lovely to get this into a proper release.

**Comment by enricop89** [comment]
I need to fix https://github.com/opentok/opentok-react-native/issues/628 before updating

**Comment by pietgk** [comment]
As opentok-android-sdk:2.24.1 fixes a bluetooth headset reconnect issue, i would like to see the update to 2.24.1.
I patched it in the BasicVideoChat test:
- build.gradle 
  `-    implementation 'com.opentok.android:opentok-android-sdk:2.23.1'
+    implementation 'com.opentok.android:opentok-android-sdk:2.24.1'`
and OTSessionManager.java with a temp fix of commenting out the @Override  
`// @Override
public boolean isCamera2Capable() {`

Then tested it for the headset reconnect issue and that worked.

**Comment by nicwise** [comment]
@enricop89 any news on #628 ? this one is causing us a lot of issues with hauwei phones :(

**Comment by pietgk** [comment]
@enricop89 i got the request (from Roger F) to test 0.21.2 but i would really appreciate that i could test the version with the upgrade of android to at least 2.24.0.
Any feedback on when that might be?

**Comment by enricop89** [comment]
Hi @pietgk , if urgent you can edit the Android version [here](https://github.com/opentok/opentok-react-native/blob/main/android/build.gradle#L30).

FYI: @jeffswartz

**Comment by Panda-ref** [comment]
Also, current opentok-android-sdk:2.23.1 depends on [WebRTC » 84.0.21 (1361.7 MB)](https://mvnrepository.com/artifact/com.vonage/webrtc/84.0.21) which dramatically increases the resulting app size like x2 compared to previous version.
