### ISSUE TITLE
How to implement blur background in opentok-react-native 

### ISSUE THREAD

**Issue by anshumanburman** [opentok/opentok-react-native#631]
- I want to use a blur background or background image during video chat in open-react-native. Anyone can help me?. Thanks in advance.

**Comment by kapilmishr** [comment]
We are working to incorporate background blur in Opentok React Native lib.

**Comment by marinaserranomontes** [comment]
Hi @anshumanburman,

FYI, the latest published [version v2.23.1](https://www.npmjs.com/package/opentok-react-native) includes the new `OTPublisher.setVideoTransformers()` method that lets you set (and clear) video transformers, such as a background blur for a publisher.

Thanks.
