### ISSUE TITLE
publisher video freezes after few seconds. - Android

### ISSUE THREAD

**Issue by KiranRadish** [opentok/opentok-react-native#632]
**On Android after connecting, the video suddenly freezes - image gets stuck of user but audio still works.**
`"opentok-react-native": "^0.21.1",`
`buildToolsVersion = "30.0.2"
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 31
ndkVersion = "21.4.7075529"
`

**Comment by fossmobile** [comment]
I had the same issue downgrade to ^20.0 helped

**Comment by KiranRadish** [comment]
@fossmobile yes downgrading the version works but this should work on 0.21.1 too, may be some changes required at native side

**Comment by vineus** [comment]
more details here: https://github.com/opentok/opentok-react-native/issues/628

**Comment by fossmobile** [comment]
Hi,

 Any update on this as opentok react native lib is crashing with Anroid 11and 12 with the latest? I think it is due to permissions as there are lot changes on Android SDK 31 , Not sure its been ported to react native as yet.

**Comment by jeffswartz** [comment]
Fixed with https://github.com/opentok/opentok-react-native/pull/646.
