### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by elie-chaaban** [opentok/opentok-react-native#635]
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':opentok-react-native:generateReleaseRFile'.
[stderr] > Could not resolve all files for configuration ':opentok-react-native:releaseCompileClasspath'.
[stderr]    > Failed to transform webrtc-84.0.21.aar (com.vonage:webrtc:84.0.21) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
[stderr]       > Could not find webrtc-84.0.21.aar (com.vonage:webrtc:84.0.21).
[stderr]         Searched in the following locations:
[stderr]             http://10.4.1.4:8081/artifactory/libs-release/com/vonage/webrtc/84.0.21/webrtc-84.0.21.aar
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 4m 40s

I am using react native expo and all was good.

Today I am releasing a new build and this error is happening.

I am using version "opentok-react-native": "^0.21.1",

**Comment by gotheme** [comment]
Any update on this..? I am also facing same issue.

**Comment by kundanthe** [comment]
Hi @elie-chaaban ,You got the solutions for this...

**Comment by brunods-dev** [comment]
any updates ?

**Comment by Taras-Tymchiy** [comment]
Hi @elie-chaaban 
I'm getting the same error. 
Please share how did you manage to fix it

**Comment by elie-chaaban** [comment]
> Hi @elie-chaaban 
> 
> I'm getting the same error. 
> 
> Please share how did you manage to fix it

![image](https://user-images.githubusercontent.com/29852821/224506233-4b1cbb44-66b1-47c1-ba21-1b8fce30f975.jpeg)

I added these

But then I removed them, updated to expo sdk 47 and the newest opentok version, you do not need it

**Comment by Taras-Tymchiy** [comment]
> > Hi @elie-chaaban
> > I'm getting the same error.
> > Please share how did you manage to fix it
> 
> ![image](https://user-images.githubusercontent.com/29852821/224506233-4b1cbb44-66b1-47c1-ba21-1b8fce30f975.jpeg)
> 
> I added these in app json
> 
> But then I removed them, updated to expo sdk 47 and the newest opentok version, you do not need it

Thank you!

I was already using expo 47, but still getting this error. The config you suggested didn't work, but it was really helpful. 

In case anyone still has this problem, the custom expo config plugin which does basically the same worked for me:

withGradleProperties(config, 
    async (config) => {
      config.modResults.find( p => p.key === 'org.gradle.jvmargs').value = '-Xmx4096m';
      return config;
    });

**Comment by elie-chaaban** [comment]
> > > Hi @elie-chaaban
> 
> > > I'm getting the same error.
> 
> > > Please share how did you manage to fix it
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/29852821/224506233-4b1cbb44-66b1-47c1-ba21-1b8fce30f975.jpeg)
> 
> > 
> 
> > I added these in app json
> 
> > 
> 
> > But then I removed them, updated to expo sdk 47 and the newest opentok version, you do not need it
> 
> 
> 
> Thank you!
> 
> 
> 
> I was already using expo 47, but still getting this error. The config you suggested didn't work, but it was really helpful. 
> 
> 
> 
> In case anyone still has this problem, the custom expo config plugin which does basically the same worked for me:
> 
> 
> 
> ```
> 
> withGradleProperties(config, 
> 
>     async (config) => {
> 
>       config.modResults.find( p => p.key === 'org.gradle.jvmargs').value = '-Xmx4096m';
> 
>       return config;
> 
>     });
> 
> ```

Perfect!

When i used this with sdk 47 and the latest opentok sdk version it worked without it, you had to install expo build properties and create a custom dev client

Anyway, glad it worked
