### ISSUE TITLE
Bitcode Enabled

### ISSUE THREAD

**Issue by haneen91** [opentok/opentok-react-native#637]
We used security feature in iOS project which reject the app if bitcode disabled ..is there any way to enable it on openTok library
<img width="572" alt="Screenshot 2023-01-02 at 10 47 10 AM" src="https://user-images.githubusercontent.com/12627582/210210060-512842fb-f9ce-4ba3-8e6a-9cd59cef14f5.png">

**Comment by jeffswartz** [comment]
The opentok-react-native library has supported bitcode for many releases, now. (Support for bitcode was added in the OpenTok iOS SDK 2.9.0. opentok-react-native now uses v2.25.1 of the OpenTok iOS SDK.) To enable bitcode in the client app, set `BITCODE_GENERATION_MODE` to `bitcode`. (See https://developer.apple.com/forums/thread/127992.)
