### ISSUE TITLE
bluetooth issues

### ISSUE THREAD

**Issue by fossmobile** [opentok/opentok-react-native#640]
Bluetooth headsets doesnt work as expected any of you have an idea for the best version?
Tried
0.20.3/0.20.4
CustomAudioDriver by enabling sterero mode.
**Please post usage questions or broader discussions on [StackOverflow](https://stackoverflow.com/questions/ask?tags=opentok+react-native)**.

---

For **feature requests**, please fill out the [feature request template](https://github.com/opentok/opentok-react-native/issues/new?template=feature_request.md)

---

For **bug reports**, please fill out the [bug report issue template](https://github.com/opentok/opentok-react-native/issues/new?template=bug.md)

**Comment by pietgk** [comment]
maybe the bump to the latest android version will solve this.
But there are blocking issues on freezing video that need solving before that will happen i think.

**Comment by pietgk** [comment]
please try 0.21.3 as it should solve bluetooth issues on android as it references an android version with bluetooth fixes.

**Comment by pietgk** [comment]
we still experience bluetooth reconnect issues with the current latest versions!

**Comment by fossmobile** [comment]
yea all good. Thanks

**Comment by pietgk** [comment]
Close the ticket?

**Comment by nicolasdevienne** [comment]
Hi all! I've just test on 3 devices with the lastest version. On Samsung S9 (Android 9) and Huawei P20 (Android 9) it works : when I connect my bluetooth device during a video call, the switch from speaker to bluetooth device works. But on Pixel 5 (Android 14) the audio is always from speaker whereas the bluetooth device is connected. I must restart the app to use bluetooth device.

**Comment by kapilmishr** [comment]
Thanks @pietgk & @fossmobile for confirming. 
Closing the issues as Bluetooth issues were fixed and released with v0.21.5 of the SDK.
