### ISSUE TITLE
Support for Live Captions

### ISSUE THREAD

**Issue by binoychemmagate** [opentok/opentok-react-native#643]
# Feature Request

Live Captions 

**Description**

**Problem** - Live Captions is a new feature supported by Vonage Video API (Web and Native), we would like to get support for Live Captions in React Native.  
**use cases** - The Vonage Captions API allows the customer to show live captions to their end-users in a Vonage Video session using a transcription service. 
**benefits/goals** - Feature parity with Web/Native platforms on Live Captions

**Proposal**
TBD

**Links / references**
TBD

cc @kapilmishr @rhainer

**Comment by pietgk** [comment]
Any status update regarding this issue?

**Comment by kapilmishr** [comment]
Live captions have been implemented and released with version 2.26.1 (October 2023).
