### ISSUE TITLE
Cycling cameras crashes on subsequent use (A13) - Fixed with new Vonage Android SDK update (with patch)

### ISSUE THREAD

**Issue by nicwise** [opentok/opentok-react-native#657]
OK, so we finally got to a working `0.21.2` which has SDK `2.23.1` in it. Thanks for that one.

`2.23.1` is 9 months old: https://tokbox.com/developer/sdks/android/release-notes.html

So, I needed to patch to `2.24.1` to get the Huawei fix, and there is also a fix in `2.24.0` around cycling the cameras.

> "This version fixes an intermittent crash when cycling the camera"

Because I can't just do this in my code, we are not monsters and we build and deploy from CI not our local machines, I've attached a .patch file which will patch both the SDK version, and the required .java change. The Java but might not be 100% correct, but it does work, so far.

Previously, if we made a call, switched camera to the back camera, then disconnected, then any subsequent call would lock up the whole app and services. Had to reboot the phone. Not good.

TBH, kinda getting sick of having to patch the SDK version manually.

[opentok-react-native+0.21.2.patch](https://github.com/opentok/opentok-react-native/files/10935847/opentok-react-native%2B0.21.2.patch)

**Comment by nicwise** [comment]
And I'll try to do a PR for this shortly, in the near future

**Comment by nicwise** [comment]
merging #656 would solve this

**Comment by elie-chaaban** [comment]
How can i use or create this patch? Maybe it would fix the issue happening on Android 9 when the video is most of the time black

**Comment by elie-chaaban** [comment]
And is the patch working correctly? You were saying java code might be not 100% right

**Comment by elie-chaaban** [comment]
![image](https://user-images.githubusercontent.com/29852821/224635603-9d138726-612e-4bf5-ae2a-f953c417a982.png)

i get this error when i did the patch

**Comment by nicwise** [comment]
Closing as @jeffswartz fixed this in the latest proper release 🎉
