### ISSUE TITLE
[iOS] Stream is getting destroyed using opentok more than 1 minutes when app comes from background to foreground in iOS 

### ISSUE THREAD

**Issue by AnmolK89** [opentok/opentok-react-native#663]
Steps for iOS
1. I have an active session with video call using open tok.
2. Suddenly if I get a Microsoft teams call or phone call. I will receive incoming call from Microsoft teams call or phone call then the opentok video call session goes to the background.
3. After completing the Microsoft teams call for more than a minute if I go back to open tok video call session shows continuous loading I am out of the particular opentok video call session for other participants.

In android when I come back more than 1 minutes from background to foreground the stream is not destroyed 
It is happening only in iOS.

I am using latest opentok sdk
Can someone please help me on this!!!

**Comment by jeffswartz** [comment]
This was fixed in [v2.25.2](https://github.com/opentok/opentok-react-native/releases/tag/v2.25.2).
