### ISSUE TITLE
OTSubscriber - subscribeToSelf option isn't working

### ISSUE THREAD

**Issue by Giebler** [opentok/opentok-react-native#664]
# Bug Report

**Current behavior**
We set the subscribeToSelf option true in OTSubscriber yet we don't see the subscriber video streaming in the subscriber view.

**Steps to reproduce**
Set the subscribeToSelf option true - look at the subscriber view

**Example Project**
Should be able to do this in the sample app.

**What is the current *bug* behavior?**
We don't see a notice in the subscriber streamCreated sessionEventHandler and it doesn’t show the stream. 

**What is the expected *correct* behavior?**
I expected to see a notice in the subscriber streamCreated sessionEventHandler and see my video stream in the subscriber view (as well as the publisher view). 

**Relevant logs and/or screenshots**
I see the usual publisher steamCreated notice with our small screen view but the large view has nothing.  Am I missing something?  Do we need to do more than set subscribeToSelf true?

**Comment by jeffswartz** [comment]
We are looking into this.

**Comment by beHaze** [comment]
@Giebler this issue was fixed in the most recent release v2.27.0 Let us know if you're still having issues on our most recent version and/or with one of our sample apps.
