### ISSUE TITLE
Dial-out method for SIP interconnect not working, Unable to receive call after api success. 

### ISSUE THREAD

**Issue by rohitmerawat807** [opentok/opentok-react-native#670]
React-native-opentok SIP interconnect is not working for dial-out. After calling sip interconnect api, getting sucess with sessionId and accessToken but not getting call on the provided number. 

Using latest version: 
"opentok-react-native": "^0.21.4",

SIP Interconnect::Initiating a SIP call

Tried this method: https://tokbox.com/developer/guides/sip/

**Comment by kapilmishr** [comment]
@rohitmerawat807 All related support tickets 2232683, 2232855, and 2240735 were closed. 
Please check with the latest version of react-native and reach out to Vonage support (https://api.support.vonage.com/hc/en-us) in case you still face issues.
