### ISSUE TITLE
Whether the subscriber can get the actual resolution of the video

### ISSUE THREAD

**Issue by gomashiox** [opentok/opentok-react-native#674]
Hello, 
Is there any way to get the WIDTH and HEIGHT for each of the subscribed frames?

I would like to always get the actual resolution on the subscriber side because the resolution of the video dynamically changes according to the network strength of the mobile device.

I think this is for iOS, but I would like to know if there is any sample code.
https://tokbox.com/developer/sdks/ios/reference/Classes/OTVideoFormat.html#//api/name/imageWidth

If it is already available, I would be happy to point it out.
Thanks.

**Comment by rhainer** [comment]
@gomashiox - Good question. That should be possible but I need to check with some developers who are unavailable this week. I will try to get back to you on this soon.

**Comment by jeffswartz** [comment]
There is currently no way to access this. The OpenTok React Native SDK does not expose the `videoRenderer` property or the `OTVideoFrame.format.imageWidth` for a subscriber's rendered frames.

**Comment by pietgk** [comment]
Any status if/when this will be fixed?

**Comment by beHaze** [comment]
@pietgkwe unfortunately, we do not have a way to get the width or height of each rendered frame.
