### ISSUE TITLE
Camera Position Back not working

### ISSUE THREAD

**Issue by hamzahoda** [opentok/opentok-react-native#680]
I'm using     

"opentok-react-native": "^0.21.4",
 "react-native": "0.71.10",

By setting  cameraPosition: 'back', 
The publisher fails to initialize.

Using 'front' works perfectly but I am unable to update the camera from front to back.

**Comment by hamzahoda** [comment]
Was able to resolve this by downgrading the opentok-react-native library.

    "opentok-react-native": "^0.20.1",

**Comment by josmmv** [comment]
I'm having this issue too with opentok v2.25.2

**Comment by jeffswartz** [comment]
Thanks. We are looking into the issue.

**Comment by josmmv** [comment]
@jeffswartz Greetings, have you been able to check this problem? We have been having it for several weeks now

**Comment by czoli1976** [comment]
@josmmv @hamzahoda 

As stated by @marinaserranomontes this should be fixed.
Can you confirm?
Please, could you retest with the latest version to confirm the issue was resolved?

Thanks.

**Comment by nicolasdevienne** [comment]
Hi all! I've just test on 3 devices with the lastest version. On Pixel 5 (Android 14) and Huawei P20 (Android 9) it works but on Samsung S9 (Android 10) when I tried to switch from "front" to "back" it fails (always "front") and just after when I tried to switch from "back" to "front", it changes to "back" whereas I sent "front". So now, when I sent "back" we have "front" and when I sent "front" we have "back". Do you know what I mean?...

**Comment by beHaze** [comment]
Hi @nicolasdevienne, please reach out to our Support team for issues related to specific devices (https://api.support.vonage.com/hc/en-us).
