### ISSUE TITLE
Getting error on background blur ?

### ISSUE THREAD

**Issue by kundanthe** [opentok/opentok-react-native#682]
PublisherKit.VideoTransformer backgroundBlur = new PublisherKit.VideoTransformer("BackgroundBlur", "{\"radius\":\"High\"}");

This complete syntax is given on documentation, And I am following same but this syntax is not executing at compile time.

I am getting this error.

'com.opentok.android.PublisherKit' is not an enclosing class ?

Needed some help full information.

**Comment by kapilmishr** [comment]
We are working to incorporate background blur in Opentok React Native lib.

**Comment by jeffswartz** [comment]
As @kapilmishr mentions, we will be adding a function to support the [Vonage Media Processor library functionality](https://tokbox.com/developer/guides/vonage-media-processor/), including background blur support. You will then access that JavaScript function in React Native. You do not have access to the PublisherKit directly in the OpenTok. React Native API.

**Comment by kundanthe** [comment]
Thank you @jeffswartz to letting me know. So when it will come on this library, We need to implement this feature as soon as possible.

**Comment by kundanthe** [comment]
Hi @jeffswartz  you have any work around for this..?

**Comment by marinaserranomontes** [comment]
Hi @kundanthe 

Background blur support was included in the latest version published v2.26.1 https://www.npmjs.com/package/opentok-react-native. The new `OTPublisher.setVideoTransformers()` method lets you set and clear video transformers such as a background blur for a publisher.

Thanks.
