### ISSUE TITLE
Video call disconnecting in IOS after taking normal call ?

### ISSUE THREAD

**Issue by kundanthe** [opentok/opentok-react-native#683]
Hi All,

I am getting one major issue in IOS mainly, After receiving normal call on my IOS device Video call is disconnecting which was runing in parallel.

**Comment by marinaserranomontes** [comment]
Hi @kundanthe

Please, could you share the version you are using? Could you retry to reproduce the issue with the latest published https://www.npmjs.com/package/opentok-react-native ?

Thanks

**Comment by beHaze** [comment]
Hi @kundanthe we haven't heard back from you for 30+ days, so we're closing this issue for now. If you still need any assistance please, reach out to support.
