### ISSUE TITLE
Release 2.26.0 with new SDK versions

### ISSUE THREAD

**Issue by ogizanagi** [opentok/opentok-react-native#684]
# Feature Request

**Description**

Since I've read the [Android SDK changelog](https://tokbox.com/developer/sdks/android/release-notes.html) and stumbled upon this line: 

> Version 2.26.0 -- August 2023
> […]
> - This version fixes an issue where the SDK was crashing for subscribers on relayed sessions published using the Android SDK.

and since I encountered some issues (crashes in a few seconds) on iOS devices (actually any device) when an Android device is in the session.

**Proposal**

I wondered if this might be related to our issue and if we could get a 2.26.0 release using the respective Android & iOS SDK versions ? 🙏🏻 

**Links / references**

Regarding our issue, the iOS application crashes in a few seconds after an Android (so, with SDK 2.25.1) device is joining the session:  

![SCR-20230830-m40-2](https://github.com/opentok/opentok-react-native/assets/2211145/92431377-d6b0-4a26-bbbd-5cadf3292791)

No issue seems to happen with 2 iOS devices.
Nor with 1 iOS device and connecting to the session as another participant with the [Vonage Playground](https://tokbox.com/developer/tools/playground/) 

I reproduced this even using the [BasicVideoChat](https://github.com/opentok/opentok-react-native-samples/tree/main/BasicVideoChat) app on Android to join the session.

**Comment by marinaserranomontes** [comment]
Hi @ogizanagi 

Latest version for [opentok-react-native](https://www.npmjs.com/package/opentok-react-native) is v2.26.1. It uses v2.26.1 versions for Android and iOS. 

Thanks.
