### ISSUE TITLE
2.25.3 - Invalid Typescript Type Definitions

### ISSUE THREAD

**Issue by relm923** [opentok/opentok-react-native#690]
# Bug Report

**Current behavior**
Valid TS type definitions

**Steps to reproduce**
Upgrade to 2.25.3 and type check the new type definitions. This breaks Typescript apps

**Example Project**

**What is the current *bug* behavior?**
Cannot build Typescript app with 2.25.3

**What is the expected *correct* behavior?**
Valid type definitions

**Relevant logs and/or screenshots**
https://github.com/opentok/opentok-react-native/blob/main/%40types/index.d.ts#L407

**Comment by vona-ben** [comment]
Thank you for your contribution @relm923. We will check this
