### ISSUE TITLE
com.opentok.android.Camera2VideoCapturer.initCamera

### ISSUE THREAD

**Issue by elie-chaaban** [opentok/opentok-react-native#697]
![image](https://github.com/opentok/opentok-react-native/assets/29852821/a3bbb7d3-7f4b-4a5f-9eee-7735d432a4ec)
![image](https://github.com/opentok/opentok-react-native/assets/29852821/331b3b56-826f-4927-b750-646ab516b807)

Hello,

I am getting these issues on Android only

Fatal Exception: java.lang.SecurityException
validateClientPermissionsLocked:1215: Caller "com.sohati.sohatidoc" (PID 10000, UID 32085) cannot open camera "1" without camera permission

    "opentok-react-native": "^0.21.3",
    "expo": "49.0.6",
    "react": "18.2.0",
    "react-native": "0.72.5",

**Comment by marinaserranomontes** [comment]
Hi @elie-chaaban,

This issue should be fixed with this change: https://github.com/opentok/opentok-react-native/pull/687
Please, could you retest with the latest version to confirm the issue was resolved?

Thanks.

**Comment by elie-chaaban** [comment]
Hello,

Yes, I am not getting anymore this error.
