### ISSUE TITLE
Android 9 is working only when the second user is on iphone

### ISSUE THREAD

**Issue by elie-chaaban** [opentok/opentok-react-native#698]
This is a weird issue happening

**Comment by rhainer** [comment]
That's a pretty old version of Android.

**Comment by elie-chaaban** [comment]
even on Android 12

**Comment by elie-chaaban** [comment]
and android version 9 works when the 2nd user is iphpne @rhainer

**Comment by kapilmishr** [comment]
@elie-chaaban Which version of react-native are you using? Have you tried with latest version of react-native 2.26.1?
Latest version of React Native requires a mininum Android API level of 23 (https://tokbox.com/developer/sdks/react-native/ & https://tokbox.com/developer/sdks/android/).
