### ISSUE TITLE
Cannot build for Android (v0.6.1)

### ISSUE THREAD

**Issue by rossenv** [opentok/opentok-react-native#70]
Hi,
I'm with v0.6.1 and follow installation instructions but cannot build a simple app for Android, which is created with react-native init. The errors are in OTSessionManager.java
`/Projects/testOpenTok/node_modules/opentok-react-native/android/src/main/java/com/opentokreactnative/OTSessionManager.java
Error:(102, 13) error: cannot find symbol class View
Error:(127, 9) error: cannot find symbol variable mPublisher
Error:(128, 9) error: cannot find symbol variable mPublisher
Error:(129, 9) error: cannot find symbol variable mPublisher
Error:(130, 9) error: cannot find symbol variable mPublisher
Error:(131, 9) error: cannot find symbol variable mPublisher
Error:(133, 38) error: cannot find symbol variable mPublisher`

**Comment by msach22** [comment]
Released with `0.6.2`. Thanks for reporting @rossenv !
