### ISSUE TITLE
Crashlytics ios log crash: otk_peer_connection_manager::collect_garbage()

### ISSUE THREAD

**Issue by cnx-caiobarroso** [opentok/opentok-react-native#701]
# Bug Report

## **Current behavior**

Crashlytics shows crashes about something related to connection and garbage collection. There may be other issues related to this, but none of them approach the issue as a crashlytics related crash.

using version: "opentok-react-native": "2.25.2"

## **Example Project**
> (If possible, please create an example project here on GitHub.com that exhibits the problematic behaviour, and link to it here in the bug report)

## **What is the current *bug* behavior?**

0  XXXX                   0xc96330 std::__1::__vector_base<rtc::scoped_refptr<otk_peer_connection_manager::StatsObserverWrapper>, std::__1::allocator<rtc::scoped_refptr<otk_peer_connection_manager::StatsObserverWrapper>>>::~__vector_base() + 6542568

1  XXXX                    0xc96338 std::__1::__vector_base<rtc::scoped_refptr<otk_peer_connection_manager::StatsObserverWrapper>, std::__1::allocator<rtc::scoped_refptr<otk_peer_connection_manager::StatsObserverWrapper>>>::~__vector_base() + 6542576

2  XXXX                    0xc960bc otk_peer_connection_manager::collect_garbage() + 6541940

3  XXXX                    0xc95b50 otk_peer_connection_manager::get_stats(rtc::scoped_refptr<webrtc::StatsObserver>, webrtc::MediaStreamTrackInterface*, webrtc::PeerConnectionInterface::StatsOutputLevel) + 6540552

4  XXXX                    0xc8fd40 otk_peer_connection_stats_thread(void*) + 6516472

5  XXXX                    0xc944dc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void* (*)(void*), std::nullptr_t>>(void*) + 6534804

6  libsystem_pthread.dylib        0x16b8 _pthread_start + 148

7  libsystem_pthread.dylib        0xb88 thread_start + 8

## **What is the expected *correct* behavior?**

Not crashing or showing crash logs.

## **Relevant logs and/or screenshots**

![image](https://github.com/opentok/opentok-react-native/assets/104463740/a662671d-9ea4-4373-bfbe-1184201694cb)

**Comment by marinaserranomontes** [comment]
@cnx-caiobarroso 

Please, could you confirm if you are getting issues with the latest version v2.26.1?

Thanks

**Comment by cnx-caiobarroso** [comment]
@marinaserranomontes 
I'll try it and confirm later!

**Comment by czoli1976** [comment]
@cnx-caiobarroso, if you still have an issue with the latest version (2.26.1) then can you please reach out to Vonage support (https://api.support.vonage.com/hc/en-us) and provide error details?

**Comment by cnx-caiobarroso** [comment]
This issue has been resolved with 2.26.1! Thanks!
