### ISSUE TITLE
IOS build failing (Undefined symbol: _OBJC_CLASS_$_OTVideoTransformer)

### ISSUE THREAD

**Issue by vanshikasachdev1** [opentok/opentok-react-native#703]
After updating opentok-react-native version to **2.26.1** getting the following error

Undefined symbol: _OBJC_CLASS_$_OTVideoTransformer

<img width="376" alt="Screenshot 2023-11-09 at 10 16 10 PM" src="https://github.com/opentok/opentok-react-native/assets/72907781/a956b6a5-7f5a-4507-b254-cc56feeea952">

---
React-Native - '0.71.8'
opentok-react-native - '2.26.1'
IOS SDK version - '2.26.1'
---

**Comment by beHaze** [comment]
@czoli1976 we haven't heard back from you for 30 days, so we're closing this issue for now. Please, reach out if you still need help.
