### ISSUE TITLE
Android build failed, opentok-react-native:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by syukronmuttaqien** [opentok/opentok-react-native#704]
Device:
Macbook Air M2 

Platform: 
React Native 0.67.5

Hi, i'm upgrading the library to the latest, and follow the instruction on the documentation. i can run it on IOS, but when i run on android. it's failing because of.

```java
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':opentok-react-native:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
``` 

I Provide the screenshoot here. 

<img width="1470" alt="Screenshot 2023-11-20 at 14 04 26" src="https://github.com/opentok/opentok-react-native/assets/39506715/cd8e3fa7-e612-4fec-b84a-7bce7c6a42dc">

<img width="1470" alt="Screenshot 2023-11-20 at 14 12 36" src="https://github.com/opentok/opentok-react-native/assets/39506715/3f66f2e1-65c4-4baa-8bf3-09d7050f833e">

**Comment by kundanthe** [comment]
I am also getting same issue @syukronmuttaqien. Have you got any solution for this..?

**Comment by syukronmuttaqien** [comment]
Not Yet.., i'm still searching workaround for this.

**Comment by kundanthe** [comment]
Hi @jeffswartz , 
Please help him on this, why we are getting this ?

**Comment by syukronmuttaqien** [comment]
Hi @kundanthe, 

I've try some method, i can successfully build my app through this step.

1. Open Android Studio
2. Open The `opentok-react-native` build.gradle
3. On That File delete all the line
```groovy
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_11
        targetCompatibility JavaVersion.VERSION_1_11
    }
``` 
4. create a patch using `yarn patch-package opentok-react-native`

and try to rebuild it.

but i don't know what the side-effect of this, but at least my apps can run.

**Comment by kundanthe** [comment]
After changing the gradle version and distribution Url its working now..

   classpath 'com.android.tools.build:gradle:7.2.1'
   distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip
   
 If targeting to JAVA_11 then need to change the gradle version.
https://developer.android.com/build/releases/past-releases/agp-7-0-0-release-notes

**Comment by marinaserranomontes** [comment]
Hi @syukronmuttaqien, @kundanthe 

Thanks for sharing your fixes.

As you commented above, you will need Gradle plugin 7 for JDK 11. 

Please, reach out to Vonage support (https://api.support.vonage.com/hc/en-us) if you still need help.
