### ISSUE TITLE
Unable to connect to the session check network connection.

### ISSUE THREAD

**Issue by hamzahoda** [opentok/opentok-react-native#706]
I'm using

"opentok-react-native": "^0.21.4",
"react-native": "0.71.10",

The app was working fine but started getting error in connecting the session, Unable to connect to the session check the network connection.
Have checked the API key and secret, also tried updating to the latest version but still getting this error. 
Out of 10 different attempts it gets connected once. But on all other attempts shows the above error.
Have also tested on different devices with different android versions.

**Comment by kapilmishr** [comment]
@hamzahoda Can you please reach out to Vonage support (https://api.support.vonage.com/hc/en-us) and provide error details?

**Comment by kapilmishr** [comment]
@hamzahoda Are you able to reproduce with the latest version of react-native(v 2.26.1) released on Oct 31, 2023?

**Comment by hamzahoda** [comment]
Thank you @kapilmishr, was able to resolve this issue. Turns out it was an issue on Android versions > 12.
Need to add this permission in android-manifest.xml

<uses-permission android:name="android.permission.CALL_AUDIO_INTERCEPTION"/>
