### ISSUE TITLE
Screen sharing crash

### ISSUE THREAD

**Issue by nemanja-1995** [opentok/opentok-react-native#710]
*Current behavior*
When switching from CAMERA to SCREEN on android, the app crashes

*Steps to reproduce*
I'm running fine the conference call between two parties (let's say A and B). I've added a button on my react-native app so that A switches the source from CAMERA to SCREEN. The other side (B) starts receiving the new feed just fine but as soon as (A) does any action (like minimize the app) then (B) sees a frozen video: that would be fine if upon taking back to frontend the app on (A) I was getting again the screen share.
Another problem I'm encountering is that if (A) without leaving the app does something such as clicking on another tab(changing tabs), then on (A) the app crashes.

*Example Project*
--not available

*What is the current bug behavior?*
App crashes

*What is the expected correct behavior?*
Screen sharing should remain alive

*Relevant logs and/or screenshots*

**Comment by beHaze** [comment]
This issue was fixed in the most recent release. Please let us know if you are able to reproduce on our most recent version and/or with one of our sample apps.
