### ISSUE TITLE
Crashlytics: EventUtils.swift line 22 - EventUtils.prepareJSConnectionEventData(_:)

### ISSUE THREAD

**Issue by cnx-caiobarroso** [opentok/opentok-react-native#713]
Bug Report
Current behavior

There is no reproducible case, but crashlytics logs keeps growing.

Steps to reproduce

Can't reproduce locally.

What is the current bug behavior?

<img width="417" alt="image" src="https://github.com/opentok/opentok-react-native/assets/104463740/7b3f5d3c-6594-4fbc-9b0e-4cd9ab7153d1">

<img width="1233" alt="image" src="https://github.com/opentok/opentok-react-native/assets/104463740/da575876-b715-4d72-aba4-66481ac1f34f">

<img width="1228" alt="image" src="https://github.com/opentok/opentok-react-native/assets/104463740/f1552345-3856-4226-88cd-28478c7ae776">

There are some variations as above pictures but same root problem, probably.

**Comment by brutalkeso** [comment]
We are also seeing a growing amount of bridge related crashes

**React native version** 0.73.5

![image](https://github.com/opentok/opentok-react-native/assets/2705375/bd38fdbe-5b20-4e48-ac28-f7de9daddccb)

**Comment by beHaze** [comment]
Please reach out to Vonage support (https://api.support.vonage.com/hc/en-us) to help reproduce if you are still having issues.
