### ISSUE TITLE
OTPublisher/OTSubscriber does not pick sessionId prop when passed

### ISSUE THREAD

**Issue by talhamuhammadashraf** [opentok/opentok-react-native#722]
[OTPublisher](https://tokbox.com/developer/sdks/react-native/reference/OTPublisher.html) & [OTSubscriber](https://tokbox.com/developer/sdks/react-native/reference/OTSubscriber.html) does not pick `sessionId` when passed in props.

Documentation says:
sessionId (String) - The OpenTok session ID. This is auto-populated by wrapping `OTPublisher`/ `OTSubscriber` with `OTSession`, so you generally do not need to set this property for the OTPublisher.

So, internally it extracts it from `OTContext`, but it should get it from props as well when context is not there (when `OTPublisher`/ `OTSubscriber.html` is not wrapped with `OTSession`)

But, in case we have to render `OTPublisher`/ `OTSubscriber.html` somewhere else, not as children of OTSession and `sessionId` has been passed in props, it doesn't pick from props

**Comment by beHaze** [comment]
@talhamuhammadashraf Could you give us a little more info about your use case ? Could you achieve by modifying your css ?

**Comment by beHaze** [comment]
@talhamuhammadashraf we haven't heard back from you for a while, so we're closing this issue for now. Please, reach out if you still need help.

**Comment by talhamuhammadashraf** [comment]
Yeah still need help,
Actually I want to keep OT session and Frames(Publishers and Subscribers) in separate hierarchy, both rendering as sibling nodes. And in that case, Frames(Publishers and Subscribers) wouldn't get `sessionId` directly populated because they are not wrapped in OTSession and I need to pass it to them through props but it does not work.

Reason for keeping separate is, we need to keep same architecture as that we are using on web(as that does not need to put publishers and subscribers as children of OTSession)
