### ISSUE TITLE
OTScreenCapturer Unresolved

### ISSUE THREAD

**Issue by steverob** [opentok/opentok-react-native#73]
I'm seeing this issue on `master` version of this project when building with Xcode.

![screen shot 2018-05-14 at 5 44 45 pm](https://user-images.githubusercontent.com/1220480/39996887-a18cad44-579e-11e8-84ee-66f394289c4f.png)

`Use of unresolved identifier 'OTScreenCapturer`

Any solutions for the same?

**Comment by msach22** [comment]
@steverob Thanks for reporting it and submitting a PR! Released with `0.6.2`

**Comment by steverob** [comment]
thanks :)
