### ISSUE TITLE
Black view coming when coming from background to foreground in Android ?

### ISSUE THREAD

**Issue by kundanthe** [opentok/opentok-react-native#736]
# Bug Report

**Current behavior**
> BlackView coming when app coming from background to foreground. 

**Steps to reproduce**
> I am using dragbox to display a video in smallView. I started the video call and video is showing in small view which is correct. Now I minimize  the app after pressing home button of android device. I again resume it but now video is showing black view only.

**Example Project**
> (If possible, please create an example project here on GitHub.com that exhibits the problematic behaviour, and link to it here in the bug report)

**What is the current *bug* behavior?**
> (What actually happens)

**What is the expected *correct* behavior?**
> Video need to be display without and intervention.

**Relevant logs and/or screenshots**
> I had tested on multiple version but issue is same. Log which I am getting in android studio is...
**Android Log:-**
Getting this log:-
[SurfaceView - com.abc/com.abc.MainActivity#1]-timeRecords is at its maximum size[64]. Ignore this when unittesting.

**Comment by beHaze** [comment]
Closing this ticket as you're working directly with our Support team.
