### ISSUE TITLE
Use of Apple's Required Reason apis requires privacy manifest

### ISSUE THREAD

**Issue by vomchik** [opentok/opentok-react-native#737]
# Feature Request

**Description**
Apple is requiring packages and apps to declare their use of required reason API. 

-  https://github.com/opentok/opentok-react-native/blob/3ca01e1d29d04eb9ab1cd0c120b32a6cecca2b22/ios/OpenTokReactNative/OTScreenCapture.m#L66

Beginning May 1, 2024, Apple won't accept new apps or updates to existing apps that use packages that don't have a PrivacyInfo.xcprivacy.

**Proposal**

**Links / references**
- https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
- https://github.com/software-mansion/react-native-gesture-handler/pull/2830
- https://github.com/software-mansion/react-native-reanimated/pull/5819

**Comment by serzmerz** [comment]
any updates on this?

**Comment by beHaze** [comment]
Hello, we plan to release a version with support for Apple's app privacy manifest before May 1st. However, you could also use our file [here](https://github.com/opentok/vonage-client-sdk-video/blob/main/Sources/VonageClientSDKVideo/Resources/PrivacyInfo.xcprivacy) to help craft your own privacy file using Apple’s [instructions](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files). Hope that helps.

**Comment by jeffswartz** [comment]
Versions 2.27.4, 2.26.2, and 2.25.5 of the OpenTok React Native SDK updates the Vonage Video iOS SDK version to 2.25.5. This version adds a [privacy manifest required by Apple's App store](https://developer.apple.com/support/third-party-SDK-requirements?adobe_mc=MCMID%3D29013960881891954810964980988995526554%7CMCORGID%3DA8833BC75245AF9E0A490D4D%2540AdobeOrg%7CTS%3D1714430436).
