### ISSUE TITLE
PIP feature in React Native

### ISSUE THREAD

**Issue by ManojNuncsys** [opentok/opentok-react-native#739]
Can you please provide support for PIP feature in video call so that screen sharing feature can be helpful?

**Comment by beHaze** [comment]
Hi @ManojNuncsys, could you elaborate further on what you're trying to do ? 
Here's a sample app as well https://github.com/opentok/opentok-react-native-samples/tree/main/ScreenSharing

**Comment by beHaze** [comment]
We haven't heard back from you for a while, so we're closing this issue for now. Please, reach out if you still need help.
