### ISSUE TITLE
Crash: logOT

### ISSUE THREAD

**Issue by brutalkeso** [opentok/opentok-react-native#750]
# Bug Report

**Current behavior**
We are seeing this crash in our crash reporting tool

**Steps to reproduce**
Cant reproduce

**Example Project**
Not easily reproducible

**What is the current *bug* behavior?**
Small amount of crashes in production

**What is the expected *correct* behavior?**
No crashes

**Relevant logs and/or screenshots**
![image](https://github.com/opentok/opentok-react-native/assets/2705375/1a3d6f33-13ce-4b72-9f86-c68a06aed97a)

**Comment by beHaze** [comment]
Hello @brutalkeso please reach out to Vonage support (https://api.support.vonage.com/hc/en-us) and provide further details to help reproduce the issue.
