### ISSUE TITLE
Build 0.6.2 failing on iOS

### ISSUE THREAD

**Issue by renanpupin** [opentok/opentok-react-native#76]
** BUILD FAILED **

The following build commands failed:

	CompileSwift normal x86_64 /Users/.../node_modules/opentok-react-native/ios/OTSessionManager.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by msach22** [comment]
@renanpupin have you added the `OTScreenCapturer.swift` file to your iOS project?

**Comment by renanpupin** [comment]
** BUILD SUCCEEDED **
Thank you.

**Comment by msach22** [comment]
Happy to help @renanpupin !
