### ISSUE TITLE
Insert publisher data in state instead of boolean

### ISSUE THREAD

**Issue by Vagnxr** [opentok/opentok-react-native#770]
https://github.com/opentok/opentok-react-native/blob/25b3d09e0da9a365fb1c5a1e68640343ae9cbe1a/src/OTPublisher.js#L162

Hello, I want to make an improvement to this piece of code, storing initPublisher() in a variable to save the publisher instance and place it in the publisher state instead of a boolean. I'm having difficulties using the library because I don't have the publisher instance, I need to use the getRtcStatsReport method.

**Comment by jeffswartz** [comment]
@Vagnxr Call the `getRtcStatsReport()` method of a ref to the OTPublisher component, as in the following:

```
  <OTPublisher
    style={{width: 200, height: 200}}
    ref={this.publisher}
    eventHandlers={{
      streamCreated: () => {
        console.log(334)
        setTimeout(() => {
          this.publisher.current.getRtcStatsReport();
        }, 1000);
      },
      rtcStatsReport: event => console.log(event),
    }}
  />
```

(In this code, `this.publisher` is a ref created with React's `createRef()` method.
