### ISSUE TITLE
streamCreated is not a supported event type [iOS]

### ISSUE THREAD

**Issue by steverob** [opentok/opentok-react-native#78]
Hi, I'm getting this exception (dismissible) when listening to the `streamCreated` event. 

![img_0392](https://user-images.githubusercontent.com/1220480/40053681-d453741c-585f-11e8-94be-5cb15944aea3.png)

I'm guessing this is because the [publisher ID prefixed event name](https://github.com/opentok/opentok-react-native/blob/master/ios/OTSessionManager.swift#L367) is not part of the declared `supportedEvents()` in [`OTSessionManager.swift`](https://github.com/opentok/opentok-react-native/blob/master/ios/OTSessionManager.swift#L30)

I'm not sure how to get around this so unable to raise a PR with fix. Help appreciated on this @msach22 

The relevant code - 

```
this.publisherEventHandlers = {
      streamCreated: event => {
        console.log("Publisher stream created!", event);
      },
      streamDestroyed: event => {
        console.log("Publisher stream destroyed!", event);
      }
    };
```

```
<OTSession
          apiKey={this.apiKey}
          sessionId={this.props.tokboxSessionId}
          token={this.props.tokboxPublisherToken}
        >
          <OTPublisher
            style={{
              height: this.state.videoHeight,
              width: this.state.videoWidth
            }}
            properties={{ cameraPosition: this.state.cameraPosition }}
            eventHandlers={this.publisherEventHandlers}
          />
        </OTSession>
```

`opentok-react-native` version - `master`

**Comment by msach22** [comment]
@steverob Thanks for pointing this out! It looks like all publisher events will be unsupported because of a bug. I'll try to push a patch out by EOD (PST).

**Comment by steverob** [comment]
Yeah makes sense. Thanks a lot. That would be helpful.

--
Regards
Steve Robinson

**Comment by msach22** [comment]
@steverob released with `0.6.3`

**Comment by steverob** [comment]
Thanks! 

--
Regards
Steve Robinson

**Comment by adaerodriguez** [comment]
Hi guys, this error continue on version "opentok-react-native": "0.13.0". How can I solve this?

Thanks!

**Comment by fulfaro** [comment]
Hi adaerodriguez, we have the same error, but we changed function component to a pure component and it's running.

`
class VideoChatScreen extends Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.props.createToken();
  }

  render() {
    return (
        <View style={Styles.container}>
          {this.props.token ? (
            <OTSession
              apiKey={Model.videoChatInfo().apiKey}
              sessionId={this.props.sessionId}
              token={this.props.token}>
              <OTPublisher style={Styles.localPublisher} />
              <OTSubscriber style={Styles.localSubscriber} />
            </OTSession>
          ) : (
            <ActivityIndicator animating={true} color={Colors.red800} />
          )}
        </View>
    );
  }
}
`

**Comment by adaerodriguez** [comment]
Hi @fulfaro, thanks for your solution 👍
