### ISSUE TITLE
Android crashes when unmounting OTSession

### ISSUE THREAD

**Issue by ShugaSvc** [opentok/opentok-react-native#85]
Hi,

We are encountering a crash whenever a View containing OTSession unmounts really fast.

E.g. Start a Session then click the Android back really fast to unmount the View, the crash does not trigger a RN error but instead crashes the APP with the following ADB log:

05-18 23:08:48.656   518   534 W ActivityManager: Activity pause timeout for ActivityRecord{19b46e0 u0 com.uecareapp/.MainActivity t32 f}
05-18 23:08:59.478   518   534 W ActivityManager: Activity destroy timeout for ActivityRecord{19b46e0 u0 com.uecareapp/.MainActivity t32 f}
...

If we run with the JS debugger we get:
05-18 23:07:29.910  4832  4832 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeAllViews()' on a null object reference
05-18 23:07:29.910  4832  4832 E AndroidRuntime: 	at com.opentokreactnative.OTSessionManager$2.run(OTSessionManager.java:281)
05-18 23:07:29.910  4832  4832 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
...

Our current workaround is to delay unmounting of the parent View by approximately 2s so the crash would not happen.

**Comment by msach22** [comment]
This should go out with the `0.6.5` release.

**Comment by msach22** [comment]
@jclalala `0.6.5` has been released! Please let me know if you have any questions!
