### ISSUE TITLE
IOS crashes with EXC_BAD_ACCESS when unmounting using streamDestroyed events

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-react-native#86]
I face an error while unmounting OTSession, OTPublisher and OTSuscriber at the same time.

The streamDestroyed event called for the destroyed publisher causes a call in prepareJSEventData that raises the EXC_BAD_ACCESS at line:
    streamInfo["connectionId"] = stream.connection.connectionId;

Simply commenting this line solves my problem.

**Comment by msach22** [comment]
@mbouxin Thanks for reporting this. Could you please let me know which version of the library you're seeing this in?

**Comment by mbouxin** [comment]
I met this using:
- react native 0.55 
- opentok-react-native 0.6.3 
- opentok 2.14

**Comment by mbouxin** [comment]
Sorry, I tried to reproduce it and I can't anymore... Maybe there was another error in my app that triggered this. If I reproduce it, i will submit it again.
