### ISSUE TITLE
Yellow warnings on IOS in react-native 0.55

### ISSUE THREAD

**Issue by akandaurov** [opentok/opentok-react-native#87]
There are 3 yellow warnings in IOS simulator saying:
"Module **OTSubscriberSwift/OTSessionManager/OTPublisherSwift** requires main queue setup since it overrides `init` but does not implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of."

**Comment by msach22** [comment]
@akandaurov Thanks for reporting this! We will update these files in one of our future releases.

**Comment by msach22** [comment]
This should go out with `0.7.0`

**Comment by msach22** [comment]
Released with `0.7.0`
