### ISSUE TITLE
connection and stream creationTime are lost in the react native Bridge

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-react-native#96]
This is due to the fact that NSDate cannot be sent to the javascript.

I solved this issue by sending a Number of millisecond since 1970 like this:
https://gist.github.com/mbouxin/369597bce6b0653d9c9fcfceb7527a93

**Comment by msach22** [comment]
@mbouxin Thanks for opening this issue. I think we should keep it as a string just like we're doing for Android. This way the data will be exactly the same regardless of the platform.

I've opened a PR for this fix. Should go out with `0.7.0`

**Comment by msach22** [comment]
Released with `0.7.0`
